force-app/main/default/objects/Email_Request__c/Email_Request__c.object-meta.xml
<CustomObject>
    <label>Email Request</label>
    <nameField>
        <displayFormat>ERN-{000000}</displayFormat>
        <label>ERN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Request__c/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <description>body of the received email</description>
    <label>Email Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Request__c/fields/From_Address__c.field-meta.xml
<CustomField>
    <fullName>From_Address__c</fullName>
    <description>Email from Address</description>
    <label>From Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Request__c/fields/subject__c.field-meta.xml
<CustomField>
    <fullName>subject__c</fullName>
    <description>Email Subject</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Request__c/fields/To_Address__c.field-meta.xml
<CustomField>
    <fullName>To_Address__c</fullName>
    <description>To Address from email received</description>
    <label>To Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmailRequestHander.cls
global class EmailRequestHander implements Messaging.InboundEmailHandler {
      global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
          Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
          try{              
              Email_Request__c er = new Email_Request__c();
              er.From_Address__c = email.fromAddress;
              er.To_Address__c = email.toAddresses[0];
              er.Email_Body__c = email.plainTextBody;
              er.subject__c = email.subject;
              
              insert er;
              result.success = true;
            }
            catch(Exception e){
            }
        
        return result;
  }
  }