force-app/main/default/objects/NS_AssociatedAccount__c/NS_AssociatedAccount__c.object-meta.xml
<CustomObject>
    <description>Associated Accounts related to a contact</description>
    <label>Associated Account</label>
    <nameField>
        <displayFormat>AA-{000000}</displayFormat>
        <label>Associated Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_AssociatedAccount__c/fields/NS_AccountName__c.field-meta.xml
<CustomField>
    <fullName>NS_AccountName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Account</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Associated_Accounts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_AssociatedAccount__c/fields/NS_ContactName__c.field-meta.xml
<CustomField>
    <fullName>NS_ContactName__c</fullName>
    <description>Contact Related to a particular account</description>
    <label>Contact Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <errorMessage>Contact must be an Active Contact.</errorMessage>
        <filterItems>
            <field>Contact.NS_ContactStatus__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Contact.NS_ContactStatus__c</field>
            <operation>equals</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Accounts</relationshipLabel>
    <relationshipName>Associated_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NS_TriggerSettings__c/NS_TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings to enable/disable Trigger</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/NS_TriggerSettings__c/fields/NS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>NS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>To enable Contact Trigger</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AssociatedAccountTestFactory.cls
@isTest
public with sharing class AssociatedAccountTestFactory {
    /*Create Test Associated Account*/
    public static NS_AssociatedAccount__c buildAssociatedAccountRecord(Id accId, Id conId){
        NS_AssociatedAccount__c assoc = new NS_AssociatedAccount__c (
        NS_AccountName__c = accId,
        NS_ContactName__c = conId);
        return assoc;
    }
    /*Insert Test Associated Account*/
    public static NS_AssociatedAccount__c insertAssociatedAccountRecord(Id accId, Id conId){
        NS_AssociatedAccount__c assoc = new NS_AssociatedAccount__c (
        NS_AccountName__c = accId,
        NS_ContactName__c = conId);
        insert assoc;
        return assoc;
    }
    /*Enable Associated Account Trigger Settings*/
    public static void enableAssocAccountTrigger()
    {
        NS_TriggerSettings__c customSet1 = new NS_TriggerSettings__c(Name= NS_StaticVariablesUtility.assocTrigger); 
        customSet1.NS_IsActive__c = true;
        Database.insert(customSet1,false);
    }
}