force-app/main/default/objects/NS_AccountRelation__c/NS_AccountRelation__c.object-meta.xml
<CustomObject>
    <description>Non parent/child affiliation relations between NS accounts</description>
    <label>Account Relation</label>
    <nameField>
        <displayFormat>AR{0000000000}</displayFormat>
        <label>Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_AccountRelation__c/fields/NS_RelationParty1__c.field-meta.xml
<CustomField>
    <fullName>NS_RelationParty1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>From Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relationships</relationshipLabel>
    <relationshipName>NS_AccountRelation_Party1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_AccountRelation__c/fields/NS_RelationParty2__c.field-meta.xml
<CustomField>
    <fullName>NS_RelationParty2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations Party2</relationshipLabel>
    <relationshipName>NS_AccountRelations_Party2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_AccountRelation__c/fields/NS_RelationType__c.field-meta.xml
<CustomField>
    <fullName>NS_RelationType__c</fullName>
    <label>Relation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Autoramp</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Dock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NS_AccountRelationTriggerHelperTest.cls
@isTest(SeeAllData=false)
public class NS_AccountRelationTriggerHelperTest {

    public static testmethod void InsertMirrorRecordtest()
    {
    Account Acc1 = New Account();
    Account Acc2 = New Account();
    Acc1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
    Acc1.Name = 'test1';
    Acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
    Acc2.Name = 'test2';
    insert Acc1;
    insert Acc2;
    NS_AccountRelation__c AccR = new NS_AccountRelation__c();
    AccR.NS_RelationParty1__c = Acc1.id;
    AccR.NS_RelationParty2__c = Acc2.id;
    insert AccR;
    delete AccR;
    }
    public static testmethod void DeleteAccountRelationstest()
    {
    Account Acc1 = AccountTestFactory.createAccountRecord(NS_StaticVariablesUtility.Name);
    Account Acc2 = AccountTestFactory.createAccountRecord(NS_StaticVariablesUtility.Name);
    Account Acc3 = AccountTestFactory.createAccountRecord(NS_StaticVariablesUtility.Name);
    NS_AccountRelation__c AccR2 = new NS_AccountRelation__c();
    AccR2.NS_RelationParty1__c = Acc3.id;
    AccR2.NS_RelationParty2__c = Acc1.id;
    insert AccR2;
    NS_AccountRelation__c AccR3 = new NS_AccountRelation__c();
    AccR3.NS_RelationParty1__c = Acc2.id;
    AccR3.NS_RelationParty2__c = Acc3.id;
    insert AccR3;
    delete Acc3;
    }
    
    public static testmethod void DuplicateCheckPreventTest(){
        
      Account TestAccount1 = AccountTestFactory.createAccountRecord(NS_StaticVariablesUtility.Name);
      Account TestAccount2 = AccountTestFactory.createAccountRecord(NS_StaticVariablesUtility.Name);
      Account TestAccount3 = AccountTestFactory.createAccountRecord(NS_StaticVariablesUtility.Name);
      NS_AccountRelation__c ar1 = new NS_AccountRelation__c(
            NS_RelationParty1__c = TestAccount1.id,
            NS_RelationParty2__c = TestAccount2.id,
            NS_RelationType__c = 'Autoramp');
        insert ar1;
        
      NS_AccountRelation__c ar2 = new NS_AccountRelation__c(
            NS_RelationParty1__c = TestAccount3.id,
            NS_RelationParty2__c = TestAccount1.id,
            NS_RelationType__c = 'Autoramp');
        insert ar2;
        
    }    
}