force-app/main/default/objects/NS_TriggerSettings__c/NS_TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings to enable/disable Trigger</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/NS_TriggerSettings__c/fields/NS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>NS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>To enable Contact Trigger</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TaskTestFactory.cls
public class TaskTestFactory {
    /*Create test task Record*/
    public static Task createTaskRecord(String subject){
        Task obTask=new Task(
            RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName =: NS_StaticVariablesUtility.tskRecordType 
                            AND SobjectType =: NS_StaticVariablesUtility.tskObj].id,
            Subject=subject,
            ActivityDate = Date.today(),
            Status='New',
            Priority='Normal',
            Description='Test');
        return obTask;
    }
    /*Enable Task Trigger Settings*/
    public static void enableTaskTrigger()
    {
        NS_TriggerSettings__c cs1 = new NS_TriggerSettings__c(Name= NS_StaticVariablesUtility.tskTrigger); 
            cs1.NS_IsActive__c = true;
            Database.insert(cs1,false);
    }
}