force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Mapping__c.field-meta.xml
<CustomField>
    <fullName>Mapping__c</fullName>
    <label>Sub Capability</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Assignment &amp; Teams</fullName>
                <label>NS Account Teams</label>
            </value>
            <value>
                <fullName>Account Hierarchy</fullName>
            </value>
            <value>
                <fullName>Account Processes</fullName>
            </value>
            <value>
                <fullName>Account Reports &amp; Dashboards</fullName>
            </value>
            <value>
                <fullName>Account Search</fullName>
            </value>
            <value>
                <fullName>Account Types</fullName>
            </value>
            <value>
                <fullName>Account Visibility</fullName>
            </value>
            <value>
                <fullName>Activities Visibility &amp; Security</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
            <value>
                <fullName>Activity Creation</fullName>
            </value>
            <value>
                <fullName>Event Key Attributes</fullName>
                <label>Activity - Event Key Attributes</label>
            </value>
            <value>
                <fullName>Activity Reports &amp; Dashboards</fullName>
            </value>
            <value>
                <fullName>Task Key Attributes</fullName>
                <label>Activity - Task Key Attributes</label>
            </value>
            <value>
                <fullName>Activity Visibility</fullName>
            </value>
            <value>
                <fullName>Case Apex Automation &amp; Workflow Rules</fullName>
            </value>
            <value>
                <fullName>Case Close</fullName>
            </value>
            <value>
                <fullName>Case Core Functionalities</fullName>
            </value>
            <value>
                <fullName>Case Creation</fullName>
            </value>
            <value>
                <fullName>Case Email Collaboration</fullName>
            </value>
            <value>
                <fullName>Case Fields</fullName>
            </value>
            <value>
                <fullName>Case Home Page</fullName>
            </value>
            <value>
                <fullName>Case Mobile Push Notifications</fullName>
            </value>
            <value>
                <fullName>Case My Page</fullName>
            </value>
            <value>
                <fullName>Case Queues</fullName>
            </value>
            <value>
                <fullName>Case Record Types &amp; Page Layouts</fullName>
            </value>
            <value>
                <fullName>Case Search Results &amp; Related Lists/Buttons</fullName>
            </value>
            <value>
                <fullName>Case Validation Rules</fullName>
            </value>
            <value>
                <fullName>Configuring Aux Codes</fullName>
            </value>
            <value>
                <fullName>Configuring Wrap-up</fullName>
            </value>
            <value>
                <fullName>Contact Deactivation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Description__c.field-meta.xml
<CustomField>
    <fullName>Request_Description__c</fullName>
    <description>Gathers further details for requirements.</description>
    <inlineHelpText>Detailed Summary* 
Screen(s) Impacted* 
Field Name(s) &amp; Type(s)* 
Picklist Values 
Calculation 
Dependency 
Workflow/Approval Rules 
Interfacing System Updates 
Interface Frequency 
Data Volumes 
*Indicates information required for all requests!</inlineHelpText>
    <label>Initial Request</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Title__c.field-meta.xml
<CustomField>
    <fullName>Request_Title__c</fullName>
    <description>Captures the requirement title</description>
    <inlineHelpText>Captures the requirement title</inlineHelpText>
    <label>Request Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Requirement__c.field-meta.xml
<CustomField>
    <fullName>Requirement__c</fullName>
    <inlineHelpText>This is the improved request, this means we have now polished it.</inlineHelpText>
    <label>Requirement</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the request</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Identify: New Requirement</fullName>
                <default>true</default>
                <label>Identify: New Requirement</label>
            </value>
            <value>
                <fullName>Identify: Submit for Business Review</fullName>
            </value>
            <value>
                <fullName>Identify: Deferred</fullName>
            </value>
            <value>
                <fullName>Consolidate: Approve to Estimate</fullName>
            </value>
            <value>
                <fullName>Consolidate: Level of Effort Complete</fullName>
            </value>
            <value>
                <fullName>Approve: Approved to Deploy</fullName>
            </value>
            <value>
                <fullName>Release: Design</fullName>
            </value>
            <value>
                <fullName>Release: Build</fullName>
            </value>
            <value>
                <fullName>Release: Test</fullName>
            </value>
            <value>
                <fullName>Release: SIT</fullName>
            </value>
            <value>
                <fullName>Release: UAT</fullName>
            </value>
            <value>
                <fullName>Release: Build Production</fullName>
            </value>
            <value>
                <fullName>Release: Test Production</fullName>
            </value>
            <value>
                <fullName>Close: Deployed</fullName>
            </value>
            <value>
                <fullName>Close: Rejected</fullName>
            </value>
            <value>
                <fullName>Close: Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/Work_Assignment__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents the assignment of a specific unit of work to a project team member.</description>
    <label>Work Assignment</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Assignment__c/fields/Requirement_Number__c.field-meta.xml
<CustomField>
    <fullName>Requirement_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related request with the work assignment</description>
    <label>Requirement #</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Work Assignment</relationshipLabel>
    <relationshipName>Work_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the work asignment</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Development in Progress</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>Onshore Unit Testing Complete</fullName>
            </value>
            <value>
                <fullName>Ready for Final Review</fullName>
            </value>
            <value>
                <fullName>Client Reviewed and/or Ready for Next Environment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WorkAssignmentTriggerTest.cls
@isTest
private class WorkAssignmentTriggerTest {

    static testmethod void test_trigger(){
        
        Request__c reqRec = new Request__c( Mapping__c= 'Case Types');
        reqRec.Request_Title__c = 'Test';
        reqRec.Requirement__c = 'Test';
        reqRec.Request_Description__c ='Test';
        reqRec.Status__c = 'Identify: New Requirement';
        insert reqRec;
        
        Work_Assignment__c waRec = new Work_Assignment__c(Requirement_Number__c=reqRec.Id);
        
        insert waRec;
    }
}