force-app/main/default/objects/Related_Request_Script__c/Related_Request_Script__c.object-meta.xml
<CustomObject>
    <label>Related Request/Script</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Request/Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Request_Script__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Related Scripts</relationshipLabel>
    <relationshipName>RelatedScripts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_Request_Script__c/fields/Test_Script__c.field-meta.xml
<CustomField>
    <fullName>Test_Script__c</fullName>
    <label>Test Script</label>
    <referenceTo>Test_Script__c</referenceTo>
    <relationshipLabel>Related Requests</relationshipLabel>
    <relationshipName>RelatedRequest</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Release in which the request will go</description>
    <inlineHelpText>The release in which the request will actually be deployed. If the requirement has not been approved for a release, there should not be a value in this field.</inlineHelpText>
    <label>Committed Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Requests (Committed Release)</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/Test_Case__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a case for which you would run a test script.</description>
    <label>Test Scenario</label>
    <nameField>
        <label>Test Scenario ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Case__c/fields/Execution_Steps__c.field-meta.xml
<CustomField>
    <fullName>Execution_Steps__c</fullName>
    <description>Execution steps for the test case</description>
    <label>Test Script/ Steps</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>Expected_Result__c</fullName>
    <description>Expected results of the test case</description>
    <label>Expected Results</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Phase</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Test Scenarios</relationshipLabel>
    <relationshipName>Test_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Test Scenarios</relationshipLabel>
    <relationshipName>Test_Scenarios1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Test_Scenario__c.field-meta.xml
<CustomField>
    <fullName>Test_Scenario__c</fullName>
    <description>This is a description of the test scenario.</description>
    <label>Test Scenario Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Execution__c/Test_Execution__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents the execution of a test script in a specific case.</description>
    <label>Test Script Execution</label>
    <nameField>
        <displayFormat>TE-{0}</displayFormat>
        <label>Test Execution ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Execution__c/fields/Execution_Steps__c.field-meta.xml
<CustomField>
    <fullName>Execution_Steps__c</fullName>
    <label>Execution Steps</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Execution__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <formula>Test_Script_Description__r.Request__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Request</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Execution__c/fields/Test_Scenario__c.field-meta.xml
<CustomField>
    <fullName>Test_Scenario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Scenario</label>
    <referenceTo>Test_Scenario__c</referenceTo>
    <relationshipLabel>Test Script Executions</relationshipLabel>
    <relationshipName>Test_Script_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Execution_Cycle__c/Test_Execution_Cycle__c.object-meta.xml
<CustomObject>
    <label>Test Execution Cycle</label>
    <nameField>
        <label>Execution Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Execution Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Execution_Cycle__c/fields/Execution_Type__c.field-meta.xml
<CustomField>
    <fullName>Execution_Type__c</fullName>
    <label>Execution Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unit Test</fullName>
            </value>
            <value>
                <fullName>SIT</fullName>
            </value>
            <value>
                <fullName>Regression Test</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Execution_Cycle__c/fields/Release_Name__c.field-meta.xml
<CustomField>
    <fullName>Release_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release Name</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Test Execution Cycles</relationshipLabel>
    <relationshipName>Test_Execution_Cycles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Execution_Steps__c/Test_Execution_Steps__c.object-meta.xml
<CustomObject>
    <label>Test Execution Steps</label>
    <nameField>
        <label>Execution Steps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Execution Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Execution_Steps__c/fields/Actual_Result__c.field-meta.xml
<CustomField>
    <fullName>Actual_Result__c</fullName>
    <label>Actual Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Execution_Steps__c/fields/Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Result__c/Test_Result__c.object-meta.xml
<CustomObject>
    <label>Test Result</label>
    <nameField>
        <displayFormat>TestResult-{0000}</displayFormat>
        <label>Test Result ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Result__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Project Phase (e.g. Phase 1, Phase 2, etc.) that the Test Result is being logged in.</description>
    <inlineHelpText>Which Phase of the Project is this? (ie.g. Phase 1)</inlineHelpText>
    <label>Project Phase</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Test Results</relationshipLabel>
    <relationshipName>Test_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Scenario__c/Test_Scenario__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a test situation that verifies the fulfillment of a request.</description>
    <label>NA_Test Scenario</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>NA Test Scenario ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NA_Test Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Scenario__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related release of test scenario</description>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipName>Test_Scenarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Scenario__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It allows users to create Test Scenarios directly at request level to make testing flow more logical and create better traceability</description>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipName>Test_Scenarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/Test_Script__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents an executable script for a specific test scenario.</description>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{0}</displayFormat>
        <label>Test Script ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Script__c/fields/Execution_Steps__c.field-meta.xml
<CustomField>
    <fullName>Execution_Steps__c</fullName>
    <description>Execution steps for the test script</description>
    <label>Execution Steps</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/Execution_Type__c.field-meta.xml
<CustomField>
    <fullName>Execution_Type__c</fullName>
    <description>Type of test execution</description>
    <label>Execution Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unit Test</fullName>
            </value>
            <value>
                <fullName>SIT</fullName>
            </value>
            <value>
                <fullName>Regression Test</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>Expected_Result__c</fullName>
    <description>Expected results of the test script</description>
    <label>Expected Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release of the test script</description>
    <formula>Test_Scenario__r.Release__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Release</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Request for which the test script is created</description>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Test Scripts</relationshipLabel>
    <relationshipName>Test_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/Test_Scenario__c.field-meta.xml
<CustomField>
    <fullName>Test_Scenario__c</fullName>
    <description>Test scenario of the test script</description>
    <label>Test Scenario</label>
    <referenceTo>Test_Scenario__c</referenceTo>
    <relationshipLabel>Test Scripts</relationshipLabel>
    <relationshipName>Test_Scripts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_Script_Execution_cntrlr.cls
global class Test_Script_Execution_cntrlr
{
    
    Public String pId{get;set;}
    Public string rId {get;set;}
    public Test_Script_Execution_cntrlr(ApexPages.StandardController controller) {
        pId = apexpages.currentpage().getparameters().get('Id');
        rId = [Select Id,name,Release_Name__c from Test_Execution_Cycle__c WHERE Id=:pId].Release_Name__c;
    }
    
    Public  PageReference insertingTextExecution(){ 
        List<Test_Script__c> tsLst_repstry = new List<Test_Script__c>();
        List<Test_Execution__c> teLst_Lab = new List<Test_Execution__c>();
        List<Test_Execution_Steps__c> testpLst = new List<Test_Execution_Steps__c>();
        List<Execution_Steps__C> exstps = new List<Execution_Steps__c>();
        List<Related_Request_Script__c> rltdScrpts = new List<Related_Request_Script__c>();
        List<Related_Request_Script_Execution__c> rrseLst = new List<Related_Request_Script_Execution__c>();

        for(Test_Scenario__c ts: [select Id,Name,Release__c,(select id,Name,Test_Scenario__c,Execution_Steps__c,Execution_Type__c,    
                                    Expected_Result__c,Request__c,Actual_Result__c,Test_Result__c FROM Test_Scripts__r)
                                                FROM Test_Scenario__c WHERE Release__c =: rId]){
                        for(Test_Script__c tscr: ts.Test_Scripts__r){        
                            tsLst_repstry.add(tscr);
                        }       
        }
        
        
        
     List<Test_Script__c> testScrptExstps = [Select Id,Name,Test_Scenario__c,Request__c,Execution_Steps__c,Execution_Type__c,    
                                            Expected_Result__c, Actual_Result__c,Test_Result__c,Execution_Date__c, 
                                            (select Id,Name,Step_Name__c,Step_Order__c,Expected_Result__c,Input_Data__c,User_Login_Details__c,Test_Script_Name__c from Execution_Steps__r)
                                            FROM Test_Script__c WHERE ID IN:tsLst_repstry];
     
     for(Related_Request_Script__c rrs: [Select Id,Name, Request__c,Test_Script__c from Related_Request_Script__c WHERE Test_Script__c IN: tsLst_repstry]){
                     rltdScrpts.add(rrs);
     }
      
    
    System.debug('Test Script list is as follows'+tsLst_repstry);
    
        for(Test_Script__c ts: testScrptExstps){
            Test_Execution__c  te = new Test_Execution__c ();
            te.Execution_Cycle_Name__c = pId;
            te.Test_Script_Description__c = ts.Id;
            te.Request_Description__c = ts.Request__c;
            te.Test_Scenario__c = ts.Test_Scenario__c;
            //te.Execution_Steps__c = ts.Execution_Steps__c;
            //te.Execution_Date__c = ts.Execution_Date__c;
           // te.Execution_Type__c = ts.Execution_Type__c;
           //te.Test_Case__c = 'a0I19000000r7wx';   
            teLst_Lab.add(te);
            
             for(Execution_Steps__c esp: ts.Execution_Steps__r){
                
                exstps.add(esp);
            }
        }
        
        if(!teLst_Lab.isempty())
            Insert teLst_Lab;
            
        for(Test_Execution__c te:teLst_Lab){
            for(Execution_Steps__c estps: exstps){
                if(te.Test_Script_Description__c == estps.Test_Script_Name__c){
                    Test_Execution_Steps__c  testp = new Test_Execution_Steps__c();
                    testp.Step_Order__c = estps.Step_Order__c;
                    testp.Name = estps.Step_Name__c;
                    testp.Test_Execution_Name__c = te.Id;
                    testp.Expected_Result__c = estps.Expected_Result__c;
                    testp.Input_Data__c = estps.Input_Data__c;
                    testp.User_Login_Details__c = estps.User_Login_Details__c;
                    testpLst.add(testp);
                                
                }
            
            }
        
        
        }   
    
    
    if(!testpLst.isempty())
        Insert testpLst; 
        
        for(Test_Execution__c te:teLst_Lab){
            for(Related_Request_Script__c rs: rltdScrpts){
                    if(te.Test_Script_Description__c == rs.Test_Script__c){
                    
                    Related_Request_Script_Execution__c rse = new Related_Request_Script_Execution__c();
                    rse.Request_Id__c  = rs.Request__c;
                    rse.Test_Script_Execution__c = te.Id;
                    rrseLst.add(rse);
                    }
            }
        } 
       
       if(!rrseLst.isempty())
           Insert rrseLst;   
            
            
       PageReference pf = new Pagereference('/'+pId);
       return pf;
    }

}