force-app/main/default/objects/Execution_Steps__c/Execution_Steps__c.object-meta.xml
<CustomObject>
    <label>Test Script Steps</label>
    <nameField>
        <displayFormat>Ex-STP-{00000}</displayFormat>
        <label>Step No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Execution_Steps__c/fields/Step_Name__c.field-meta.xml
<CustomField>
    <fullName>Step_Name__c</fullName>
    <label>Step Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Execution_Steps__c/fields/Test_Script_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Script_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Script Name</label>
    <referenceTo>Test_Script__c</referenceTo>
    <relationshipName>Execution_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Execution_Steps__c/fields/User_Login_Details__c.field-meta.xml
<CustomField>
    <fullName>User_Login_Details__c</fullName>
    <label>User Login Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/Test_Script__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents an executable script for a specific test scenario.</description>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{0}</displayFormat>
        <label>Test Script ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Script__c/fields/Execution_Steps__c.field-meta.xml
<CustomField>
    <fullName>Execution_Steps__c</fullName>
    <description>Execution steps for the test script</description>
    <label>Execution Steps</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>Expected_Result__c</fullName>
    <description>Expected results of the test script</description>
    <label>Expected Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/Input_Data__c.field-meta.xml
<CustomField>
    <fullName>Input_Data__c</fullName>
    <description>Input data for the test script</description>
    <label>Input Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/Test_Script_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Script_Name__c</fullName>
    <label>Test Script Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/User_Login_Details__c.field-meta.xml
<CustomField>
    <fullName>User_Login_Details__c</fullName>
    <description>Added a field for User Details where login information will be added</description>
    <label>User Login Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/VFC_TScript_Steps_Export.cls
public with sharing class VFC_TScript_Steps_Export {

    
    
    Public String teId{get;set;}
    
    
    public VFC_TScript_Steps_Export(ApexPages.StandardController controller) {
            
            
            //  returnToPage();
    } 
    
    public VFC_TScript_Steps_Export(ApexPages.StandardSetController controller) {
        scrptLst = new List<Execution_Steps__c>();
        
        teId =  ApexPages.currentPage().getParameters().get('id');
        
         for(Execution_Steps__c est: [Select Id,name,Expected_Result__c,Step_Order__c,Input_Data__c,Step_Name__c,Test_Script_Name__c,Test_Script_Name__r.Id,User_Login_Details__c 
                                        FROM Execution_Steps__c  WHERE Test_Script_Name__c =: ApexPages.currentPage().getParameters().get('id')]){
                    scrptLst.add(est);
                
            }
            
         // returnToPage();
    }

    
    Public List<Execution_Steps__c> scrptLst {get;set;}
    
    
    
    Public VFC_TScript_Steps_Export(){
        scrptLst = new List<Execution_Steps__c>();
            
            for(Execution_Steps__c est: [Select Id,name,Expected_Result__c,Step_Order__c,Input_Data__c,Step_Name__c,Test_Script_Name__c,Test_Script_Name__r.Id,User_Login_Details__c 
                                        FROM Execution_Steps__c  WHERE Test_Script_Name__c =: ApexPages.currentPage().getParameters().get('id')]){
                    scrptLst.add(est);
                
            }
    
    }
     /* Public PageReference returnToPage(){
        PageReference pf = new PageReference('/'+teId);
        
        return pf;
    
    }   */

    
   }