force-app/main/default/objects/Execution_Steps__c/Execution_Steps__c.object-meta.xml
<CustomObject>
    <label>Test Script Steps</label>
    <nameField>
        <displayFormat>Ex-STP-{00000}</displayFormat>
        <label>Step No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Execution_Steps__c/fields/Step_Name__c.field-meta.xml
<CustomField>
    <fullName>Step_Name__c</fullName>
    <label>Step Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Execution_Steps__c/fields/Test_Script_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Script_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Script Name</label>
    <referenceTo>Test_Script__c</referenceTo>
    <relationshipName>Execution_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Execution_Steps__c/fields/User_Login_Details__c.field-meta.xml
<CustomField>
    <fullName>User_Login_Details__c</fullName>
    <label>User Login Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Planned_Release__c.field-meta.xml
<CustomField>
    <fullName>Planned_Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates each request to a Release or Project.</description>
    <inlineHelpText>This is the suggested release in which the requirement should be deployed.</inlineHelpText>
    <label>Planned Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipName>CRM_Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Release in which the request will go</description>
    <inlineHelpText>The release in which the request will actually be deployed. If the requirement has not been approved for a release, there should not be a value in this field.</inlineHelpText>
    <label>Committed Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Requests (Committed Release)</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Description__c.field-meta.xml
<CustomField>
    <fullName>Request_Description__c</fullName>
    <description>Gathers further details for requirements.</description>
    <inlineHelpText>Detailed Summary* 
Screen(s) Impacted* 
Field Name(s) &amp; Type(s)* 
Picklist Values 
Calculation 
Dependency 
Workflow/Approval Rules 
Interfacing System Updates 
Interface Frequency 
Data Volumes 
*Indicates information required for all requests!</inlineHelpText>
    <label>Initial Request</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Title__c.field-meta.xml
<CustomField>
    <fullName>Request_Title__c</fullName>
    <description>Captures the requirement title</description>
    <inlineHelpText>Captures the requirement title</inlineHelpText>
    <label>Request Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>Type of the request</description>
    <inlineHelpText>If you are unsure of the type of request you are submitting, please select Unknown.</inlineHelpText>
    <label>Request Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Configuration</fullName>
            </value>
            <value>
                <fullName>Custom Code</fullName>
            </value>
            <value>
                <fullName>Data Access</fullName>
            </value>
            <value>
                <fullName>Data Migration</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>User Administration</fullName>
            </value>
            <value>
                <fullName>User Story</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the request</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Identify: New Requirement</fullName>
                <default>true</default>
                <label>Identify: New Requirement</label>
            </value>
            <value>
                <fullName>Identify: Submit for Business Review</fullName>
            </value>
            <value>
                <fullName>Identify: Deferred</fullName>
            </value>
            <value>
                <fullName>Consolidate: Approve to Estimate</fullName>
            </value>
            <value>
                <fullName>Consolidate: Level of Effort Complete</fullName>
            </value>
            <value>
                <fullName>Approve: Approved to Deploy</fullName>
            </value>
            <value>
                <fullName>Release: Design</fullName>
            </value>
            <value>
                <fullName>Release: Build</fullName>
            </value>
            <value>
                <fullName>Release: Test</fullName>
            </value>
            <value>
                <fullName>Release: SIT</fullName>
            </value>
            <value>
                <fullName>Release: UAT</fullName>
            </value>
            <value>
                <fullName>Release: Build Production</fullName>
            </value>
            <value>
                <fullName>Release: Test Production</fullName>
            </value>
            <value>
                <fullName>Close: Deployed</fullName>
            </value>
            <value>
                <fullName>Close: Rejected</fullName>
            </value>
            <value>
                <fullName>Close: Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Scenario__c/Test_Scenario__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a test situation that verifies the fulfillment of a request.</description>
    <label>NA_Test Scenario</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>NA Test Scenario ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NA_Test Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Scenario__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related release of test scenario</description>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipName>Test_Scenarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Scenario__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It allows users to create Test Scenarios directly at request level to make testing flow more logical and create better traceability</description>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipName>Test_Scenarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Scenario__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of test scenario</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Script__c/Test_Script__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents an executable script for a specific test scenario.</description>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{0}</displayFormat>
        <label>Test Script ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Script__c/fields/Execution_Steps__c.field-meta.xml
<CustomField>
    <fullName>Execution_Steps__c</fullName>
    <description>Execution steps for the test script</description>
    <label>Execution Steps</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>Expected_Result__c</fullName>
    <description>Expected results of the test script</description>
    <label>Expected Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/Input_Data__c.field-meta.xml
<CustomField>
    <fullName>Input_Data__c</fullName>
    <description>Input data for the test script</description>
    <label>Input Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release of the test script</description>
    <formula>Test_Scenario__r.Release__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Release</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Request for which the test script is created</description>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Test Scripts</relationshipLabel>
    <relationshipName>Test_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/Test_Scenario__c.field-meta.xml
<CustomField>
    <fullName>Test_Scenario__c</fullName>
    <description>Test scenario of the test script</description>
    <label>Test Scenario</label>
    <referenceTo>Test_Scenario__c</referenceTo>
    <relationshipLabel>Test Scripts</relationshipLabel>
    <relationshipName>Test_Scripts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/Test_Script_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Script_Name__c</fullName>
    <label>Test Script Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Script__c/fields/User_Login_Details__c.field-meta.xml
<CustomField>
    <fullName>User_Login_Details__c</fullName>
    <description>Added a field for User Details where login information will be added</description>
    <label>User Login Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/VFC_TestScript_Steps_Export_Tes.cls
@isTest
Public class VFC_TestScript_Steps_Export_Tes{
    Public static testMethod Void VFC_TestScript_Steps_Export_Tes(){
        Release__c rl = new Release__c();
        rl.Name = 'TestRelease';
        
        Insert rl;
        
        Request__c rq = new Request__c();
        rq.Request_Title__c  = 'TestREquest';
        rq.Status__c = 'Release: Build';
        rq.Request_Type__c = 'Configuration';
        rq.Request_Description__c = 'TestDescription';
        rq.Planned_Release__c = rl.Id;
        
        Insert rq;
        
        Test_Scenario__c ts = new Test_Scenario__c();
        ts.Release__c = rl.Id;
        ts.Request__c = rq.Id;
        Insert ts;
        
        Test_Script__c tsp = new Test_Script__c();
        tsp.Test_Scenario__c = ts.Id;
        Insert tsp;
        
        Execution_Steps__c es = new Execution_Steps__c();
        es.Step_Name__c = 'TestStep';
        es.Expected_Result__c = 'Test Expected Result';
        es.Input_Data__c = 'Test Input Data';
        es.Test_Script_Name__c = tsp.Id;
        es.User_Login_Details__c = 'Test User Login details';
        
        Insert es;
        
        List<Test_Script__c> tsLst = new List<Test_Script__c>{tsp};
        
        
        ApexPages.currentPage().getParameters().put('id',tsp.Id);
        
        ApexPages.StandardSetController sst = new ApexPages.StandardSetController(tsLst);
        VFC_TScript_Steps_Export tse2 = new VFC_TScript_Steps_Export(sst);
        
        
        ApexPages.StandardController  std = new ApexPages.StandardController(tsp);
        VFC_TScript_Steps_Export tse = new VFC_TScript_Steps_Export(std);
        
        VFC_TScript_Steps_Export tse1 = new VFC_TScript_Steps_Export();
        
        
    
    
    }

}