force-app/main/default/objects/Execution_Steps__c/Execution_Steps__c.object-meta.xml
<CustomObject>
    <label>Test Script Steps</label>
    <nameField>
        <displayFormat>Ex-STP-{00000}</displayFormat>
        <label>Step No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Case__c/Test_Case__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a case for which you would run a test script.</description>
    <label>Test Scenario</label>
    <nameField>
        <label>Test Scenario ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Case__c/fields/Execution_Status__c.field-meta.xml
<CustomField>
    <fullName>Execution_Status__c</fullName>
    <label>Execution Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Execution_Steps__c.field-meta.xml
<CustomField>
    <fullName>Execution_Steps__c</fullName>
    <description>Execution steps for the test case</description>
    <label>Test Script/ Steps</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>Expected_Result__c</fullName>
    <description>Expected results of the test case</description>
    <label>Expected Results</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Phase</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Test Scenarios</relationshipLabel>
    <relationshipName>Test_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Test_Phase__c.field-meta.xml
<CustomField>
    <fullName>Test_Phase__c</fullName>
    <label>Testing Stage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIT</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>End-to-End</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>BUILD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Test_Scenario__c.field-meta.xml
<CustomField>
    <fullName>Test_Scenario__c</fullName>
    <description>This is a description of the test scenario.</description>
    <label>Test Scenario Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Test_Script_Description__c.field-meta.xml
<CustomField>
    <fullName>Test_Script_Description__c</fullName>
    <label>Test Script Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Total_Results_Expected__c.field-meta.xml
<CustomField>
    <fullName>Total_Results_Expected__c</fullName>
    <label>Total Results Expected</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <description>This is the User that the tester will log in as to test the scenario.</description>
    <label>User</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OSS Rep</fullName>
            </value>
            <value>
                <fullName>OSS Manager</fullName>
            </value>
            <value>
                <fullName>OSS Support</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Marketing User</fullName>
                <label>Marketing Leadership</label>
            </value>
            <value>
                <fullName>LSS</fullName>
            </value>
            <value>
                <fullName>Automotive Leadership</fullName>
            </value>
            <value>
                <fullName>Automotive Manager</fullName>
            </value>
            <value>
                <fullName>UTS Leadership</fullName>
            </value>
            <value>
                <fullName>UTS Manager</fullName>
            </value>
            <value>
                <fullName>EP Leadership</fullName>
            </value>
            <value>
                <fullName>EP Manager</fullName>
            </value>
            <value>
                <fullName>Marketing Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Result__c/Test_Result__c.object-meta.xml
<CustomObject>
    <label>Test Result</label>
    <nameField>
        <displayFormat>TestResult-{0000}</displayFormat>
        <label>Test Result ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Result__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Project Phase (e.g. Phase 1, Phase 2, etc.) that the Test Result is being logged in.</description>
    <inlineHelpText>Which Phase of the Project is this? (ie.g. Phase 1)</inlineHelpText>
    <label>Project Phase</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Test Results</relationshipLabel>
    <relationshipName>Test_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Result__c/fields/Test_Case__c.field-meta.xml
<CustomField>
    <fullName>Test_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Scenario</label>
    <referenceTo>Test_Case__c</referenceTo>
    <relationshipLabel>Test Results</relationshipLabel>
    <relationshipName>Test_Results1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Result__c/fields/Test_Result__c.field-meta.xml
<CustomField>
    <fullName>Test_Result__c</fullName>
    <inlineHelpText>If ANY step failed, please log the Test Result as Failed.</inlineHelpText>
    <label>Test Result?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Result__c/fields/Tester__c.field-meta.xml
<CustomField>
    <fullName>Tester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Who is the Tester logging this Test Result?</inlineHelpText>
    <label>Tester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Test_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Result__c/fields/Testing_Phase__c.field-meta.xml
<CustomField>
    <fullName>Testing_Phase__c</fullName>
    <label>Testing Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIT</fullName>
            </value>
            <value>
                <fullName>End-to-End</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Result__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OSS Rep</fullName>
            </value>
            <value>
                <fullName>OSS Manager</fullName>
            </value>
            <value>
                <fullName>OSS Support</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Marketing User</fullName>
                <label>Marketing Leadership</label>
            </value>
            <value>
                <fullName>Integration User</fullName>
            </value>
            <value>
                <fullName>EP Leadership</fullName>
            </value>
            <value>
                <fullName>EP Manager</fullName>
            </value>
            <value>
                <fullName>UT Leadership</fullName>
            </value>
            <value>
                <fullName>UT Manager</fullName>
            </value>
            <value>
                <fullName>Automotive Leadership</fullName>
            </value>
            <value>
                <fullName>Automotive Manager</fullName>
            </value>
            <value>
                <fullName>Marketing Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Scenario__c/Test_Scenario__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a test situation that verifies the fulfillment of a request.</description>
    <label>NA_Test Scenario</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>NA Test Scenario ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NA_Test Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Scenario__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related release of test scenario</description>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipName>Test_Scenarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Scenario__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of test scenario</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestResultTriggerHelperTest.cls
@isTest(SeeAllData=false)
private class TestResultTriggerHelperTest {
    public static testMethod void FailedTestResult(){
        System.test.StartTest();
        Release__c rel = new Release__c();
        rel.Name='R1';
        Insert rel;
        
        Test_Case__c tc = new Test_Case__c();
        tc.Name ='Test';
        tc.Test_Scenario__c = 'Test';
        tc.Test_Phase__c = 'SIT';
        tc.User__c='OSS Rep';
        tc.Test_Script_Description__c = 'Test';
        tc.Execution_Steps__c = 'test';
        tc.Expected_Result__c = 'Test';
        tc.Total_Results_Expected__c ='Test';
        //tc.Status__c = 'Draft';
        tc.Release__c = rel.Id;
        Insert tc;
        
        Test_Result__c tr= new Test_Result__c();
        tr.User__c='OSS Rep';
        tr.Tester__c = system.UserInfo.getUserId();
        tr.Test_Case__c = tc.Id;
        tr.Testing_Phase__c ='SIT';
        tr.Test_Result__c = 'In Progress';
        insert tr;
        
        Test_Case__c tc1 = [Select Id,Execution_Status__c From Test_Case__c limit 1];
        system.assertEquals('Pending', tc1.Execution_Status__c);
        
        tr.Test_Result__c = 'Passed';
        update tr;
        
        Test_Case__c tc2 = [Select Id,Execution_Status__c From Test_Case__c limit 1];
        system.assertEquals('Passed', tc2.Execution_Status__c);
        
        Test_Result__c tr2= new Test_Result__c();
        tr2.User__c='OSS Rep';
        tr2.Tester__c = system.UserInfo.getUserId();
        tr2.Test_Case__c = tc.Id;
        tr2.Testing_Phase__c ='SIT';
        tr2.Test_Result__c = 'Failed';
        insert tr2;
        
        Test_Case__c tc3 = [Select Id,Execution_Status__c From Test_Case__c limit 1];
        system.assertEquals('Failed', tc3.Execution_Status__c);
        System.test.StopTest();
    }
}