force-app/main/default/objects/Allocation_Details__c/Allocation_Details__c.object-meta.xml
<CustomObject>
    <label>Allocation Details</label>
    <nameField>
        <displayFormat>AD-{0}</displayFormat>
        <label>Allocation Week</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocation Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Allocation_Details__c/fields/Employee_Allocation_Details__c.field-meta.xml
<CustomField>
    <fullName>Employee_Allocation_Details__c</fullName>
    <label>Employee Allocation Details</label>
    <referenceTo>Employee_Allocation__c</referenceTo>
    <relationshipLabel>Allocation Details</relationshipLabel>
    <relationshipName>Allocation_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Release_End_Month__c.field-meta.xml
<CustomField>
    <fullName>Release_End_Month__c</fullName>
    <formula>Employee_Allocation_Details__r.End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Allocation End Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Release_Month__c.field-meta.xml
<CustomField>
    <fullName>Release_Month__c</fullName>
    <formula>Employee_Allocation_Details__r.Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Allocation Start Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Year_of_Month__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Month__c</fullName>
    <formula>CASE(
MONTH(Weekly_Start_Date__c),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;,
4, &quot;April&quot;,
5, &quot;May&quot;,
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year of Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Presales</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Allocation__c/Employee_Allocation__c.object-meta.xml
<CustomObject>
    <label>Employee Allocation</label>
    <nameField>
        <displayFormat>EA-{000000}</displayFormat>
        <label>Employee Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Allocation__c/fields/Allocation_End_Date_Month__c.field-meta.xml
<CustomField>
    <fullName>Allocation_End_Date_Month__c</fullName>
    <formula>CASE( 
MONTH(End_Date__c), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
12, &quot;December&quot;, 
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Allocation End Date Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Allocation__c/fields/Allocation_Start_Date_Month__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Start_Date_Month__c</fullName>
    <formula>CASE( 
MONTH(Start_Date__c), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
12, &quot;December&quot;, 
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Allocation Start Date Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Allocation__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Allocations</relationshipLabel>
    <relationshipName>Employee_Alocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Allocation__c/fields/Release_Name__c.field-meta.xml
<CustomField>
    <fullName>Release_Name__c</fullName>
    <label>Release Name</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Employee Allocations</relationshipLabel>
    <relationshipName>Employee_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Allocation__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>YEAR(Release_Name__r.Proejct_Start_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Proejct_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Proejct_Start_Date__c</fullName>
    <label>Project Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Project_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_End_Date__c</fullName>
    <label>Project End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release_Planned_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Planned_End_Date__c</fullName>
    <description>Estimated date of end of release</description>
    <label>Release Planned End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Start_Date__c</fullName>
    <description>Start Date of release</description>
    <label>Planned Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Weekly_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Start_Date__c</fullName>
    <formula>CASE( 
MONTH( Proejct_Start_Date__c), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
12, &quot;December&quot;, 
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weekly_Start_Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VFC_EmployeeAllocation_Clone_Test.cls
@isTest
public class VFC_EmployeeAllocation_Clone_Test {
    
    private static testMethod void VFC_EmployeeAllocation_Clone_Test(){
        
        
        
        Employee__c emp = new Employee__c();
        emp.Name = 'TestEMployyee';
        emp.Country__c='US';
        
        Insert emp;
        
        Release__c rl = new Release__c();
        rl.Name = 'TestRelease';
        Insert rl;

        
        Employee_Allocation__c EA = new Employee_Allocation__c();
        
        EA.Employee_Name__c=emp.id;
        EA.End_Date__c=Date.newInstance(2018, 2, 30);
        EA.Release_Name__c=rl.id;
        EA.Start_Date__c=Date.newInstance(2018, 1, 30);
        insert EA;
        
         Allocation_Details__c ad = new Allocation_Details__c();
        //ad.Name = 'TestWeek';
        ad.Employee_Allocation_Details__c = ea.Id;
        //ad.Year_of_Month__c = 'August';
        //ad.Release_Month__c = system.Today();
        //ad.Release_End_Month__c = system.Today().addDays(10);
        ad.Weekly_Start_Date__c = system.Today().addDays(0);
        Insert ad;
        
        
        
        ApexPages.StandardController sc = new ApexPages.StandardController(emp);
        VFC_EmployeeAllocation_Clone testAccPlan = new VFC_EmployeeAllocation_Clone(sc);
        
        PageReference pageRef = Page.VFP_EmployeeAllocation_Clone;
        pageRef.getParameters().put('id', emp.Id);
        Test.setCurrentPage(pageRef);
        
        
        testAccPlan.getmonths();
        testAccPlan.selectedmonth = 'January';
        testAccPlan.searchvalues();
        testAccPlan.selectedmonth = 'January';
        testAccPlan.searchvalues();
        testAccPlan.selectedmonth = 'February';
        testAccPlan.searchvalues();
        testAccPlan.selectedmonth = 'March';
        testAccPlan.searchvalues();
        testAccPlan.selectedmonth = 'April';
        testAccPlan.searchvalues();
        testAccPlan.selectedmonth = 'May';
        testAccPlan.searchvalues();
        testAccPlan.selectedmonth = 'June';
        testAccPlan.searchvalues();
        testAccPlan.selectedmonth = 'July';
        testAccPlan.searchvalues();
        testAccPlan.selectedmonth = 'August';
        testAccPlan.searchvalues();
        testAccPlan.selectedmonth = 'September';
        testAccPlan.searchvalues();
        testAccPlan.selectedmonth = 'October';
        testAccPlan.searchvalues();
        testAccPlan.selectedmonth = 'November';
        testAccPlan.searchvalues();
        testAccPlan.selectedmonth = 'December';
        testAccPlan.searchvalues();  
        testAccPlan.goback();
        testAccPlan.Updatevalues();
        testAccPlan.selectedmonth = '- None -';
        testAccPlan.enteredhours=01;
        testAccPlan.searchvalues();
        testAccPlan.Month='1';
        testAccPlan.Applyvalues();
  
        System.debug('SRV '+ [Select id FROM Employee_Allocation__c WHERE Employee_Name__c =:apexpages.currentPage().getParameters().get('id')]);
        
system.debug('SRV '+[select Id, Name,Employee_Name__c,Employee_Name__r.Name,Employee_Name__r.Project__c,End_Date__c,Release_Name__c,Year__c,
                                               Release_Name__r.Name,Start_Date__c,Release_Name__r.Proejct_Start_Date__c,Release_Name__r.Release_Start_Date__c,Release_Name__r.Release_Planned_End_Date__c,
                                               Release_Name__r.Project_End_Date__c
                                               FROM Employee_Allocation__c
                                               WHERE Employee_Name__c =: apexpages.currentPage().getParameters().get('id')]);        
    
        
    
    }
    
     private static testMethod void VFC_EmployeeAllocation_Clone_Test01(){
        
        
        
        Employee__c emp = new Employee__c();
        emp.Name = 'TestEMployyee';
        emp.Country__c='US';
        
        Insert emp;
        
        Release__c rl = new Release__c();
        rl.Name = 'TestRelease';
        Insert rl;

        
        Employee_Allocation__c EA = new Employee_Allocation__c();
        
        EA.Employee_Name__c=emp.id;
        EA.End_Date__c=Date.newInstance(2018, 11, 30);
        EA.Release_Name__c=rl.id;
        EA.Start_Date__c=Date.newInstance(2018, 11, 29);
        insert EA;
        
         Allocation_Details__c ad = new Allocation_Details__c();
        //ad.Name = 'TestWeek';
        ad.Employee_Allocation_Details__c = ea.Id;
        //ad.Year_of_Month__c = 'August';
        //ad.Release_Month__c = system.Today();
        //ad.Release_End_Month__c = system.Today().addDays(10);
        ad.Weekly_Start_Date__c = system.Today().addDays(0);
        Insert ad;
        
        
        
        ApexPages.StandardController sc = new ApexPages.StandardController(emp);
        VFC_EmployeeAllocation_Clone testAccPlan = new VFC_EmployeeAllocation_Clone(sc);
        
        PageReference pageRef = Page.VFP_EmployeeAllocation_Clone;
        pageRef.getParameters().put('id', emp.Id);
        Test.setCurrentPage(pageRef);

        testAccPlan.selectedmonth = '- None -';
        testAccPlan.enteredhours=01;
        testAccPlan.searchvalues();
        testAccPlan.Month='1';
        testAccPlan.Applyvalues();
  
        System.debug('SRV '+ [Select Allocation_Start_Date_Month__c,Allocation_End_Date_Month__c FROM Employee_Allocation__c WHERE Employee_Name__c =:apexpages.currentPage().getParameters().get('id')]);
        
system.debug('SRV '+[select Id, Name,Employee_Name__c,Employee_Name__r.Name,Employee_Name__r.Project__c,End_Date__c,Release_Name__c,Year__c,
                                               Release_Name__r.Name,Start_Date__c,Release_Name__r.Proejct_Start_Date__c,Release_Name__r.Release_Start_Date__c,Release_Name__r.Release_Planned_End_Date__c,
                                               Release_Name__r.Project_End_Date__c,
                                               (Select Id,Name,Year_of_Month__c,Employee_Allocation_Details__r.Release_Name__c from Allocation_Details__r)
                                               FROM Employee_Allocation__c
                                               WHERE Employee_Name__c =: apexpages.currentPage().getParameters().get('id')]);        
    
        
    
    }
}