force-app/main/default/objects/Allocation_Details__c/Allocation_Details__c.object-meta.xml
<CustomObject>
    <label>Allocation Details</label>
    <nameField>
        <displayFormat>AD-{0}</displayFormat>
        <label>Allocation Week</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocation Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Allocation_Details__c/fields/Allocation_Hours__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Hours__c</fullName>
    <label>Allocation Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Employee_Allocation_Details__c.field-meta.xml
<CustomField>
    <fullName>Employee_Allocation_Details__c</fullName>
    <label>Employee Allocation Details</label>
    <referenceTo>Employee_Allocation__c</referenceTo>
    <relationshipLabel>Allocation Details</relationshipLabel>
    <relationshipName>Allocation_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Planned_Vocation_Hours__c.field-meta.xml
<CustomField>
    <fullName>Planned_Vocation_Hours__c</fullName>
    <label>Planned Vocation Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Release_End_Month__c.field-meta.xml
<CustomField>
    <fullName>Release_End_Month__c</fullName>
    <formula>Employee_Allocation_Details__r.End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Allocation End Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Release_Month__c.field-meta.xml
<CustomField>
    <fullName>Release_Month__c</fullName>
    <formula>Employee_Allocation_Details__r.Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Allocation Start Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Vacation_Hours__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Vacation Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Year_of_Month__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Month__c</fullName>
    <formula>CASE(
MONTH(Weekly_Start_Date__c),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;,
4, &quot;April&quot;,
5, &quot;May&quot;,
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year of Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Allocation__c/Employee_Allocation__c.object-meta.xml
<CustomObject>
    <label>Employee Allocation</label>
    <nameField>
        <displayFormat>EA-{000000}</displayFormat>
        <label>Employee Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Allocation__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Allocations</relationshipLabel>
    <relationshipName>Employee_Alocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Allocation__c/fields/Release_Name__c.field-meta.xml
<CustomField>
    <fullName>Release_Name__c</fullName>
    <label>Release Name</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Employee Allocations</relationshipLabel>
    <relationshipName>Employee_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Weekly_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Start_Date__c</fullName>
    <formula>CASE( 
MONTH( Proejct_Start_Date__c), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
12, &quot;December&quot;, 
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weekly_Start_Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vacation__c/Vacation__c.object-meta.xml
<CustomObject>
    <label>Out of Office</label>
    <nameField>
        <label>Out of Office Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Out of Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Vacations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacation__c/fields/Weekly_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Start_Date__c</fullName>
    <label>Weekly Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/VFE_Release_Employee_Allocation_Test.cls
@isTest
Public class VFE_Release_Employee_Allocation_Test{
    Public static testMethod void VFE_Release_Employee_Allocation_Test(){
    
        Release__c rl = new Release__c();
        rl.Name = 'TestRelease';
        
        Insert rl;
        
        Employee__c emp = new Employee__c();
        emp.Name = 'TestEMployyee';
        Insert emp;
        
        Employee_Allocation__c ea = new Employee_Allocation__c();
        ea.Release_Name__c = rl.Id;
        ea.Employee_Name__c = emp.Id;
        ea.Start_Date__c = system.Today();
        ea.End_Date__c = system.Today().addDays(10);
        Insert ea;
        
        Allocation_Details__c ad = new Allocation_Details__c();
        //ad.Name = 'TestWeek';
        ad.Employee_Allocation_Details__c = ea.Id;
        //ad.Year_of_Month__c = 'August';
        //ad.Release_Month__c = system.Today();
        //ad.Release_End_Month__c = system.Today().addDays(10);
        ad.Weekly_Start_Date__c = system.Today().addDays(0);
        Insert ad;
        
        Vacation__c vc = new Vacation__c();
        vc.Name = 'TestVcation';
        vc.Contact__c = emp.Id;
        Insert vc;
        
        List<Allocation_Details__c> aldllst = new List<Allocation_Details__c >{ad};
        
        apexpages.currentPage().getParameters().put('id',rl.Id);
        
        VFE_Release_Employee_Allocation_Clone.EmployAllcation eal = new VFE_Release_Employee_Allocation_Clone.EmployAllcation(ea);
        eal.selected = true;
        ApexPages.StandardController contrlr = new ApexPages.StandardController(rl);
        VFE_Release_Employee_Allocation_Clone vrm = new VFE_Release_Employee_Allocation_Clone(contrlr);
        vrm.getmonths();
        vrm.searchvalues();
        vrm.Applyvalues();
        vrm.Updatevalues();
        vrm.goback();
        
        vrm.vacation = 40;
        vrm.enteredhours =30;
        vrm.selectedmonth = 'August';
        
        /*System.assertnotEquals(vrm.month,'January');
        System.assertnotEquals(vrm.month,'February');
        System.assertnotEquals(vrm.month,'March');
        System.assertnotEquals(vrm.month,'April');
        System.assertnotEquals(vrm.month,'May');
        System.assertnotEquals(vrm.month,'June');
        System.assertnotEquals(vrm.month,'July');
       // System.assertEquals(vrm.month,'August');
        //System.assertnotEquals(vrm.month,'September');
        System.assertnotEquals(vrm.month,'October');
        System.assertnotEquals(vrm.month,'November');
        System.assertnotEquals(vrm.month,'December');*/
    }
    
    Public static testMethod void VFE_Release_Employee_Allocation_Test1(){
    
        Release__c rl = new Release__c();
        rl.Name = 'TestRelease';
        
        Insert rl;
        
        Employee__c emp = new Employee__c();
        emp.Name = 'TestEMployyee';
        Insert emp;
        
        Employee_Allocation__c ea = new Employee_Allocation__c();
        ea.Release_Name__c = rl.Id;
        ea.Employee_Name__c = emp.Id;
        ea.Start_Date__c = system.Today();
        ea.End_Date__c = system.Today().addDays(10);
        Insert ea;
        
        Allocation_Details__c ad = new Allocation_Details__c();
        //ad.Name = 'TestWeek';
        ad.Employee_Allocation_Details__c = ea.Id;
        //ad.Release_Month__c = system.Today();
        //ad.Release_End_Month__c = system.Today().addDays(10);
        ad.Weekly_Start_Date__c = system.Today().addDays(0);
        Insert ad;
        
        Vacation__c vc = new Vacation__c();
        vc.Name = 'TestVcation';
        vc.Contact__c = emp.Id;
        Insert vc;
        
        List<Allocation_Details__c> aldllst = new List<Allocation_Details__c >{ad};
        
        apexpages.currentPage().getParameters().put('id',rl.Id);
        
        VFE_Release_Employee_Allocation_Clone.EmployAllcation eal = new VFE_Release_Employee_Allocation_Clone.EmployAllcation(ea);
        
        eal.selected = true;
        ApexPages.StandardController contrlr = new ApexPages.StandardController(rl);
        VFE_Release_Employee_Allocation_Clone vrm = new VFE_Release_Employee_Allocation_Clone(contrlr);
        vrm.getmonths();
        System.assertEquals(vrm.selectedmonth ,null);
        vrm.searchvalues();
        vrm.Applyvalues();
        vrm.Updatevalues();
        vrm.goback();
        
        
        
        vrm.vacation = 40;
        vrm.enteredhours =30;
        //vrm.selectedmonth = '- None -';
        
      
        }

     Public static testMethod void VFE_Release_Employee_Allocation_Test2(){
    
        Release__c rl = new Release__c();
        rl.Name = 'TestRelease';
        
        Insert rl;
        
        Employee__c emp = new Employee__c();
        emp.Name = 'TestEMployyee';
        Insert emp;
        
        Employee_Allocation__c ea = new Employee_Allocation__c();
        ea.Release_Name__c = rl.Id;
        ea.Employee_Name__c = emp.Id;
        ea.Start_Date__c = system.Today();
        ea.End_Date__c = system.Today().addDays(10);
        Insert ea;
        
        Allocation_Details__c ad = new Allocation_Details__c();
        //ad.Name = 'TestWeek';
        ad.Employee_Allocation_Details__c = ea.Id;
        //ad.Name = 'TestWeek1';        
        ad.Vacation_Hours__c = 50;
        ad.Planned_Vocation_Hours__c = 40;
        ad.Allocation_Hours__c = 50;
        //ad.Release_Month__c = system.Today();
        //ad.Release_End_Month__c = system.Today().addDays(10);
        ad.Weekly_Start_Date__c = system.Today().addDays(0);

        
        Vacation__c vc = new Vacation__c();
        vc.Name = 'TestVcation';
        vc.Contact__c = emp.Id;
        Insert vc;
        
        List<Allocation_Details__c> aldllst = new List<Allocation_Details__c >{ad};
        
        apexpages.currentPage().getParameters().put('id',rl.Id);
        
        VFE_Release_Employee_Allocation_Clone.EmployAllcation eal = new VFE_Release_Employee_Allocation_Clone.EmployAllcation(ea);
        
        eal.selected = False;
        ApexPages.StandardController contrlr = new ApexPages.StandardController(rl);
        VFE_Release_Employee_Allocation_Clone vrm = new VFE_Release_Employee_Allocation_Clone(contrlr);
        vrm.selectedmonth = 'august';
        vrm.enteredhours = 50;
        vrm.getmonths();
         
       // System.assertEquals(vrm.selectedmonth ,null);
        vrm.searchvalues();
        vrm.Applyvalues();
        vrm.Updatevalues();
        vrm.goback();
        
        
        
        vrm.vacation = 40;
        vrm.enteredhours =30;
        //vrm.selectedmonth = '- None -';
        
      
        }
         Public static testMethod void VFE_Release_Employee_Allocation_Test3(){
    
        Release__c rl = new Release__c();
        rl.Name = 'TestRelease';
        
        Insert rl;
        
        Employee__c emp = new Employee__c();
        emp.Name = 'TestEMployyee';
        Insert emp;
        
        Employee_Allocation__c ea = new Employee_Allocation__c();
        ea.Release_Name__c = rl.Id;
        ea.Employee_Name__c = emp.Id;
        ea.Start_Date__c = system.Today();
        ea.End_Date__c = system.Today().addDays(10);
        Insert ea;
        
        Allocation_Details__c ad = new Allocation_Details__c();
        //ad.Name = 'TestWeek';
        ad.Employee_Allocation_Details__c = ea.Id;
       // ad.Name = 'TestWeek1';        
        ad.Vacation_Hours__c = 50;
        ad.Planned_Vocation_Hours__c = 40;
        ad.Allocation_Hours__c = 50;
        //ad.Release_Month__c = system.Today();
        //ad.Release_End_Month__c = system.Today().addDays(10);
        ad.Weekly_Start_Date__c = system.Today().addDays(0);

        
        Vacation__c vc = new Vacation__c();
        vc.Name = 'TestVcation';
        vc.Contact__c = emp.Id;
        Insert vc;
        
        List<Allocation_Details__c> aldllst = new List<Allocation_Details__c >{ad};
        
        apexpages.currentPage().getParameters().put('id',rl.Id);
        
        VFE_Release_Employee_Allocation_Clone.EmployAllcation eal = new VFE_Release_Employee_Allocation_Clone.EmployAllcation(ea);
        
        eal.selected = False;
        ApexPages.StandardController contrlr = new ApexPages.StandardController(rl);
        VFE_Release_Employee_Allocation_Clone vrm = new VFE_Release_Employee_Allocation_Clone(contrlr);
        vrm.selectedmonth = '- None -';
        vrm.enteredhours = 50;
        vrm.getmonths();
         
       // System.assertEquals(vrm.selectedmonth ,null);
        vrm.searchvalues();
        vrm.Applyvalues();
        vrm.Updatevalues();
        vrm.goback();
        
        
        
       // vrm.vacation = 40;
        //vrm.enteredhours =30;
        //vrm.selectedmonth = '- None -';
        
      
        }
    

}