force-app/main/default/objects/Allocation_Details__c/Allocation_Details__c.object-meta.xml
<CustomObject>
    <label>Allocation Details</label>
    <nameField>
        <displayFormat>AD-{0}</displayFormat>
        <label>Allocation Week</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocation Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Allocation_Details__c/fields/Allocation_Hours__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Hours__c</fullName>
    <label>Allocation Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Day_Year__c.field-meta.xml
<CustomField>
    <fullName>Day_Year__c</fullName>
    <formula>Year_of_Month__c &amp;&#39;-&#39;&amp; TEXT( Start_Date_of_the_Week__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Day &amp; Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Employee_Allocation_Details__c.field-meta.xml
<CustomField>
    <fullName>Employee_Allocation_Details__c</fullName>
    <label>Employee Allocation Details</label>
    <referenceTo>Employee_Allocation__c</referenceTo>
    <relationshipLabel>Allocation Details</relationshipLabel>
    <relationshipName>Allocation_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Project_Start_Month__c.field-meta.xml
<CustomField>
    <fullName>Project_Start_Month__c</fullName>
    <formula>CASE( 
MONTH( Employee_Allocation_Details__r.Release_Name__r.Proejct_Start_Date__c ), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
12, &quot;December&quot;, 
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Start Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Release_Month__c.field-meta.xml
<CustomField>
    <fullName>Release_Month__c</fullName>
    <formula>Employee_Allocation_Details__r.Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Allocation Start Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Start_Date_of_the_Week__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_of_the_Week__c</fullName>
    <formula>DAY(IF 
(MOD(Weekly_Start_Date__c - DATE(1900,1,8),7)=0, 
Weekly_Start_Date__c,/*Monday*/ 

IF 
(MOD(Weekly_Start_Date__c - DATE(1900,1,8),7)=1, 
Weekly_Start_Date__c-1,/*Tuesday*/ 

IF 
(MOD(Weekly_Start_Date__c - DATE(1900,1,8),7)=2, 
Weekly_Start_Date__c-2,/*Wednesday*/ 

IF 
(MOD(Weekly_Start_Date__c - DATE(1900,1,8),7)=3, 
Weekly_Start_Date__c-3,/*Thursday*/ 

IF 
(MOD(Weekly_Start_Date__c - DATE(1900,1,8),7)=4, 
Weekly_Start_Date__c-4,/*Friday*/ 

IF 
(MOD(Weekly_Start_Date__c - DATE(1900,1,8),7)=5, 
Weekly_Start_Date__c-5,/*Saturday*/ 

IF 
(MOD(Weekly_Start_Date__c - DATE(1900,1,8),7)=6, 
Weekly_Start_Date__c-6,/*Sunday*/ 

DATE(1878,1,1)))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date of the Week</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Vacation_Hours__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Vacation Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Year_of_Month__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Month__c</fullName>
    <formula>CASE(
MONTH(Weekly_Start_Date__c),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;,
4, &quot;April&quot;,
5, &quot;May&quot;,
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year of Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Presales</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Allocation__c/Employee_Allocation__c.object-meta.xml
<CustomObject>
    <label>Employee Allocation</label>
    <nameField>
        <displayFormat>EA-{000000}</displayFormat>
        <label>Employee Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Allocation__c/fields/Allocation_End_Date_Month__c.field-meta.xml
<CustomField>
    <fullName>Allocation_End_Date_Month__c</fullName>
    <formula>CASE( 
MONTH(End_Date__c), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
12, &quot;December&quot;, 
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Allocation End Date Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Allocation__c/fields/Allocation_Start_Date_Month__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Start_Date_Month__c</fullName>
    <formula>CASE( 
MONTH(Start_Date__c), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
12, &quot;December&quot;, 
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Allocation Start Date Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Allocation__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Allocations</relationshipLabel>
    <relationshipName>Employee_Alocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Allocation__c/fields/Release_Name__c.field-meta.xml
<CustomField>
    <fullName>Release_Name__c</fullName>
    <label>Release Name</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Employee Allocations</relationshipLabel>
    <relationshipName>Employee_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Allocation__c/fields/Week_Start_Allocation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_Start_Allocation_End_Date__c</fullName>
    <formula>IF 
(MOD(End_Date__c - DATE(1900,1,8),7)=0, 
End_Date__c,/*Monday*/ 

IF 
(MOD(End_Date__c - DATE(1900,1,8),7)=1, 
End_Date__c-1,/*Tuesday*/ 

IF 
(MOD(End_Date__c - DATE(1900,1,8),7)=2, 
End_Date__c-2,/*Wednesday*/ 

IF 
(MOD(End_Date__c - DATE(1900,1,8),7)=3, 
End_Date__c-3,/*Thursday*/ 

IF 
(MOD(End_Date__c - DATE(1900,1,8),7)=4, 
End_Date__c-4,/*Friday*/ 

IF 
(MOD(End_Date__c - DATE(1900,1,8),7)=5, 
End_Date__c-5,/*Saturday*/ 

IF 
(MOD(End_Date__c - DATE(1900,1,8),7)=6, 
End_Date__c-6,/*Sunday*/ 

DATE(1878,1,1))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Week Start Allocation End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Allocation__c/fields/Week_Start_Allocation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_Start_Allocation_Start_Date__c</fullName>
    <formula>IF 
(MOD(Start_Date__c - DATE(1900,1,8),7)=0, 
Start_Date__c,/*Monday*/ 

IF 
(MOD(Start_Date__c - DATE(1900,1,8),7)=1, 
Start_Date__c-1,/*Tuesday*/ 

IF 
(MOD(Start_Date__c - DATE(1900,1,8),7)=2, 
Start_Date__c-2,/*Wednesday*/ 

IF 
(MOD(Start_Date__c - DATE(1900,1,8),7)=3, 
Start_Date__c-3,/*Thursday*/ 

IF 
(MOD(Start_Date__c - DATE(1900,1,8),7)=4, 
Start_Date__c-4,/*Friday*/ 

IF 
(MOD(Start_Date__c - DATE(1900,1,8),7)=5, 
Start_Date__c-5,/*Saturday*/ 

IF 
(MOD(Start_Date__c - DATE(1900,1,8),7)=6, 
Start_Date__c-6,/*Sunday*/ 

DATE(1878,1,1))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Week Start Allocation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Allocation__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>YEAR(Release_Name__r.Proejct_Start_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Proejct_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Proejct_Start_Date__c</fullName>
    <label>Project Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Project_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_End_Date__c</fullName>
    <label>Project End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Project_Start_Month__c.field-meta.xml
<CustomField>
    <fullName>Project_Start_Month__c</fullName>
    <formula>CASE( 
MONTH(Proejct_Start_Date__c), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
12, &quot;December&quot;, 
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Start Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release_Planned_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Planned_End_Date__c</fullName>
    <description>Estimated date of end of release</description>
    <label>Release Planned End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Start_Date__c</fullName>
    <description>Start Date of release</description>
    <label>Planned Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Weekly_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Start_Date__c</fullName>
    <formula>CASE( 
MONTH( Proejct_Start_Date__c), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
12, &quot;December&quot;, 
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weekly_Start_Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vacation__c/Vacation__c.object-meta.xml
<CustomObject>
    <label>Out of Office</label>
    <nameField>
        <label>Out of Office Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Out of Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Vacations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacation__c/fields/Vocation_Hours__c.field-meta.xml
<CustomField>
    <fullName>Vocation_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Vocation Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vacation__c/fields/Weekly_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Start_Date__c</fullName>
    <label>Weekly Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vacation__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>YEAR( Start_Date__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year of start</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/VFC_EmployeeAllocation_Clone.cls
public with sharing class VFC_EmployeeAllocation_Clone {
    Public List<Employee_Allocation__c> empAlLst {get;set;}
    Public List<Release__c> relsLst {get;set;}
    Public List<Employee__c> empLst {get;set;}
    Public List<Allocation_Details__c> allDtlLst{get;set;}
    Public List<EmployAllcation> emplWrapLst {get;set;}
    Public List<String> WeeksLst{get;set;}
    Public List<Vacation__c> vacnewLst {get;set;}
    Public Integer count{get;set;}
    
    Map<Id,Allocation_Details__c> las = new Map<Id,Allocation_Details__c>();
    
    public string selectedmonth {get;set;}
    Public Integer enteredhours{get;set;}
    Public map<string,string> distinctLastnames {get;set;}
    Public List<Allocation_Details__c> allDtlLst1 {get;set;}
    Public String Month{get;set;}
    Public List<Id> empIds {get;set;}
    Public List<vacation__c> vacLst{get;set;}
    
    Public Integer vacation {get;set;}
    
    Public Integer weeksize{get;set;}
    
    Public Date CurrentMonhDate;
    
    
    
    public VFC_EmployeeAllocation_Clone (ApexPages.StandardController controller) {
           vacLst = new List<Vacation__c>();
           empIds  = new List<Id>();
           empAlLst = new  List<Employee_Allocation__c>();
           relsLst = new List<Release__c>();
           empLst = new List<Employee__c>();
           emplWrapLst = new List<EmployAllcation>();
           allDtlLst = new List<Allocation_Details__c>();
           count =0;
           
           //allDtlLst1 = new List<Allocation_Details__c>();
           WeeksLst = new List<String>();
           distinctLastnames = new map<string,string>();
           List<Allocation_Details__c> alcdtl = new List<Allocation_Details__c>();
           vacnewLst = new List<vacation__c>();
           //Date CurrentMonthDate = Date.Valueof(date.today().format());
           Integer dtMonth = System.Today().MOnth();
           
           String monthcur = String.Valueof(System.Today().MOnth());
           if(Integer.Valueof(monthcur) < 10)
             monthcur = monthcur +''+'0';
           String  dtYear = String.Valueof(System.Today().Year());
           Integer curMonYr = Integer.Valueof(dtYear+''+monthcur);
           System.debug('Current Month and Year is>>>>>'+curMonYr);
                    
            if(dtMonth == 1) month = 'January'; 
            if(dtMonth == 2) month = 'February';
            if(dtMonth == 3) month = 'March';
            if(dtMonth == 4) month = 'April';
            if(dtMonth == 5) month = 'May';
            if(dtMonth == 6) month = 'June';
            if(dtMonth == 7) month = 'July';
            if(dtMonth == 8) month = 'August';
            if(dtMonth == 9) month = 'September';
            if(dtMonth == 10)month = 'October';
            if(dtMonth == 11) month = 'November';
            if(dtMonth == 12) month = 'December';
            
            System.debug('Month is>>>>'+month);
           
           for(Employee_Allocation__c ea : [select Id, Name,Employee_Name__c,Employee_Name__r.Name,Employee_Name__r.Project__c,End_Date__c,Release_Name__c,Year__c,
                                               Release_Name__r.Name,Start_Date__c,Release_Name__r.Proejct_Start_Date__c,Release_Name__r.Release_Start_Date__c,Release_Name__r.Release_Planned_End_Date__c,
                                               Release_Name__r.Project_End_Date__c
                                               FROM Employee_Allocation__c
                                               WHERE Employee_Name__c =: apexpages.currentPage().getParameters().get('id')
                                               
                                               ]){
                                               
                                               System.debug('Employee inside aalocation');
                                               
                                              String StartMonth = String.Valueof(ea.Start_Date__c.Month());
                                              if(Integer.Valueof(StartMonth ) < 10)
                                                 StartMonth = StartMonth +''+'0';
                                              String StartYr = String.Valueof(ea.Start_Date__c.Year());
                                              Integer StartMonthYr = Integer.Valueof(StartYr+''+StartMonth);
                                              
                                              System.debug('Start Month Date and Year **********'+StartMonthYr);
                                              
                                              
                                              String EndMonth = String.Valueof(ea.End_Date__c.Month());
                                               if(Integer.Valueof(EndMonth) < 10)
                                                 EndMonth  = EndMonth +''+'0';
                                              String EndYr = String.Valueof(ea.End_Date__c.Year());
                                              Integer EndMonthYr = Integer.Valueof(EndYr+''+EndMonth); 
                                              
                                              System.debug('End  Month Date and Year **********'+EndMonthYr );              
                                               
                             //CurrentMonhDate = date.newInstance(dtYear,mth,day);
                         if(StartMonthYr <= curMonYr && EndMonthYr >= curMonYr){  
                                                
                             empIds.add(ea.Employee_Name__r.Id);
                           emplWrapLst.add(new EmployAllcation(ea));
                       }
           }
            emplst = [select Id,(Select Id,Name,Vocation_Hours__c,Contact__c from Vacations__r) from Employee__c WHERE ID IN:empIds];           
            for(Employee__c ep : emplst){
                for(Vacation__c vc : ep.Vacations__r){        
                         vacnewLst.add(vc);        
                }    
            }
            
            for(Vacation__c voc : vacnewLst){
                
                vacLst.add(voc);
                
            }
            //System.debug('Vacation List is');
           
           //List<Vacation__c> vacLst = [Select Id,Contact__c from Vacation__c where Contact__c IN: empIds];
           
           
           //String monthName = [select Id,Weekly_Start_Date__c from Release__c where Id=:apexpages.currentPage().getParameters().get('id')].Weekly_Start_Date__c;
           //System.debug('Cuurent month from Release is>>>>>>>'+monthName);
           
           /*for(Allocation_Details__c a:[Select Id,Name,Employee_Allocation_Details__c,Day_Year__c,Vacation_Hours__c,Project_Start_Month__c,Allocation_Hours__c,Year_of_Month__c,Release_Month__c 
                            ,Employee_Allocation_Details__r.Start_Date__c,Weekly_Start_Date__c,Employee_Allocation_Details__r.End_Date__c,
                            Employee_Allocation_Details__r.Allocation_Start_Date_Month__c,Employee_Allocation_Details__r.Allocation_End_Date_Month__c   
                            FROM Allocation_Details__c
                           WHERE Employee_Allocation_Details__r.Release_Name__c =: apexpages.currentPage().getParameters().get('id')                           
                           ORDER by Weekly_Start_Date__c ASC]){
                            las.put(a.Id,a);
            }  */
            
            alcdtl =  [Select Id,Year_of_Month__c,Day_Year__c,Allocation_Hours__c,Vacation_Hours__c,Start_Date_of_the_Week__c,Weekly_Start_Date__c,Employee_Allocation_Details__r.Release_Name__r.Name,
                                    Employee_Allocation_Details__r.Allocation_Start_Date_Month__c,Employee_Allocation_Details__r.Allocation_End_Date_Month__c,
                                    Employee_Allocation_Details__r.Start_Date__c, Employee_Allocation_Details__r.End_Date__c,
                                    Employee_Allocation_Details__r.Week_Start_Allocation_Start_Date__c,Employee_Allocation_Details__r.Week_Start_Allocation_End_Date__c,
                                    Employee_Allocation_Details__r.Name 
                                    FROM Allocation_Details__c
                           WHERE Employee_Allocation_Details__r.Employee_Name__c =: apexpages.currentPage().getParameters().get('id')                           
                           ORDER by Weekly_Start_Date__c ASC];
                           
                               
            for(Allocation_Details__c adl: alcdtl){
                
                if(adl.Year_of_Month__c== month ){
                    allDtlLst.add(adl);
                }
            }
            for(Allocation_Details__c  a: allDtlLst){
                 if(a.Employee_Allocation_Details__r.Week_Start_Allocation_Start_Date__c <= a.Weekly_Start_Date__c && a.Employee_Allocation_Details__r.Week_Start_Allocation_End_Date__c >= a.Weekly_Start_Date__c ){ 
                    las.put(a.Id,a);
                 }
            }
             for(Allocation_Details__c u: allDtlLst){
                 
                 distinctLastnames.put(u.Day_Year__c,u.Day_Year__c);                                    
             }
             for(string s:distinctLastnames.values()){
               if(s != null){
                 WeeksLst.add(s);
                 }
             }
           
           weeksize = WeeksLst.Size();
    }
    
    public List<selectOption> getmonths() {
       
        List<selectOption> options = new List<selectOption>();
        
        map<Id,string> distinctLastnames = new map<Id,String>();
        //new list for holding all of the picklist options
        options.add(new selectOption('- None -', '- None -'));
        options.add(new selectOption('January', 'January'));
        options.add(new selectOption('February', 'February'));
        options.add(new selectOption('March', 'March'));
        options.add(new selectOption('April', 'April'));
        options.add(new selectOption('May', 'May'));
        options.add(new selectOption('June', 'June'));
        options.add(new selectOption('July', 'July'));
        options.add(new selectOption('August', 'August'));
        options.add(new selectOption('September', 'September'));
        options.add(new selectOption('October', 'October'));
        options.add(new selectOption('November', 'November'));
        options.add(new selectOption('December', 'December'));
            
         
        return options; //return the picklist options
    }
    
    Public PageReference searchvalues(){
        WeeksLst = new List<String>();
        allDtlLst= new List<Allocation_Details__c>();
        distinctLastnames = new map<string,string>();
        
        emplWrapLst = new List<EmployAllcation>();
        Integer mth;
        Integer Day;
        Integer dtYear;
            if(selectedmonth == 'January'){
                 mth = 1;
                 Day = 1;
            }
            if(selectedmonth == 'February'){
                 mth = 2;
                 Day = 1;
            }
            if(selectedmonth == 'March'){
                 mth = 3;
                 Day = 1;
            }
            if(selectedmonth == 'April'){
                 mth = 4;
                 Day = 1;
            }
            if(selectedmonth == 'May'){
                 mth = 5;
                 Day = 1;
            }
            if(selectedmonth == 'June'){
                 mth = 6;
                 Day = 1;
            }
            if(selectedmonth == 'July'){
                 mth = 7;
                 Day = 1;
            }
            if(selectedmonth == 'August'){
                 mth = 8;
                 Day = 1;
            }if(selectedmonth == 'September'){
                 mth = 9;
                 Day = 1;
            }
            if(selectedmonth == 'October'){
                 mth = 10;
                 Day = 1;
            }
            if(selectedmonth == 'November'){
                 mth = 11;
                 Day = 1;
             }
            if(selectedmonth == 'December'){
                 mth = 12;
                 Day = 1;
            }
            
            
             dtYear = System.Today().Year();
             
             if(dtYear != NUll && mth != Null && day != Null)   CurrentMonhDate = date.newInstance(dtYear,mth,day);
        
        
        if(selectedmonth != '- None -'){
        System.debug('Selected Month is <<<<<<'+selectedmonth);
        
        
        System.debug('Date from Selected Month>>>>>>'+CurrentMonhDate );
        
        if(CurrentMonhDate != Null){
        
        
        for(Employee_Allocation__c ea : [select Id, Name,Employee_Name__c,Employee_Name__r.Name,Employee_Name__r.Project__c,End_Date__c,Release_Name__c,Year__c,
                                               Release_Name__r.Name,Start_Date__c,Release_Name__r.Proejct_Start_Date__c,Release_Name__r.Release_Start_Date__c,Release_Name__r.Release_Planned_End_Date__c,
                                               Release_Name__r.Project_End_Date__c,
                                               (Select Id,Name,Year_of_Month__c,Employee_Allocation_Details__r.Release_Name__c from Allocation_Details__r)
                                               FROM Employee_Allocation__c
                                               WHERE Employee_Name__c =: apexpages.currentPage().getParameters().get('id')]){
                                               
                                              String currentMonth = String.ValueOf(CurrentMonhDate.Month());
                                              if(Integer.Valueof(currentMonth) < 10)
                                                 currentMonth= currentMonth+''+'0';
                                              String CurrentYear = String.Valueof(CurrentMonhDate.Year());
                                              Integer  CurrentMonYr = Integer.Valueof(CurrentYear+''+currentMonth);
                                              
                                              System.debug('Current Month Date and Year **********'+CurrentMonYr);
                                              
                                              String StartMonth = String.Valueof(ea.Start_Date__c.Month());
                                              if(Integer.Valueof(StartMonth) < 10)
                                                 StartMonth = StartMonth +''+'0';
                                              String StartYr = String.Valueof(ea.Start_Date__c.Year());
                                              Integer StartMonthYr = Integer.Valueof(StartYr+''+StartMonth);
                                              
                                              System.debug('Start Month Date and Year **********'+StartMonthYr);
                                              
                                              
                                              String EndMonth = String.Valueof(ea.End_Date__c.Month());
                                              if(Integer.Valueof(EndMonth) < 10)
                                                 EndMonth  = EndMonth +''+'0';
                                              String EndYr = String.Valueof(ea.End_Date__c.Year());
                                              Integer EndMonthYr = Integer.Valueof(EndYr+''+EndMonth);
                                              
                                              System.debug('Start Month Date and Year **********'+EndMonthYr);
                                               
                                               System.debug('Start Date&&&&&&&&&'+ea.Start_Date__c +'End Date>>>>>>>>'+ea.End_Date__c  );
                                            if(StartMonthYr <= CurrentMonYr && EndMonthYr >= CurrentMonYr){
                                                if(ea.Allocation_Details__r.size()>0){
                                                                empIds.add(ea.Employee_Name__r.Id);
                                                                    emplWrapLst.add(new EmployAllcation(ea));
                                                                
                                                }
                                            }
                                System.debug('wrapper added employee list is>>>>'+emplWrapLst);
                               
        }
        }
        /*allDtlLst  = [Select Id,Allocation_Hours__c,Employee_Allocation_Details__c,Vacation_Hours__c,Project_Start_Month__c,Start_Date_of_the_Week__c,Weekly_Start_Date__c,Year_of_Month__c,Day_Year__c
                            ,Employee_Allocation_Details__r.Allocation_Start_Date_Month__c,Employee_Allocation_Details__r.Allocation_End_Date_Month__c   
                            FROM Allocation_Details__c where Year_of_Month__c = : selectedmonth 
                            AND  Employee_Allocation_Details__r.Release_Name__c =: apexpages.currentPage().getParameters().get('id')
                            ORDER BY Weekly_Start_Date__c ASC ];*/
                            
                   for(Allocation_Details__c a: [Select Id,Year_of_Month__c,Day_Year__c,Allocation_Hours__c,Vacation_Hours__c,Start_Date_of_the_Week__c,Weekly_Start_Date__c,Employee_Allocation_Details__r.Release_Name__r.Name,
                                                  Employee_Allocation_Details__r.Allocation_Start_Date_Month__c,Employee_Allocation_Details__r.Allocation_End_Date_Month__c, 
                                                  Employee_Allocation_Details__r.Start_Date__c, Employee_Allocation_Details__r.End_Date__c, 
                                                  Employee_Allocation_Details__r.Week_Start_Allocation_Start_Date__c,Employee_Allocation_Details__r.Week_Start_Allocation_End_Date__c, 
                                                  Employee_Allocation_Details__r.Name
                                                  FROM Allocation_Details__c
                                                where Year_of_Month__c = : selectedmonth 
                                                AND  Employee_Allocation_Details__r.Employee_Name__c =: apexpages.currentPage().getParameters().get('id')
                                                ORDER BY Weekly_Start_Date__c ASC ]){
                            
                            
                                    allDtlLst.add(a);
                            
                   }
                   System.debug('All detail list is >>>>>>'+allDtlLst);
                   System.debug('All detail list Size is as  >>>>>>'+allDtlLst.size());
                   
                   for(Allocation_Details__c  a: allDtlLst){
                         if(a.Employee_Allocation_Details__r.Week_Start_Allocation_Start_Date__c <= a.Weekly_Start_Date__c && a.Employee_Allocation_Details__r.Week_Start_Allocation_End_Date__c >= a.Weekly_Start_Date__c ){ 
                            las.put(a.Id,a);
                         }
                    }
                             
                 if(allDtlLst.Size()>0){            
                     for(Allocation_Details__c u: allDtlLst){
                        
                         distinctLastnames.put(u.Day_Year__c,u.Day_Year__c);                                    
                     }
                 }
                 for(string s:distinctLastnames.values()){
                   if(s != null){
                     WeeksLst.add(s);
                     }
                 }
                 System.debug('Allocation Details as follows>>>>>'+allDtlLst);
                 weeksize = WeeksLst.Size();
        
        }else{
        
            /* allDtlLst  = [Select Id,Year_of_Month__c,Allocation_Hours__c ,Project_Start_Month__c,Employee_Allocation_Details__r.Employee_Name__r.Project__c,Day_Year__c,Start_Date_of_the_Week__c,Weekly_Start_Date__c
                              FROM Allocation_Details__c 
                              WHERE  Employee_Allocation_Details__r.Release_Name__c =: apexpages.currentPage().getParameters().get('id') 
                              ORDER BY Weekly_Start_Date__c ASC];*/
                              
                               for(Employee_Allocation__c ea : [select Id, Name,Employee_Name__c,Employee_Name__r.Name,Employee_Name__r.Project__c,End_Date__c,Release_Name__c,Year__c,
                                               Release_Name__r.Name,Start_Date__c,Release_Name__r.Proejct_Start_Date__c,Release_Name__r.Release_Start_Date__c,Release_Name__r.Release_Planned_End_Date__c,
                                               Release_Name__r.Project_End_Date__c,
                                               (Select Id,Name,Year_of_Month__c,Employee_Allocation_Details__r.Release_Name__c from Allocation_Details__r)
                                               FROM Employee_Allocation__c
                                               WHERE Employee_Name__c =: apexpages.currentPage().getParameters().get('id')
                                               AND (Allocation_Start_Date_Month__c=: month OR Allocation_End_Date_Month__c =: month)]){
                                               if(ea.Allocation_Details__r.size()>0){
                                                                empIds.add(ea.Employee_Name__r.Id);
                                                                    emplWrapLst.add(new EmployAllcation(ea));
                                                                
                                                }
                                  }
                              System.debug('Allocation Details as No Month follows>>>>>'+allDtlLst);  
                              for(Allocation_Details__c  at : [Select Id,Year_of_Month__c,Day_Year__c,Allocation_Hours__c,Vacation_Hours__c,Start_Date_of_the_Week__c,Weekly_Start_Date__c,Employee_Allocation_Details__r.Release_Name__r.Name,
                                                                  Employee_Allocation_Details__r.Allocation_Start_Date_Month__c,Employee_Allocation_Details__r.Allocation_End_Date_Month__c, 
                                                                  Employee_Allocation_Details__r.Start_Date__c, Employee_Allocation_Details__r.End_Date__c, 
                                                                  Employee_Allocation_Details__r.Week_Start_Allocation_Start_Date__c,Employee_Allocation_Details__r.Week_Start_Allocation_End_Date__c, 
                                                                  Employee_Allocation_Details__r.Name
                                                                  FROM Allocation_Details__c
                                                                  WHERE Employee_Allocation_Details__r.Employee_Name__c =: apexpages.currentPage().getParameters().get('id') 
                                                                  ORDER BY Weekly_Start_Date__c ASC]){
                                                    
                            
                                           if(at.Year_of_Month__c== Month){
                                                    allDtlLst.add(at);
                                            }
                                    
                              } 
                              
                              for(Allocation_Details__c  a: allDtlLst){
                                     if(a.Employee_Allocation_Details__r.Week_Start_Allocation_Start_Date__c <= a.Weekly_Start_Date__c && a.Employee_Allocation_Details__r.Week_Start_Allocation_End_Date__c >= a.Weekly_Start_Date__c ){ 
                                        las.put(a.Id,a);
                                     }
                                }   
                              
                              for(Allocation_Details__c u: allDtlLst){
                                     if(u.Year_of_Month__c== Month)
                                     distinctLastnames.put(u.Day_Year__c,u.Day_Year__c);                                    
                             }
                             for(string s:distinctLastnames.values()){
                               if(s != null){
                                 WeeksLst.add(s);
                                 }
                             }  
                             weeksize = WeeksLst.Size();
          }
        
        
        return null;
    }
    
    
    Public PageReference Applyvalues(){
         List<Employee_Allocation__c> selectedEmployee = new List<Employee_Allocation__c>();
         WeeksLst = new List<String>();
         allDtlLst= new List<Allocation_Details__c>();
         distinctLastnames = new map<string,string>();
         
    
         system.debug('yourVariable -->' + enteredhours);
 
          list<string> selectedName = new list<string>();
         for(EmployAllcation aa: emplWrapLst){
             if(aa.selected == true) {
                    selectedEmployee.add(aa.eal);
                    selectedName.add(aa.eal.Name);
                }
         }
        
         
            if(selectedmonth == '- None -' && enteredhours >0 && selectedName.size()>0){
                                 for(Allocation_Details__c al: [Select Id,Year_of_Month__c,Vacation_Hours__c,Day_Year__c,Allocation_Hours__c,Project_Start_Month__c,Start_Date_of_the_Week__c,Weekly_Start_Date__c,Employee_Allocation_Details__r.Release_Name__r.Name,
                              Employee_Allocation_Details__r.Start_Date__c, Employee_Allocation_Details__r.End_Date__c,
                              Employee_Allocation_Details__r.Week_Start_Allocation_Start_Date__c,Employee_Allocation_Details__r.Week_Start_Allocation_End_Date__c,
                              Employee_Allocation_Details__r.Allocation_Start_Date_Month__c,Employee_Allocation_Details__r.Allocation_End_Date_Month__c,Employee_Allocation_Details__r.Name 
                              FROM Allocation_Details__c
                              WHERE Employee_Allocation_Details__r.Name like: selectedName
                              ORDER by Weekly_Start_Date__c ASC]){
                               if(al.Year_of_Month__c== month ){
                                       allDtlLst.add(al);
                               }
                              
                   }
                   
                   for(Allocation_Details__c  a: allDtlLst){
                         if(a.Employee_Allocation_Details__r.Week_Start_Allocation_Start_Date__c <= a.Weekly_Start_Date__c && a.Employee_Allocation_Details__r.Week_Start_Allocation_End_Date__c >= a.Weekly_Start_Date__c ){ 
                            las.put(a.Id,a);
                         }
                    }
                              
                   for(Allocation_Details__c u: allDtlLst){
                     //if(u.Year_of_Month__c== u.Project_Start_Month__c)
                        distinctLastnames.put(u.Day_Year__c,u.Day_Year__c);
                                                         
                 }
                 for(string s:distinctLastnames.values()){
                   if(s != null){
                     WeeksLst.add(s);
                     }
                 }     
                 weeksize = WeeksLst.Size();                    
                              
            } else if(selectedmonth != '- None -' && enteredhours >0 && selectedName.size()>0){
                
                allDtlLst = [Select Id,Year_of_Month__c,Day_Year__c,Allocation_Hours__c,Vacation_Hours__c,Start_Date_of_the_Week__c,Weekly_Start_Date__c,Employee_Allocation_Details__r.Release_Name__r.Name,
                              Employee_Allocation_Details__r.Allocation_Start_Date_Month__c,Employee_Allocation_Details__r.Allocation_End_Date_Month__c, 
                              Employee_Allocation_Details__r.Start_Date__c, Employee_Allocation_Details__r.End_Date__c, 
                              Employee_Allocation_Details__r.Week_Start_Allocation_Start_Date__c,Employee_Allocation_Details__r.Week_Start_Allocation_End_Date__c, 
                              Employee_Allocation_Details__r.Name
                              FROM Allocation_Details__c
                              WHERE Employee_Allocation_Details__r.Name like: selectedName
                              AND Year_of_Month__c =: selectedmonth 
                              ORDER BY Weekly_Start_Date__c ASC
                              ];
                              
                    for(Allocation_Details__c  a: allDtlLst){
                         if(a.Employee_Allocation_Details__r.Week_Start_Allocation_Start_Date__c <= a.Weekly_Start_Date__c && a.Employee_Allocation_Details__r.Week_Start_Allocation_End_Date__c >= a.Weekly_Start_Date__c ){ 
                            las.put(a.Id,a);
                         }
                    }
                 for(Allocation_Details__c u: allDtlLst){
                     distinctLastnames.put(u.Day_Year__c,u.Day_Year__c);                                    
                 }
                 for(string s:distinctLastnames.values()){
                   if(s != null){
                     WeeksLst.add(s);
                     }
                 }      
                      
                 weeksize = WeeksLst.Size();           
            } else if(selectedmonth == '- None -' && enteredhours >0 && selectedName.size()==0){
                allDtlLst = [Select Id,Year_of_Month__c,Day_Year__c,Allocation_Hours__c,Vacation_Hours__c,Start_Date_of_the_Week__c,Weekly_Start_Date__c,Employee_Allocation_Details__r.Release_Name__r.Name,
                                    Employee_Allocation_Details__r.Allocation_Start_Date_Month__c,Employee_Allocation_Details__r.Allocation_End_Date_Month__c,
                                    Employee_Allocation_Details__r.Start_Date__c, Employee_Allocation_Details__r.End_Date__c,
                                    Employee_Allocation_Details__r.Week_Start_Allocation_Start_Date__c,Employee_Allocation_Details__r.Week_Start_Allocation_End_Date__c,
                                    Employee_Allocation_Details__r.Name 
                                    FROM Allocation_Details__c
                                    WHERE Employee_Allocation_Details__r.Employee_Name__c =:ApexPages.currentPage().getParameters().get('id') 
                                    ORDER BY Weekly_Start_Date__c ASC];
                        for(Allocation_Details__c  a: allDtlLst){
                             if(a.Employee_Allocation_Details__r.Week_Start_Allocation_Start_Date__c <= a.Weekly_Start_Date__c && a.Employee_Allocation_Details__r.Week_Start_Allocation_End_Date__c >= a.Weekly_Start_Date__c ){ 
                                las.put(a.Id,a);
                             }
                        }
            }
                
        for(Allocation_Details__c a: allDtlLst){
                 
                if(a.Employee_Allocation_Details__r.Week_Start_Allocation_Start_Date__c <= a.Weekly_Start_Date__c && a.Employee_Allocation_Details__r.Week_Start_Allocation_End_Date__c >= a.Weekly_Start_Date__c ){ 
                     a.id = a.Id;
                     if((a.Vacation_Hours__c+enteredhours)>40){
                         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Total hours for a week (vacation and allocated working hours) should not exceed 40 hours. Please review and resubmit the weekly allocation hours.'));
                      
                     }else{
                             a.Allocation_Hours__c =  enteredhours;
                     }
                     las.put(a.Id,a);
                }
             //las.add(a);
         }
          
        system.debug('selectedResource' + selectedEmployee);
        system.debug('lallocsumm --> ' + selectedName);
        //List<Allocation_Details__c> lasUpd = new List<Allocation_Details__c>();
        if(las.size()>0){
           //update  las;
        }   
          
         return null;
    }
    
    public PageReference Updatevalues(){
      
      // las = new List<Allocation_Details__c>();
       emplWrapLst = new List<EmployAllcation> ();
     // allDtlLst = new List<Allocation_Details__c>();
       /* if(UpdateLstFltr.isempty())
              Update UpdateLstFltr;*/
       
        if(!las.isempty()){
            update las.Values();
          }
        
        if(!allDtlLst.isempty())
            //Update allDtlLst;
            
            System.debug('Month is as follows>>>>>'+month);

                for(Employee_Allocation__c ea : [select Id, Name,Employee_Name__c,Employee_Name__r.Name,Employee_Name__r.Project__c,End_Date__c,Release_Name__c,Year__c,
                                                       Release_Name__r.Name,Start_Date__c,Release_Name__r.Proejct_Start_Date__c,Release_Name__r.Release_Start_Date__c,Release_Name__r.Release_Planned_End_Date__c,
                                                       Release_Name__r.Project_End_Date__c
                                                       FROM Employee_Allocation__c
                                                       WHERE Employee_Name__c =: apexpages.currentPage().getParameters().get('id')
                                                       AND (Allocation_Start_Date_Month__c=: month OR Allocation_End_Date_Month__c =: month)
                                                       ]){
                                          empIds.add(ea.Employee_Name__r.Id);
                                          emplWrapLst.add(new EmployAllcation(ea));
                                       
                 }
         System.debug('emplWrapLst********'+emplWrapLst);
        
       searchvalues();
        enteredhours =0;
        return null;
    }
    public PageReference goback(){   
    
      PageReference newpage = new Pagereference('/apex/VFP_EmployeeAllocation_Clone?Id='+ApexPages.currentPage().getParameters().get('id'));
        newpage.setRedirect(true);
        return newpage;
    }
   
    Public class EmployAllcation{
    
        Public Employee_Allocation__c eal{get;set;}
        Public boolean selected{get;set;}
        
        Public EmployAllcation(Employee_Allocation__c ea){
            eal = ea;
            selected= false;
        
        }
    }

}