force-app/main/default/objects/Allocation_Details__c/Allocation_Details__c.object-meta.xml
<CustomObject>
    <label>Allocation Details</label>
    <nameField>
        <displayFormat>AD-{0}</displayFormat>
        <label>Allocation Week</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocation Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Allocation_Details__c/fields/Allocation_Hours__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Hours__c</fullName>
    <label>Allocation Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Employee_Allocation_Details__c.field-meta.xml
<CustomField>
    <fullName>Employee_Allocation_Details__c</fullName>
    <label>Employee Allocation Details</label>
    <referenceTo>Employee_Allocation__c</referenceTo>
    <relationshipLabel>Allocation Details</relationshipLabel>
    <relationshipName>Allocation_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Allocation_Details__c/fields/Vacation_Hours__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Vacation Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Allocation__c/Employee_Allocation__c.object-meta.xml
<CustomObject>
    <label>Employee Allocation</label>
    <nameField>
        <displayFormat>EA-{000000}</displayFormat>
        <label>Employee Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Allocation__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Allocations</relationshipLabel>
    <relationshipName>Employee_Alocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Allocation__c/fields/Release_Name__c.field-meta.xml
<CustomField>
    <fullName>Release_Name__c</fullName>
    <label>Release Name</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Employee Allocations</relationshipLabel>
    <relationshipName>Employee_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Weekly_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Start_Date__c</fullName>
    <formula>CASE( 
MONTH( Proejct_Start_Date__c), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
12, &quot;December&quot;, 
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weekly_Start_Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vacation__c/Vacation__c.object-meta.xml
<CustomObject>
    <label>Out of Office</label>
    <nameField>
        <label>Out of Office Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Out of Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Vacations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacation__c/fields/Weekly_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Start_Date__c</fullName>
    <label>Weekly Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/trg_Cal_Vaocation_Hours_test.cls
@isTest
private class trg_Cal_Vaocation_Hours_test {
    
    private static testMethod void trg_Cal_Vaocation_Hours_test01(){
        
        
        
        //Create a New Employee  
        
        Employee__c emp = new Employee__c (
            Name = 'xyzFirst');
        insert emp;
        
        
        //Creating Release__c record 
        Release__c release= New Release__c();
        
        
        insert release;
        
        
        
        
        //Creating Employee_Allocation__c record 
        Employee_Allocation__c eallocation= new Employee_Allocation__c();
        eallocation.Employee_Name__c=emp.id;
        eallocation.End_Date__c=Date.newInstance(2018, 11, 30);
        eallocation.Release_Name__c=release.id;	
        
        insert eallocation;
        
        
        
        
        
        //Creating Allocation_Details__c record
        
        Allocation_Details__c allocation = new Allocation_Details__c();
        allocation.Employee_Allocation_Details__c=eallocation.id;      
        allocation.Weekly_Start_Date__c=Date.newInstance(2018, 11, 6);
        
        
        insert allocation;
        
        
        
        
        
        // Inserting a New record in Vacation Object   
        
        Vacation__c vacation=new Vacation__c();
        vacation.Name ='Test';
        vacation.Contact__c=emp.id;
        vacation.Start_Date__c=Date.newInstance(2018, 11, 6);
        vacation.End_Date__c= Date.newInstance(2018, 11, 17);
        
        
        insert vacation;
        
        
    }
    
    private static testMethod void trg_Cal_Vaocation_Hours_test02(){
        
        
        
        //Create a New Employee  
        
        Employee__c emp = new Employee__c (
            Name = 'xyzFirst');
        insert emp;
        
        
        //Creating Release__c record 
        Release__c release= New Release__c();
        
        
        insert release;
        
        
        
        
        //Creating Employee_Allocation__c record 
        Employee_Allocation__c eallocation= new Employee_Allocation__c();
        eallocation.Employee_Name__c=emp.id;
        eallocation.End_Date__c=Date.newInstance(2018, 11, 30);
        eallocation.Release_Name__c=release.id;	
        
        insert eallocation;
        
        
        
        
        
        //Creating Allocation_Details__c record
        
        Allocation_Details__c allocation = new Allocation_Details__c();
        allocation.Employee_Allocation_Details__c=eallocation.id;
        allocation.Allocation_Hours__c=3.0;
        allocation.Weekly_Start_Date__c=Date.newInstance(2018, 11, 6);
        
        
        insert allocation;
		allocation.Vacation_Hours__c=1;
        Update allocation;
        
        
        
        // Inserting a New record in Vacation Object   
        
        Vacation__c vacation=new Vacation__c();
        vacation.Name ='Test';
        vacation.Contact__c=emp.id;
        vacation.Start_Date__c=Date.newInstance(2018, 11, 6);
        vacation.End_Date__c= Date.newInstance(2018, 11, 6);
        
        
        insert vacation;
        
        
    }
    
}