force-app/main/default/objects/NS_PrimaryContact__c/NS_PrimaryContact__c.object-meta.xml
<CustomObject>
    <description>It defines who the Primary Contact is for a service</description>
    <label>Primary Contact</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Primary Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Primary Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_PrimaryContact__c/fields/NS_AccountName__c.field-meta.xml
<CustomField>
    <fullName>NS_AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Account</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NS_Primary_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_PrimaryContact__c/fields/NS_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>NS_BusinessUnit__c</fullName>
    <description>Associated Business Units</description>
    <label>Associated NS Business Unit(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>OSS</fullName>
            </value>
            <value>
                <fullName>Revenue Accounting</fullName>
            </value>
            <value>
                <fullName>Revenue Waybilling</fullName>
            </value>
            <value>
                <fullName>Unit Train</fullName>
            </value>
            <value>
                <fullName>Equipment Planning</fullName>
            </value>
            <value>
                <fullName>Intermodal Non-Premium</fullName>
                <isActive>false</isActive>
                <label>Intermodal Non-Premium</label>
            </value>
            <value>
                <fullName>Intermodal Premium</fullName>
                <isActive>false</isActive>
                <label>Intermodal Premium</label>
            </value>
            <value>
                <fullName>Revenue Accounting Demurrage</fullName>
                <isActive>false</isActive>
                <label>Revenue Accounting Demurrage</label>
            </value>
            <value>
                <fullName>Revenue Accounting Traffic</fullName>
                <isActive>false</isActive>
                <label>Revenue Accounting Traffic</label>
            </value>
            <value>
                <fullName>Transportation</fullName>
                <isActive>false</isActive>
                <label>Transportation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NS_PrimaryContact__c/fields/NS_ContactName__c.field-meta.xml
<CustomField>
    <fullName>NS_ContactName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It is the  contact name for the Account</description>
    <label>Primary Role Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact must be an Active Contact.</errorMessage>
        <filterItems>
            <field>Contact.NS_ContactStatus__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Contacts</relationshipLabel>
    <relationshipName>NS_Primary_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_TriggerSettings__c/NS_TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings to enable/disable Trigger</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/NS_TriggerSettings__c/fields/NS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>NS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>To enable Contact Trigger</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NS_VDN__c/NS_VDN__c.object-meta.xml
<CustomObject>
    <description>This object is maintained to keep VDN detail and ANI Maintenence</description>
    <label>VDN</label>
    <nameField>
        <label>VDN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VDN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_VDN__c/fields/NS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>NS_IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It indicates the status of the VDN</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NS_VDN__c/fields/NS_VDNCode__c.field-meta.xml
<CustomField>
    <fullName>NS_VDNCode__c</fullName>
    <description>VDN Code</description>
    <externalId>true</externalId>
    <label>VDN Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/NS_VDN__c/fields/NS_VDNDescription__c.field-meta.xml
<CustomField>
    <fullName>NS_VDNDescription__c</fullName>
    <description>VDN Description for different VDN (ANI)</description>
    <label>VDN Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NS_IntegrationHelperTest.cls
/*
Description  : This class covers the unit testing for NS_IntegrationHelper class
Developer    : Accenture Solutions
Date         : 20-06-2018

-----------------------------------------------------------------------
Developer name        Date          Description        
-----------------------------------------------------------------------
@Bharadwaj Urma    20-06-2018     Unit testing methods
*/

@isTest
private class NS_IntegrationHelperTest {
    
    @isTest
    static void AccountWithPhoneInsertTest(){
        system.test.StartTest();
        System.Test.setMock(HttpCalloutMock.class, new NscorpWSCalloutRequestHandler_Mock());
        
        NS_VDN__c newVdnRec = new NS_VDN__c();
        newVdnRec.NS_VDNDescription__c = 'Test Description';
        newVdnRec.NS_VDNCode__c = '4504';
        Database.insert(newVdnRec);        
        Account acc = AccountTestFactory.getOnlineAccountRecord(NS_StaticVariablesUtility.Name); 
        acc.phone = '1234567890';
        acc.NS_PrimaryVDN__c = newVdnRec.Id;
        Database.insert(acc);
        system.test.StopTest();
    }
    
    @isTest
    static void AccountWithPhoneUpdateTest(){
        system.test.StartTest();
        //System.Test.setMock(HttpCalloutMock.class, new NscorpWSCalloutRequestHandler_Mock());
        NS_VDN__c newVdnRec = new NS_VDN__c();
        newVdnRec.NS_VDNDescription__c = 'Test Description';
        newVdnRec.NS_VDNCode__c = '4504';
        Database.insert(newVdnRec);
        
        Account acc = AccountTestFactory.getOnlineAccountRecord(NS_StaticVariablesUtility.Name); 
        acc.phone = '1234567890';
        acc.NS_PrimaryVDN__c = newVdnRec.Id;
        Database.insert(acc);
        
        Account accToUpdate = new Account();
        accToUpdate.Id = acc.Id ;
        accToUpdate.phone = '1234567891';
        Database.update(accToUpdate);
        
        system.test.StopTest();
    }
    
    @isTest
    static void AccountWithVDNUpdateTest(){
        system.test.StartTest();
        System.Test.setMock(HttpCalloutMock.class, new NscorpWSCalloutRequestHandler_Mock());
        NS_VDN__c newVdnRec = new NS_VDN__c();
        newVdnRec.NS_VDNDescription__c = 'Test Description';
        newVdnRec.NS_VDNCode__c = '4504';
        Database.insert(newVdnRec);
        
        NS_VDN__c newVdnRec1 = new NS_VDN__c();
        newVdnRec1.NS_VDNDescription__c = 'Test Description 1';
        newVdnRec1.NS_VDNCode__c = '4502';
        Database.insert(newVdnRec1);
        
        Account acc = AccountTestFactory.getOnlineAccountRecord(NS_StaticVariablesUtility.Name); 
        acc.phone = '1234567890';
        acc.NS_PrimaryVDN__c = newVdnRec.Id;
        Database.insert(acc);
        
        Account accToUpdate = new Account();
        accToUpdate.Id = acc.Id ;
        accToUpdate.NS_PrimaryVDN__c = newVdnRec1.Id;
        Database.update(accToUpdate);
        
        system.test.StopTest();
    }
    
    /*Test Method for ANI sync*/
    @isTest
    static void MaintainContactTest(){
        system.test.StartTest();
        System.Test.setMock(HttpCalloutMock.class, new NscorpWSCalloutRequestHandler_Mock());
        Profile agentprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,agentprof.Id);
        System.runAs( admin ){ 
            NS_TriggerSettings__c customSet = new NS_TriggerSettings__c(Name= NS_StaticVariablesUtility.conTrigger); 
            customSet.NS_IsActive__c = true;
            Database.insert(customSet,false);
        }
        Profile prof = UserTestFactory.createProfile(NS_StaticVariablesUtility.UserSupport);
        User utest = UserTestFactory.createUser(24,prof.Id); 
        utest.UserRoleId = NS_StaticVariablesUtility.userRoleSupport;
        update utest;
        system.runAs(utest){ 
            Account acc = AccountTestFactory.createOnlineAccountRecord(NS_StaticVariablesUtility.Name); 
            Contact con = ContactTestFactory.createContactRecord(acc.id,NS_StaticVariablesUtility.CONST_BLANK);
            system.debug('Con'+con);
            NS_PrimaryContact__c newPC = new NS_PrimaryContact__c();
            newPC.NS_AccountName__c = acc.Id;
            newPC.NS_ContactName__c = con.Id;
            Database.insert(newPC,false);
            
            acc = [SELECT Id,Name from Account];
            con = [SELECT Phone,NS_ContactStatus__c,NS_BusinessUnit__c FROM Contact where Id =:con.id LIMIT 1];
            con.NS_ContactStatus__c =NS_StaticVariablesUtility.conInactiveStatus;
            con.NS_BusinessUnit__c=NS_StaticVariablesUtility.Automotive;
            con.Phone='1234567890';
            Database.update(con,false);
            
        }
        System.test.StopTest();
    }
    
    @isTest
    static void updatePrimaryContactTest(){
        system.test.StartTest();
        System.Test.setMock(HttpCalloutMock.class, new NscorpWSCalloutRequestHandler_Mock());
        
        Profile agentprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.UserRep);
        User atest = UserTestFactory.createUser(13,agentprof.Id);
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,sysprof.Id);
        
        System.runAs( admin ){ 
            NS_TriggerSettings__c customSet = new NS_TriggerSettings__c(Name= NS_StaticVariablesUtility.conTrigger); 
            customSet.NS_IsActive__c = false;
            Database.insert(customSet,false);
        }
        system.runAs(atest){
            Account ACCOUNT_NOT_LOADED = AccountTestFactory.createOnlineAccountRecord(NS_StaticVariablesUtility.accName); 
            system.assertNotEquals(null, ACCOUNT_NOT_LOADED.Id);
            
            Account acc = AccountTestFactory.createOnlineAccountRecord(NS_StaticVariablesUtility.Name); 
            system.assertNotEquals(null, acc.Id);
            
            Contact con = ContactTestFactory.buildContactRecord(acc.id,NS_StaticVariablesUtility.CONST_BLANK);
            con.LastName = NS_StaticVariablesUtility.MANUAL;
            Database.insert(con,false);
            system.assertNotEquals(null, con.Id);
            
            Contact con1 = ContactTestFactory.buildContactRecord(acc.id,NS_StaticVariablesUtility.CONST_BLANK);
            con1.LastName = NS_StaticVariablesUtility.MANUAL+'2';
            con1.Email = 'user.test2'+acc.Id+'@gmail.com';
            Database.insert(con1,false);
            system.assertNotEquals(null, con1.Id);
            
            
            NS_PrimaryContact__c newPC = new NS_PrimaryContact__c();
            newPC.NS_AccountName__c = acc.Id;
            newPC.NS_ContactName__c = con.Id;
            Database.insert(newPC,false);
            system.assertNotEquals(null, newPC.Id);
            
            NS_PrimaryContact__c newPC1 = new NS_PrimaryContact__c();
            newPC1.Id = newPC.Id;
            newPC1.NS_ContactName__c = con1.Id;
            Database.update(newPC1,false);
        }
        System.test.StopTest();
    }
    
    @isTest
    static void insertPrimaryContactTest(){
        
        system.test.StartTest();
        System.Test.setMock(HttpCalloutMock.class, new NscorpWSCalloutRequestHandler_Mock());
        
        Profile agentprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.UserRep);
        User atest = UserTestFactory.createUser(13,agentprof.Id);
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,sysprof.Id);
        
        System.runAs( admin ){ 
            NS_TriggerSettings__c customSet = new NS_TriggerSettings__c(Name= NS_StaticVariablesUtility.conTrigger); 
            customSet.NS_IsActive__c = false;
            Database.insert(customSet,false);
        }
        system.runAs(atest){
            
            Account ACCOUNT_NOT_LOADED = AccountTestFactory.createOnlineAccountRecord(NS_StaticVariablesUtility.accName); 
            system.assertNotEquals(null, ACCOUNT_NOT_LOADED.Id);
            
            Account acc = AccountTestFactory.createOnlineAccountRecord(NS_StaticVariablesUtility.Name); 
            system.assertNotEquals(null, acc.Id);
            
            Contact con = ContactTestFactory.buildContactRecord(acc.id,NS_StaticVariablesUtility.CONST_BLANK);
            con.LastName = NS_StaticVariablesUtility.MANUAL;
            Database.insert(con,false);
            
            NS_PrimaryContact__c newPC = new NS_PrimaryContact__c();
            newPC.NS_AccountName__c = acc.Id;
            newPC.NS_ContactName__c = con.Id;
            Database.insert(newPC,false);
        }
        System.test.StopTest();
    }
    
    @isTest
    static void insertVDNTest(){
        system.test.StartTest();
        System.Test.setMock(HttpCalloutMock.class, new NscorpWSCalloutRequestHandler_Mock());
        NS_VDN__c newVdnRec = new NS_VDN__c();
        newVdnRec.NS_VDNDescription__c = 'Test Description';
        newVdnRec.NS_VDNCode__c = '4504';
        Database.insert(newVdnRec);
        system.test.StopTest();
    }
    
    @isTest
    static void updateVDNTest(){
        system.test.StartTest();
        System.Test.setMock(HttpCalloutMock.class, new NscorpWSCalloutRequestHandler_Mock());
        NS_VDN__c newVdnRec = new NS_VDN__c();
        newVdnRec.NS_VDNDescription__c = 'Test Description';
        newVdnRec.NS_VDNCode__c = '4504';
        insert newVdnRec;
        
        NS_VDN__c updateVdnRec = new NS_VDN__c();
        updateVdnRec.NS_VDNDescription__c = 'Test Description';
        updateVdnRec.NS_VDNCode__c = '4505';
        updateVdnRec.Id = newVdnRec.Id;
        Database.update(updateVdnRec);          
        system.test.StopTest();
    }
/* ================================================
* @Method Name : contactDeleteTest
* @author id: sudipta.b.mukherjee@accenture.com
* @Purpose: This method is used to unit test deleteContactonTyes() in NS_Integration Helper
* @Parameters: String Account Name
* @return: Account
* @Release: Phase-1 Enhancement Request
* @created date: 20-01-2019
==================================================*/ 
    @isTest
    static void contactDeleteTest(){
        system.test.StartTest();
        try{  
            Profile agentprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
            User admin = UserTestFactory.createUser(14,agentprof.Id);
            System.runAs( admin ){ 
                Account acc = AccountTestFactory.createOnlineServiceAccountRecord(NS_StaticVariablesUtility.Name);  
                Contact con = ContactTestFactory.buildContactRecord(acc.id,NS_StaticVariablesUtility.CONST_BLANK); 
                insert con;
                
                delete con;
                Contact deletedContact = [SELECT Id, IsDeleted FROM Contact WHERE Id = :con.Id ALL ROWS];
                system.assertEquals(deletedContact.IsDeleted, true);           
            }
        }
        catch(Exception e)
        {
            NS_StaticVariablesUtility.createExceptionRecord(e, 'NS_IntegrationHelperTest', 'ContactDelete');
        }
        system.test.StopTest();
    }
   
/* ================================================
* @Method Name : invoke_ContactUpdatePositiveTest
* @author id: arjun.c.ghosh@accenture.com
* @Purpose: This method is used to unit test invoke_ContactUpdate() in NS_Integration Helper
* @Parameters: String Account Name
* @return: Account
* @Release: Phase-1 Enhancement Request
* @created date: 20-01-2019
==================================================*/ 
    @isTest
    static void invoke_ContactUpdatePositiveTest(){
        try{
            system.test.StartTest();
            NS_TriggerSettings__c customSet1 = new NS_TriggerSettings__c();
            customSet1.Name=NS_StaticVariablesUtility.assocTrigger;
            customSet1.NS_IsActive__c=true;
            Database.insert(customSet1,false);
            Profile agentprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
            User admin = UserTestFactory.createUser(14,agentprof.Id);
            System.runAs( admin ){ 
                Account acc = AccountTestFactory.createOnlineServiceAccountRecord(NS_StaticVariablesUtility.Name);  
                Contact con = ContactTestFactory.buildContactRecord(acc.id,NS_StaticVariablesUtility.CONST_BLANK);  
                Database.insert (con);
                NS_PrimaryContact__c newPC = new NS_PrimaryContact__c();
            	newPC.NS_AccountName__c = acc.Id;
            	newPC.NS_ContactName__c = con.Id;
           		Database.insert(newPC,false);
                Account acc2 = AccountTestFactory.createOnlineServiceAccountRecord(NS_StaticVariablesUtility.SystemAdministratorProfile);  
                con.AccountId=acc2.Id;
                Database.update(con) ; 
                system.test.StopTest();
            }
        }catch(Exception exp){
            NS_StaticVariablesUtility.createExceptionRecord(exp, 'NS_IntegrationHelperTest', 'invoke_ContactUpdateTest');
        }
    }
    
/* ================================================
* @Method Name : invoke_ContactUpdateNegativeTest
* @author id: arjun.c.ghosh@accenture.com
* @Purpose: This method is used to unit test invoke_ContactUpdate() in NS_Integration Helper
* @Parameters: String Account Name
* @return: Account
* @Release: Phase-1 Enhancement Request
* @created date: 20-01-2019
==================================================*/ 
    @isTest
    static void invoke_ContactUpdateNegativeTest(){
        try{
            system.test.StartTest();
            NS_TriggerSettings__c customSet1 = new NS_TriggerSettings__c();
            customSet1.Name=NS_StaticVariablesUtility.assocTrigger;
            customSet1.NS_IsActive__c=true;
            Database.insert(customSet1,false);
            Profile agentprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
            User admin = UserTestFactory.createUser(14,agentprof.Id);
            System.runAs( admin ){ 
                Account acc = AccountTestFactory.createOnlineServiceAccountRecord(NS_StaticVariablesUtility.Name);  
                Contact con = ContactTestFactory.buildContactRecord(acc.id,NS_StaticVariablesUtility.CONST_BLANK);  
                Database.insert (con);
                NS_PrimaryContact__c newPC = new NS_PrimaryContact__c();
            	newPC.NS_AccountName__c = acc.Id;
            	newPC.NS_ContactName__c = con.Id;
           		Database.insert(newPC,false);                     
                con.Phone='9766857889';                
                Database.update(con) ; 
                system.test.StopTest();
            }
        }catch(Exception exp){
            NS_StaticVariablesUtility.createExceptionRecord(exp, 'NS_IntegrationHelperTest', 'invoke_ContactUpdateTest');
        }
    } 
    
}