force-app/main/default/objects/Business_Objectives__c/Business_Objectives__c.object-meta.xml
<CustomObject>
    <label>Business Objectives</label>
    <nameField>
        <label>Objectives name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Objectives__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Business Objectives</relationshipLabel>
    <relationshipName>Business_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KPIs__c/KPIs__c.object-meta.xml
<CustomObject>
    <label>KPIs</label>
    <nameField>
        <label>KPIs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPIs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KPIs__c/fields/Tactics__c.field-meta.xml
<CustomField>
    <fullName>Tactics__c</fullName>
    <label>Tactics</label>
    <referenceTo>Tactics__c</referenceTo>
    <relationshipLabel>KPIs</relationshipLabel>
    <relationshipName>KPIs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tactics__c/Tactics__c.object-meta.xml
<CustomObject>
    <label>Tactics</label>
    <nameField>
        <label>Tactics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tactics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tactics__c/fields/Value_Drivers__c.field-meta.xml
<CustomField>
    <fullName>Value_Drivers__c</fullName>
    <label>Value Drivers</label>
    <referenceTo>Value_Drivers__c</referenceTo>
    <relationshipLabel>Tactics</relationshipLabel>
    <relationshipName>Tactics1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Drivers__c/Value_Drivers__c.object-meta.xml
<CustomObject>
    <label>Value Drivers</label>
    <nameField>
        <label>Value Drivers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Drivers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Drivers__c/fields/Business_Objectives__c.field-meta.xml
<CustomField>
    <fullName>Business_Objectives__c</fullName>
    <label>Business Objectives</label>
    <referenceTo>Business_Objectives__c</referenceTo>
    <relationshipLabel>Value Drivers</relationshipLabel>
    <relationshipName>Value_Drivers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VFC_OrgChartMaster_Clone_Test.cls
@isTest
Public class VFC_OrgChartMaster_Clone_Test{
    Public static testMethod void VFC_OrgChartMaster_Clone_Test(){
        
        Release__c rl = new Release__c();
        rl.Name = Testing_Utility_Constants.ReleaseName;        
        Database.Insert(rl,false);
        
        Business_Objectives__c bo = new Business_Objectives__c();
        bo.Name = Testing_Utility_Constants.BusinessObjectiveName;
        bo.Release__c = rl.Id;        
        Database.Insert(bo,false);        
        
        Value_Drivers__c vd = new Value_Drivers__c();
        vd.Name = Testing_Utility_Constants.ValueDriverName;
        vd.Business_Objectives__c = bo.Id;
        Database.Insert(vd,false);
        
        
        Tactics__c tc = new Tactics__c();
        tc.Name = Testing_Utility_Constants.TacticsName;
        tc.Value_Drivers__c = vd.Id;
        Database.Insert(tc,false);
        
        
        KPIs__c kp = new KPIs__c();
        kp.Name = Testing_Utility_Constants.KPISName;
        kp.Tactics__c = tc.Id;
        Database.Insert(kp,false);
       
        
        ApexPages.StandardController cntrlr = new ApexPages.StandardController(rl);
        apexpages.currentPage().getParameters().put('id',rl.Id);
        
        VFC_OrgChartMaster_Clone  vorcl = new VFC_OrgChartMaster_Clone(cntrlr);
        
        VFC_OrgChartMaster_Clone.releaseClass orgrel = new VFC_OrgChartMaster_Clone.releaseClass();
        VFC_OrgChartMaster_Clone.BusinessObjClass orgbs= new VFC_OrgChartMaster_Clone.BusinessObjClass();
        VFC_OrgChartMaster_Clone.ValueDriversClass orgvd = new VFC_OrgChartMaster_Clone.ValueDriversClass();
        VFC_OrgChartMaster_Clone.TacticsClass orgTc = new VFC_OrgChartMaster_Clone.TacticsClass();
        VFC_OrgChartMaster_Clone.KPISClass orgKPI = new VFC_OrgChartMaster_Clone.KPISClass();
        
        
    
    }

}