force-app/main/default/objects/Issues_Risks__c/Issues_Risks__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents an issue or risk with some parts of the project plan.</description>
    <label>Issue/Risk</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Risk/Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues/Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issues_Risks__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Detailed description of the issue/risk.</description>
    <inlineHelpText>Detailed description of the issue/risk.</inlineHelpText>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/fields/Logged_Date__c.field-meta.xml
<CustomField>
    <fullName>Logged_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>issue/risk logged date</description>
    <label>Logged Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Level of severity</description>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Issues and Risks for this release.</description>
    <inlineHelpText>Issues and Risks for this release.</inlineHelpText>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Issues/Risks</relationshipLabel>
    <relationshipName>Issues_Risks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Risk is resolved or still open for action</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/fields/Target_Resolution_Date__c.field-meta.xml
<CustomField>
    <fullName>Target_Resolution_Date__c</fullName>
    <description>Planned date to resolve issue/risk</description>
    <label>Target Resolution Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/recordTypes/Issue.recordType-meta.xml
<RecordType>
    <fullName>Issue</fullName>
    <active>true</active>
    <description>Create/Update any issues with the project.</description>
    <label>Issue</label>
</RecordType>

force-app/main/default/objects/Issues_Risks__c/recordTypes/Risk.recordType-meta.xml
<RecordType>
    <fullName>Risk</fullName>
    <active>true</active>
    <description>Create/Update any risks with the project.</description>
    <label>Risk</label>
</RecordType>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about Release</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SaaSCreateIssueRiskCtrl.cls
/** 
 *  Author : Accenture 
 *  Description : Controller class for SaaSReleaseListView  
 *  Created Date : 05\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  05\06\2015        created 
 *
 */
public class SaaSCreateIssueRiskCtrl 
{
    public Issues_Risks__c issueRiskObj {get;set;}
    public Date loggedDate {get;set;}
    public Date targetResolutionDate {get;set;}
    public string release {get;set;}  
    public Boolean isSaved {get;set;} 
    public String issueRiskType {get;set;}  
    public Boolean disableRecType {get;set;}  
    public Boolean isDetail {get;set;}
    /**
     * Construtor 
     * @param ApexPages.StandardController controller
     *
     */
    public SaaSCreateIssueRiskCtrl (ApexPages.StandardController controller) 
    {    
        isSaved  = false;
        Issues_Risks__c tempIssueRiskObj = null;
        List<Issues_Risks__c>  issueRiskLst = null;
        Boolean isClone =false;
        issueRiskType  = SaaSTextConstant.EMPTY_STRING;
        tempIssueRiskObj = (Issues_Risks__c)controller.getRecord();
        release =  SaaSUtility.getURLParameter(SaaSTextConstant.RELEASEID_URL_PARAM );
        isDetail = SaaSUtility.getURLParameter(SaaSTextConstant.DETAIL_URL_PARAM ) == SaaSTextConstant.NUMERIC_ONE  ?true:false;
        isClone =   SaaSUtility.getURLParameter(SaaSTextConstant.IS_CLONE_URL_PARAM) == SaaSTextConstant.NUMERIC_ONE  ? true :false;  
        disableRecType = isClone? true:false;
        disableRecType = isDetail ? true:false;
 //       issueRiskType  =  (tempIssueRiskObj.id != null)?tempIssueRiskObj.RecordType.developerName:SaaSTextConstant.EMPTY_STRING;      

          // Check if this is edit mode
        if(tempIssueRiskObj.id != null )
        {
            issueRiskLst  = Database.query(SaaSUtility.getCreatableFieldsSOQL(SaaSTextConstant.ISSUE_RISK_OBJ_API_NAME, 'id=\''+tempIssueRiskObj.id+'\''));
            if(issueRiskLst.size() > 0)
            {
                issueRiskObj= issueRiskLst.get(0); 
                issueRiskType  =  SaaSUtility.getRecordTypeDeveloperName(issueRiskLst.get(0).recordTypeID);
                targetResolutionDate = issueRiskObj.Target_Resolution_Date__c;
                loggedDate = issueRiskObj.Logged_Date__c;  
            }
        }  
        else 
        {
            issueRiskObj= new Issues_Risks__c();
        }        
        if(isClone)
        {
            issueRiskObj= issueRiskObj.clone();
            issueRiskObj.ownerID = Userinfo.getUserID();
        }     
        if(release !=null && release.trim() != SaaSTextConstant.EMPTY_STRING )
        {
            issueRiskObj.Release__c = release ;
        }
    }
      
   /**
    * Save the IssueRisk record
    * @return 
    *
    */   
    public PageReference saveIssueRisk() 
    {                
        PageReference pageRef= null; 
        String errMsg = null;       
        try
        {
            
            issueRiskObj.Target_Resolution_Date__c = targetResolutionDate;
            issueRiskObj.Logged_Date__c = loggedDate; 
            List<RecordType> recLst = [Select id from RecordType where  SobjectType = :SaaSTextConstant.ISSUE_RISK_OBJ_API_NAME and developerName = :issueRiskType ];        
            if(recLst.size() > 0)
            {
                issueRiskObj.recordTypeID  = recLst.get(0).id;
            }
            errMsg  =validateKeyDecision(); 
            if(errMsg  != null)
            {
                SaaSUtility.displayErrMsg(errMsg   );  
                System.debug('errMsg---'+ errMsg  );   
                return null;
            }
            upsert issueRiskObj; 
            SaaSUtility.displaySuccessMsg(SaaSTextConstant.ISSUE_RISK_SAVE_MSG);
            isSaved  = true; 
        }
        catch(DmlException e)
        {
            SaaSUtility.displayErrMsg(e.getDmlMessage(0) );           
        } 
        catch(Exception e)
        {
             SaaSUtility.displayErrMsg(SaaSTextConstant.EXCEPTION_ERR_MSG );          
        }
        return pageRef;
    }    
    
   /**
    *  Get all record type of the Issue and risk object
    * @return List<SelectOption>
    *
    */         
    public List<SelectOption> getRecordType() 
    {
        List<SelectOption> recType = new List<SelectOption>();
         recType.add(new SelectOption(SaaSTextConstant.EMPTY_STRING ,SaaSTextConstant.NONE_PICKLIST_VALUE ));
        List<RecordType> rcordType1 = [Select id ,Name,DeveloperName from RecordType where SobjectType = :SaaSTextConstant.ISSUE_RISK_OBJ_API_NAME];
        for(RecordType obj : rcordType1 )
        {
              recType.add(new SelectOption(obj.DeveloperName,Obj.name));
        }
        return recType;
    }
    
   /**
    * Disable Record Type picklsit once picklis is modified 
    * @return none
    *
    */  
    public void disbaleRecordType()
    {
       if(issueRiskType  != SaaSTextConstant.EMPTY_STRING)
       {
            disableRecType = true;
       }            
    }
     
   /**
    * Validate the data entered by the user.
    * @return String errmsg
    *
    */       
    @TestVisible private String validateKeyDecision()
    {
        String errMsg = null; 
        
        if(issueRiskObj.Status__c== Null || issueRiskObj.Status__c==SaaSTextConstant.EMPTY_STRING)
        {
            errMsg = SaaSTextConstant.ISSUE_STATUS_EMPTY_ERR_MSG; 
        }                             
        else if(issueRiskObj.Priority__c== Null || issueRiskObj.Priority__c==SaaSTextConstant.EMPTY_STRING)
         {
             errMsg = SaaSTextConstant.ISSUE_PRIORITY_EMPTY_ERR_MSG ;
         }
            
         else if(issueRiskObj.Description__c== Null || issueRiskObj.Description__c==SaaSTextConstant.EMPTY_STRING)
         {
             errMsg = SaaSTextConstant.ISSUE_DESC_EMPTY_ERR_MSG; 
         }
         else if(issueRiskObj.Target_Resolution_Date__c == Null)
        {
             errMsg = SaaSTextConstant.ISSUE_TARGET_RESOLUTION_DATE_ERR_MSG;      
        }
        else if(issueRiskType == Null || issueRiskType ==SaaSTextConstant.EMPTY_STRING)
        {
             errMsg =SaaSTextConstant.SELECT_REQUEST_TYPE_ERR_MSG;
        }  
        return errMsg; 
    }    
    
     /**
    * Create new issue OR Risk 
    * 
    *    
    */    
    public void createIssueOrRisk()
    {
        isDetail = false;
        issueRiskObj  = new   Issues_Risks__c ();
        loggedDate  = null;    
        targetResolutionDate  = null;
        issueRiskType  = SaaSTextConstant.EMPTY_STRING;  
        disableRecType  = false;                  
    }
}