force-app/main/default/objects/Issues_Risks__c/Issues_Risks__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents an issue or risk with some parts of the project plan.</description>
    <label>Issue/Risk</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Risk/Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues/Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issues_Risks__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Detailed description of the issue/risk.</description>
    <inlineHelpText>Detailed description of the issue/risk.</inlineHelpText>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Milestone related to this Issue/Risk.</description>
    <inlineHelpText>Milestone related to this Issue/Risk.</inlineHelpText>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Issues/Risks</relationshipLabel>
    <relationshipName>Issues_Risks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Level of severity</description>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Issues and Risks for this release.</description>
    <inlineHelpText>Issues and Risks for this release.</inlineHelpText>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Issues/Risks</relationshipLabel>
    <relationshipName>Issues_Risks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Risk is resolved or still open for action</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/fields/Target_Resolution_Date__c.field-meta.xml
<CustomField>
    <fullName>Target_Resolution_Date__c</fullName>
    <description>Planned date to resolve issue/risk</description>
    <label>Target Resolution Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a significant event in the project&#39;s lifespan.</description>
    <label>Milestone</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Milestone ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Release related to this milestone.</description>
    <inlineHelpText>Release related to this milestone.</inlineHelpText>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about Release</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SaaSIssuesListViewCtrl.cls
/** 
 *  Author : Accenture 
 *  Description : Controller class for SaaSReleaseListView  
 *  Created Date : 05\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  05\06\2015        created 
 *
 */
 
public class SaaSIssuesListViewCtrl
{
    private List<IssueRiskWrapper> issueRiskWrapLst;
    
    public String searchtxt {get;set;}  
      
    public SaaSIssuesListViewCtrl()
    {
        searchtxt = '';
    }    
    
    public ApexPages.StandardSetController con 
    {
        get 
        {
            if(con == null) 
            {
               // con = new ApexPages.StandardSetController(Database.getQueryLocator([Select Release__r.name ,Milestone__r.name ,Priority__c, Status__c, Description__c,Target_Resolution_Date__c,Id,recordType.Name, Name FROM Issues_Risks__c Order By CreatedDate DESC]));            
                con = new ApexPages.StandardSetController(Database.query(getSoql()));
                con.setPageSize(SaaSTextConstant.LIST_VIEW_PAGE_SIZE);
            }
            return con;
        }
        set;
    }
    /**
     * Get Records form the Standardset controller 
     *
     * @param args none.
     * @return none 
     *
     */ 
    public List<IssueRiskWrapper> getIssueRiskWrapLst() 
    {
        issueRiskWrapLst = new List<IssueRiskWrapper>();
        for (Issues_Risks__c   issueObj : (List<Issues_Risks__c  >)con.getRecords())
            issueRiskWrapLst.add(new IssueRiskWrapper(issueObj));

        return issueRiskWrapLst;
    }
        
    /**
     * indicates whether there are more records after the current page set.
     *
     * @param args none.
     * @return none 
     *
     */      
     public Boolean hasNext {
        get {
            return con.getHasNext();
        }
        set;
    }

    /**
     * indicates whether there are more records before the current page set.
     *
     * @param args none.
     * @return none 
     *
     */      
     public Boolean hasPrevious {
        get {
            return con.getHasPrevious();
        }
        set;
    }

     /**
     *  returns the first page of records
     *
     * @param args none.
     * @return none 
     *
     */    
     public void first() {
         con.first();
     }

    /**
     *  returns the last page of records
     *
     * @param args none.
     * @return none 
     *
     */       
     public void last() {
         con.last();
     }

    /**
     *  returns the previous page of records
     *
     * @param args none.
     * @return none 
     *
     */       
     public void previous() {
         con.previous();
     }

    /**
     *  returns the next page of records
     *
     * @param args none.
     * @return none 
     *
     */       
      public void next() {
         con.next();
     }

    /**
     *  IssueRisk Wrapper Class 
     *
     */   
    public class IssueRiskWrapper 
    {
        public Boolean checked{ get; set;}
        public Issues_Risks__c  issueRiskObj{ get; set;}  
        
        public IssueRiskWrapper (Issues_Risks__c  c)
        {
            issueRiskObj = c;
            checked = false;
        }      
    }
      /**
     * Search for relase records for given Srtring 
     *
     * @param args none.
     * @return PageReference 
     *
     */   
    public void search()
    {           
        // con = new ApexPages.StandardSetController(Database.getQueryLocator([Select Release__r.name ,Milestone__r.name ,Priority__c, Status__c, Description__c,Target_Resolution_Date__c,Id,recordType.Name, Name FROM Issues_Risks__c where name like : ('%'+searchtxt+'%' )   Order By Name limit 100]));            
        // con.setPageSize(5);   
         if(searchtxt!= null)
        {
            searchtxt =searchtxt.trim();
        }
        con = new ApexPages.StandardSetController(Database.query(getSoql()));
        con.setPageSize(SaaSTextConstant.LIST_VIEW_PAGE_SIZE);

    }    
     /**
     * Delete Selected Record
     *
     * @param args none.
     * @return none
     *
     */    
    public void deleteIssues()
    {
        List<Issues_Risks__c> delIssues = getSelectedElement();
        if(delIssues.size () > 0)
        {
            Database.delete(delIssues);
            con = null;
            SaaSUtility.displaySuccessMsg(SaaSTextConstant.DELETE_SELECT_ONE_RECORD_SAVE_MSG );
        }
        else 
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.DELETE_SELECT_ONE_RECORD_ERR_MSG );      
        }            
    
    }
    /**
     * Navigate to Update page 
     *
     * @param args none.
     * @return PageReference 
     *
     */      
    public PageReference updateIssue()
    {

        List<Issues_Risks__c> updateIssue = getSelectedElement();
        if(updateIssue.size() > 1)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.EDIT_MULTIPLE_SELECT_ERR_MSG );                   
            return null;
        }
        
        if(updateIssue.size() == 0)
        {
           SaaSUtility.displayErrMsg(SaaSTextConstant.EDIT_SELECT_ONE_RECORD_ERR_MSG );           
            return null;            
        }          
        return  new  PageReference(SaaSTextConstant.CREATE_RISK_ISSUE_VF_PAGE_NAME_URL+'?id='+updateIssue.get(0).id);                 
    }
     /**
     * Navigate to Selected Record to Clone
     *
     * @param args none.
     * @return List<Release__c> 
     *
     */ 
    public PageReference cloneIssue()
    {

        List<Issues_Risks__c> cloneIssue = getSelectedElement();
        if(cloneIssue.size() > 1)
        {
           SaaSUtility.displayErrMsg(SaaSTextConstant.CLONE_SELECT_ONE_RECORD_ERR_MSG );               
            return null;
        }
        
        if(cloneIssue.size() == 0)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.CLONE_MULTIPLE_SELECT_ERR_MSG );                     
            return null;            
        }          
        return new PageReference(SaaSTextConstant.CREATE_RISK_ISSUE_VF_PAGE_NAME_URL+ '?isClone=1&&id='+cloneIssue.get(0).id);                 
    }
   /**
    * Get Selected Element from the List
    *
    * @param args none.
    * @return List<Release__c> 
    *
    */    
    public List<Issues_Risks__c> getSelectedElement()
    {
        List<Issues_Risks__c> slectedIssues = new List<Issues_Risks__c>();    
        if(issueRiskWrapLst!= null)
        {
            for(IssueRiskWrapper wrapObj : issueRiskWrapLst)
            {
                if(wrapObj.checked)
                {
                    slectedIssues.add(wrapObj.issueRiskObj);    
                }
            }
        }
        return slectedIssues;
    }
     /**
    * To set a Direction either in ascending order or descending order.
    *
    */       
    public String sortDir 
    {   
       get  { if (sortDir == null) {  sortDir = SaaSTextConstant.ASCENDING_SORT_ORDER ; } return sortDir;}
       set;
    }

   /**
    * The current field to sort by. defaults to last name
    *
    */  
    public String sortField 
    {

        get  { if (sortField == null) {sortField = SaaSTextConstant.NAME_FIELD_API_NAME ; } return sortField;  }
        set;
    }
    
   /**
    * Sort List View By Column
    *
    */  
    public void sortByColumn()
    {
         sortDir = sortDir.equals(SaaSTextConstant.ASCENDING_SORT_ORDER ) ? SaaSTextConstant.DESCENDING_SORT_ORDER  :  SaaSTextConstant.ASCENDING_SORT_ORDER ;
         search();
         
    }
    
   /**
    * Get Soql For the List View
    *
    */          
    private String getSoql()
    {
        String soql = 'Select Release__r.name ,Milestone__r.name ,Priority__c, Status__c, Description__c,Target_Resolution_Date__c,Id,recordType.Name, Name FROM Issues_Risks__c where ';
               soql = soql +  'name like  \'%'+searchtxt+'%\'  or ';
               soql = soql +  'Release__r.name like  \'%'+searchtxt+'%\'  or ';
               soql = soql +  'Milestone__r.name like  \'%'+searchtxt+'%\'  or ';
               soql = soql +  'recordType.Name like  \'%'+searchtxt+'%\'  or ';
               soql = soql +  'Priority__c like  \'%'+searchtxt+'%\'  or ';
               soql = soql +  'Status__c like \'%'+searchtxt+'%\'  Order By ' + sortField + ' ' + sortDir + ' NULLS LAST' ; 
               
        System.debug('soql-----' + soql );               
        
        return soql;              
    } 

    
}