force-app/main/default/objects/Issues_Risks__c/Issues_Risks__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents an issue or risk with some parts of the project plan.</description>
    <label>Issue/Risk</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Risk/Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues/Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issues_Risks__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Detailed description of the issue/risk.</description>
    <inlineHelpText>Detailed description of the issue/risk.</inlineHelpText>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Level of severity</description>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Issues and Risks for this release.</description>
    <inlineHelpText>Issues and Risks for this release.</inlineHelpText>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Issues/Risks</relationshipLabel>
    <relationshipName>Issues_Risks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shows Issue/Risk&#39;s related request</description>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Issues/Risks</relationshipLabel>
    <relationshipName>Issues_Risks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Risk is resolved or still open for action</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/fields/Target_Resolution_Date__c.field-meta.xml
<CustomField>
    <fullName>Target_Resolution_Date__c</fullName>
    <description>Planned date to resolve issue/risk</description>
    <label>Target Resolution Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Issues_Risks__c/recordTypes/Issue.recordType-meta.xml
<RecordType>
    <fullName>Issue</fullName>
    <active>true</active>
    <description>Create/Update any issues with the project.</description>
    <label>Issue</label>
</RecordType>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about Release</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Plan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Start_Date__c</fullName>
    <description>Estimated date of Start</description>
    <label>Plan Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release_Planned_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Planned_End_Date__c</fullName>
    <description>Estimated date of end of release</description>
    <label>Release Planned End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status_Update__c.field-meta.xml
<CustomField>
    <fullName>Status_Update__c</fullName>
    <description>Release status update</description>
    <inlineHelpText>Release status update</inlineHelpText>
    <label>Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>High 
Medium 
Low</description>
    <inlineHelpText>High 
Medium 
Low</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Release in which the request will go</description>
    <inlineHelpText>The release in which the request will actually be deployed. If the requirement has not been approved for a release, there should not be a value in this field.</inlineHelpText>
    <label>Committed Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Requests (Committed Release)</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Description__c.field-meta.xml
<CustomField>
    <fullName>Request_Description__c</fullName>
    <description>Gathers further details for requirements.</description>
    <inlineHelpText>Detailed Summary* 
Screen(s) Impacted* 
Field Name(s) &amp; Type(s)* 
Picklist Values 
Calculation 
Dependency 
Workflow/Approval Rules 
Interfacing System Updates 
Interface Frequency 
Data Volumes 
*Indicates information required for all requests!</inlineHelpText>
    <label>Initial Request</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Title__c.field-meta.xml
<CustomField>
    <fullName>Request_Title__c</fullName>
    <description>Captures the requirement title</description>
    <inlineHelpText>Captures the requirement title</inlineHelpText>
    <label>Request Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>Type of the request</description>
    <inlineHelpText>If you are unsure of the type of request you are submitting, please select Unknown.</inlineHelpText>
    <label>Request Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Configuration</fullName>
            </value>
            <value>
                <fullName>Custom Code</fullName>
            </value>
            <value>
                <fullName>Data Access</fullName>
            </value>
            <value>
                <fullName>Data Migration</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>User Administration</fullName>
            </value>
            <value>
                <fullName>User Story</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the request</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Identify: New Requirement</fullName>
                <default>true</default>
                <label>Identify: New Requirement</label>
            </value>
            <value>
                <fullName>Identify: Submit for Business Review</fullName>
            </value>
            <value>
                <fullName>Identify: Deferred</fullName>
            </value>
            <value>
                <fullName>Consolidate: Approve to Estimate</fullName>
            </value>
            <value>
                <fullName>Consolidate: Level of Effort Complete</fullName>
            </value>
            <value>
                <fullName>Approve: Approved to Deploy</fullName>
            </value>
            <value>
                <fullName>Release: Design</fullName>
            </value>
            <value>
                <fullName>Release: Build</fullName>
            </value>
            <value>
                <fullName>Release: Test</fullName>
            </value>
            <value>
                <fullName>Release: SIT</fullName>
            </value>
            <value>
                <fullName>Release: UAT</fullName>
            </value>
            <value>
                <fullName>Release: Build Production</fullName>
            </value>
            <value>
                <fullName>Release: Test Production</fullName>
            </value>
            <value>
                <fullName>Close: Deployed</fullName>
            </value>
            <value>
                <fullName>Close: Rejected</fullName>
            </value>
            <value>
                <fullName>Close: Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SaaSCreateIssueRiskCtrlTest.cls
/** 
 *  Author : Accenture 
 *  Description : Test Class for Controller class for SaaSCreateIssueRiskCtrl
 *  Created Date : 05\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  09\06\2015        created 
 *
 */
@isTest 
public class SaaSCreateIssueRiskCtrlTest
{
    static testMethod void validateInsertIssueRisk() 
    {
        Release__c rel = new Release__c();
         rel.Name = 'Test Release ';
         rel.Release__c = 24;
         rel.Plan_Start_Date__c = System.today();
         rel.Release_Planned_End_Date__c= System.today() + 10;
         rel.Status__c = 'Red';
         rel.Description__c = 'Test description ';
         rel.Status_Update__c = 'Test Comments';
         insert rel;
         
         Issues_Risks__c issue = new Issues_Risks__c();
         issue.Priority__c = 'High';
         issue.Status__c ='Open';
         issue.Description__c ='Test Description';
         issue.Target_Resolution_Date__c = System.today()+7;
         issue.release__c=rel.id;
         insert issue;
         
        
        PageReference pageRef = Page.SaaSClientQuestionSearch;
        pageRef.getParameters().put(SaaSTextConstant.IS_CLONE_URL_PARAM, '1');
        pageRef.getParameters().put(SaaSTextConstant.RELEASEID_URL_PARAM,rel.id);
        Test.setCurrentPage(pageRef);
        
        SaaSCreateIssueRiskCtrl IssRisk = new SaaSCreateIssueRiskCtrl(new ApexPages.StandardController(issue));
        IssRisk.issueRiskType = 'Issue'; 
        IssRisk.disbaleRecordType();
        IssRisk.getRecordType();
        IssRisk.saveIssueRisk();
        IssRisk.issueRiskObj.Status__c = null;
        IssRisk.saveIssueRisk();
        IssRisk.issueRiskObj.Status__c = 'Status';
        IssRisk.targetResolutionDate  = system.today().addDays(10);
        IssRisk.loggedDate =  system.today();
        IssRisk.saveIssueRisk();
        IssRisk.createIssueOrRisk();
        
    }  
    
     static testMethod void validateIssueRiskCtrl() 
     {
         Issues_Risks__c issue = new Issues_Risks__c();
         SaaSCreateIssueRiskCtrl controller = new SaaSCreateIssueRiskCtrl(new ApexPages.StandardController(issue));
         controller.saveIssueRisk();
         controller.createIssueOrRisk();     
     } 
      
    
    static testMethod void validateIssueRiskClone() 
    {
        Release__c rel =SaaSTestUtility.createRelease();
        Request__c req = new Request__c();
        req.Status__c= 'Identify: New Requirement';
        req.Request_Title__c = 'Test description ';
        req.Request_Type__c ='Integration ';
        req.Request_Description__c= 'Test description ';
        req.Release__c = rel.id;
        insert req;
        Issues_Risks__c issue = SaaSTestUtility.createIssue();
        PageReference pageRef = Page.SaaSCreateIssueRiskPage;
        Test.setCurrentPage(pageRef);
        SaaSCreateIssueRiskCtrl IssRisk = new SaaSCreateIssueRiskCtrl(new ApexPages.StandardController(issue));
        
        IssRisk.saveIssueRisk();
        IssRisk.disbaleRecordType();
        IssRisk.getRecordType();
         IssRisk.issueRiskObj.Priority__c = null;
        IssRisk.saveIssueRisk();
        IssRisk.issueRiskObj.Priority__c = 'priority';
        IssRisk.saveIssueRisk();
        IssRisk.issueRiskObj.Description__c = null;
        IssRisk.saveIssueRisk();
        IssRisk.issueRiskObj.Description__c = 'Desc';
        IssRisk.saveIssueRisk();
        IssRisk.TargetResolutionDate = null;
        IssRisk.saveIssueRisk();
        IssRisk.TargetResolutionDate = System.today();
        IssRisk.saveIssueRisk();
               
        IssRisk.validateKeyDecision();
        IssRisk.issueRiskObj.Target_Resolution_Date__c = system.today().addDays(10);
        IssRisk.saveIssueRisk();
        IssRisk.createIssueOrRisk();
    } 


}