force-app/main/default/objects/Test_Case__c/Test_Case__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a case for which you would run a test script.</description>
    <label>Test Scenario</label>
    <nameField>
        <label>Test Scenario ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Case__c/fields/Execution_Status__c.field-meta.xml
<CustomField>
    <fullName>Execution_Status__c</fullName>
    <label>Execution Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Result__c/Test_Result__c.object-meta.xml
<CustomObject>
    <label>Test Result</label>
    <nameField>
        <displayFormat>TestResult-{0000}</displayFormat>
        <label>Test Result ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Result__c/fields/Test_Case__c.field-meta.xml
<CustomField>
    <fullName>Test_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Scenario</label>
    <referenceTo>Test_Case__c</referenceTo>
    <relationshipLabel>Test Results</relationshipLabel>
    <relationshipName>Test_Results1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Result__c/fields/Test_Result__c.field-meta.xml
<CustomField>
    <fullName>Test_Result__c</fullName>
    <inlineHelpText>If ANY step failed, please log the Test Result as Failed.</inlineHelpText>
    <label>Test Result?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestResultTriggerHelper.cls
public class TestResultTriggerHelper {
    public static void updateStatusOnTestScenario(List<Test_Result__c> testResults){
        Set<Id> testScenes =  new Set<Id>();
        integer count=0;
        List<Test_Case__c> testSceneUpdate = new List<Test_Case__c>();
        try{
            For(Test_Result__c tr:testResults){
                testScenes.add(tr.Test_Case__c);
            }
            //Check all Test Results for the testScenes
            For(Test_Case__c testScene:[SELECT Id,Execution_Status__c,(select id,Test_Result__c from Test_Results1__r order by Test_Result__c desc) FROM Test_Case__c Where Id In: testScenes]){
                For(Test_Result__c tr:testScene.Test_Results1__r){
                    system.debug('tr-->'+tr);
                    If(tr.Test_Result__c.equals('Failed')){
                        testScene.Execution_Status__c = 'Failed';
                        break;
                    }
                    else If(tr.Test_Result__c.equals('Not Started') || tr.Test_Result__c.equals('In Progress')){
                        testScene.Execution_Status__c = 'Pending';
                    }
                    else{
                        count=count+1;
                    }
                }
                if(count==(testScene.Test_Results1__r).size()){
                    testScene.Execution_Status__c = 'Passed';
                }
                count=0;
                system.debug('testScene-->'+testScene);
                testSceneUpdate.add(testScene);
            }
            system.debug('testSceneUpdate-->'+testSceneUpdate);
            update testSceneUpdate;  
    	}
        catch(Exception ex){
             system.debug('ex: '+ex);  
             system.debug('ex line no: '+ex.getLineNumber());  
        }
    }        
}