force-app/main/default/objects/Capability__c/Capability__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents as set ability, such as managing opportunities.</description>
    <label>Capability</label>
    <nameField>
        <label>Capability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Capability__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related release to the capability</description>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Capabilities</relationshipLabel>
    <relationshipName>Capabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about Release</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story__c/fields/Capability__c.field-meta.xml
<CustomField>
    <fullName>Capability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capability</label>
    <referenceTo>Capability__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/User_Story_Description__c.field-meta.xml
<CustomField>
    <fullName>User_Story_Description__c</fullName>
    <label>User Story Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/Value_Delivery_Session__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session</label>
    <nameField>
        <label>Value Delivery Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>To store Session Details.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Releases__c.field-meta.xml
<CustomField>
    <fullName>Releases__c</fullName>
    <description>Add Session to The Existing Project</description>
    <label>Releases</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Value Delivery Sessions</relationshipLabel>
    <relationshipName>Value_Delivery_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/Value_Delivery_Session_Outcomes__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session Outcomes</label>
    <nameField>
        <label>Session Outcomes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Session Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/fields/Value_Delivery_Session__c.field-meta.xml
<CustomField>
    <fullName>Value_Delivery_Session__c</fullName>
    <label>Value Delivery Session</label>
    <referenceTo>Value_Delivery_Session__c</referenceTo>
    <relationshipName>Session_Outcomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_User_Stories__c/Value_Delivery_Session_User_Stories__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session User Stories</label>
    <nameField>
        <displayFormat>Session User-{0000}</displayFormat>
        <label>Value Deliver Session User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Value Delivery Session User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session_User_Stories__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Value Delivery Session User Stories</relationshipLabel>
    <relationshipName>Value_Deliver_Session_User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_User_Stories__c/fields/Value_Delivery_Session_Outcomes__c.field-meta.xml
<CustomField>
    <fullName>Value_Delivery_Session_Outcomes__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Value Delivery Session Outcomes</label>
    <referenceTo>Value_Delivery_Session_Outcomes__c</referenceTo>
    <relationshipLabel>Value Delivery Session User Stories</relationshipLabel>
    <relationshipName>Value_Deliver_Session_User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SaasSessionUserStories.cls
/** 
 *  Author : Accenture 
 *  Description : Controller class for SaasSessionUserStories page
 *  Created Date : 05\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  05\06\2015        created 
 *
 */ 
 
public with sharing class SaasSessionUserStories 
{
    public Value_Delivery_Session_Outcomes__c sessOutcomeObj {get;set;}
    public String valueSessionPrjName {get;set;}
    private List<UserStoriesWrapper> UserStoriesWrapLst;
    public String searchtxt {get;set;}
    private Set<Id> sessionUserStoriesSet = new Set<Id>();
    Public Id Release;
     /**
     * Constructor   
     *
     */ 
    public SaasSessionUserStories(ApexPages.StandardController controller) 
    {
        sessOutcomeObj= (Value_Delivery_Session_Outcomes__c )controller.getRecord();
        Value_Delivery_Session__c valuedeliverysession =[select id,Releases__c from Value_Delivery_Session__c where id =:sessOutcomeObj.Value_Delivery_Session__c];
        Release = valuedeliverysession.Releases__c;
        system.debug('===Release==='+Release);
        valueSessionPrjName = SaaSUtility.getValueSessionProjectName();
        for(Value_Delivery_Session_User_Stories__c userStories: [Select User_Story__c,Value_Delivery_Session_Outcomes__c from  Value_Delivery_Session_User_Stories__c where Value_Delivery_Session_Outcomes__c =:sessOutcomeObj.ID])
        {
            sessionUserStoriesSet.add(userStories.User_Story__c);
        } 
        
   }    
    
    
    
    public ApexPages.StandardSetController con 
    {
        get 
        {
            if(con == null) 
            {
                //con = new ApexPages.StandardSetController(Database.getQueryLocator([Select Name,Priority__c, Status__c, Description__c,Decision_Outcome__c,Due_Date__c,RecordType.Name FROM User_Story__c  Order By CreatedDate DESC]));            
                con = new ApexPages.StandardSetController(Database.query(getSoql()));
                con.setPageSize(SaaSTextConstant.LIST_VIEW_PAGE_SIZE);
            }
            return con;
        }
        set;
    }

   /**
    * Get Records form the Standardset controller 
    *
    * @param args none.
    * @return none 
    *
    */ 
    public List<UserStoriesWrapper> getUserStoriesWrapLst() 
    {
        
        UserStoriesWrapLst= new List<UserStoriesWrapper>();
        List<User_Story__c> userStoryLst =(List<User_Story__c>)con.getRecords();
        for(User_Story__c storyObj: userStoryLst )
        {       
            UserStoriesWrapLst.add(new UserStoriesWrapper(storyObj));
        }
        return UserStoriesWrapLst;
    }
       
    /**
     * indicates whether there are more records after the current page set.
     *
     * @param args none.
     * @return none 
     *
     */       
     public Boolean hasNext {
        get {
            return con.getHasNext();
        }
        set;
    }

    /**
     * indicates whether there are more records before the current page set.
     *
     * @param args none.
     * @return none 
     *
     */    
    public Boolean hasPrevious {
        get {
            return con.getHasPrevious();
        }
        set;
     }

   /**
     *  returns the previous page of records
     *
     * @param args none.
     * @return none 
     *
     */   
     public void previous() {
         con.previous();
     }

    /**
     *  returns the next page of records
     *
     * @param args none.
     * @return none 
     *
     */       
     public void next() {
         con.next();
     }

   /**
    *  UserStoriesWrapper Wrapper Class 
    *
    */   
    public class UserStoriesWrapper
    {
        public Boolean checked{ get; set;}
        public User_Story__c  UserStoryObj{ get; set;}  
        
        public UserStoriesWrapper(User_Story__c  c)
        {
            UserStoryObj= c;
            checked = false;
        }      
    }
  /**     
   * Search for Key Decision records for given Srtring 
   *
   * @param args none.
   * @return PageReference 
   *
   */       
    public void search()
    {           
        if(searchtxt!= null)
        {
            searchtxt =searchtxt.trim();
        }
          con = new ApexPages.StandardSetController(Database.query(getSoql()));
          con.setPageSize(SaaSTextConstant.LIST_VIEW_PAGE_SIZE);             
    }    
  
    /**
     * Get Selected Element from the List
     *
     * @param args none.
     * @return List<User_Story__c > 
     *
     */     
    public List<User_Story__c > getSelectedElement()
    {
        List<User_Story__c> slectedUserStory = new List<User_Story__c >();    
        if(UserStoriesWrapLst!= null)
        {
            for(UserStoriesWrapper wrapObj : UserStoriesWrapLst)
            {
                if(wrapObj.checked)
                {
                    slectedUserStory.add(wrapObj.UserStoryObj);    
                }
            }
        }
        return slectedUserStory;
    }
    
     /**
    * To set a Direction either in ascending order or descending order.
    *
    */       
    public String sortDir 
    {   
       get  { if (sortDir == null) {  sortDir = SaaSTextConstant.ASCENDING_SORT_ORDER ; } return sortDir;}
       set;
    }

   /**
    * The current field to sort by. defaults to last name
    *
    */  
    public String sortField 
    {

        get  { if (sortField == null) {sortField = SaaSTextConstant.NAME_FIELD_API_NAME ; } return sortField;  }
        set;
    }
    
   /**
    * Sort List View By Column
    *
    */  
    public void sortByColumn()
    {
         sortDir = sortDir.equals(SaaSTextConstant.ASCENDING_SORT_ORDER ) ? SaaSTextConstant.DESCENDING_SORT_ORDER  :  SaaSTextConstant.ASCENDING_SORT_ORDER ;
         search();
         
    }
    
   /**
    * Get Soql For the List View
    *
    */          
    private String getSoql()
    {
       //String soql = 'Select Name,Priority__c, Release__r.Name, User_Story_Description__c,Capability__r.Name FROM User_Story__c  where ID NOT IN : sessionUserStoriesSet AND Release__c = \'' + sessOutcomeObj.Value_Delivery_Session__r.Releases__c + '\'';                          
        String soql = 'Select Name,Priority__c, Release__r.Name, User_Story_Description__c,Capability__r.Name FROM User_Story__c  where ID NOT IN : sessionUserStoriesSet AND Release__c = \'' + Release + '\'';                          

          soql =  soql + ' Order By ' + sortField + ' ' + sortDir + ' NULLS LAST' ;                            
           return soql ;
        
    }      
    
    /**
     * Import User Stories into value Delivery Sessions
     *
     */
    public PageReference importUserStories()
    {
       Id UserId; 
       List<Value_Delivery_Session_User_Stories__c> userLinkLst  = new   List<Value_Delivery_Session_User_Stories__c>();        

        List<User_Story__c> userStoryLst =  getSelectedElement();
      
        // Check if any user story is selected
        if(userStoryLst.size() ==0 )
        {
            SaaSUtility.displayErrMsg('Select User Stories to import.' );   
            return null;
        }
        for(User_Story__c userStoryObj : userStoryLst ) 
        {
            Value_Delivery_Session_User_Stories__c obj = new Value_Delivery_Session_User_Stories__c();
            obj.User_Story__c = userStoryObj.id;
            obj.Value_Delivery_Session_Outcomes__c = sessOutcomeObj.id;  
            //obj.Name=sessOutcomeObj.name +'_'+ Date.Today();
            userLinkLst.add(obj);  
        }           
        
        try
        {   
            insert userLinkLst; 
            PageReference orderPage = new PageReference('/apex/SaaSSessionOutcomeDetail?id=' + sessOutcomeObj.id);
            orderPage.setRedirect(true);
            return orderPage;   
        }
        catch(Exception e )
        {
        
        }
        return null;           
    }    
}