force-app/main/default/objects/Capability__c/Capability__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents as set ability, such as managing opportunities.</description>
    <label>Capability</label>
    <nameField>
        <label>Capability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Capability__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related release to the capability</description>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Capabilities</relationshipLabel>
    <relationshipName>Capabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status_Update__c.field-meta.xml
<CustomField>
    <fullName>Status_Update__c</fullName>
    <description>Release status update</description>
    <inlineHelpText>Release status update</inlineHelpText>
    <label>Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Capability__c.field-meta.xml
<CustomField>
    <fullName>Capability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Capability related to the request</description>
    <label>Capability</label>
    <referenceTo>Capability__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Release in which the request will go</description>
    <inlineHelpText>The release in which the request will actually be deployed. If the requirement has not been approved for a release, there should not be a value in this field.</inlineHelpText>
    <label>Committed Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Requests (Committed Release)</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Description__c.field-meta.xml
<CustomField>
    <fullName>Request_Description__c</fullName>
    <description>Gathers further details for requirements.</description>
    <inlineHelpText>Detailed Summary* 
Screen(s) Impacted* 
Field Name(s) &amp; Type(s)* 
Picklist Values 
Calculation 
Dependency 
Workflow/Approval Rules 
Interfacing System Updates 
Interface Frequency 
Data Volumes 
*Indicates information required for all requests!</inlineHelpText>
    <label>Initial Request</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Title__c.field-meta.xml
<CustomField>
    <fullName>Request_Title__c</fullName>
    <description>Captures the requirement title</description>
    <inlineHelpText>Captures the requirement title</inlineHelpText>
    <label>Request Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>Type of the request</description>
    <inlineHelpText>If you are unsure of the type of request you are submitting, please select Unknown.</inlineHelpText>
    <label>Request Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Configuration</fullName>
            </value>
            <value>
                <fullName>Custom Code</fullName>
            </value>
            <value>
                <fullName>Data Access</fullName>
            </value>
            <value>
                <fullName>Data Migration</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>User Administration</fullName>
            </value>
            <value>
                <fullName>User Story</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the request</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Identify: New Requirement</fullName>
                <default>true</default>
                <label>Identify: New Requirement</label>
            </value>
            <value>
                <fullName>Identify: Submit for Business Review</fullName>
            </value>
            <value>
                <fullName>Identify: Deferred</fullName>
            </value>
            <value>
                <fullName>Consolidate: Approve to Estimate</fullName>
            </value>
            <value>
                <fullName>Consolidate: Level of Effort Complete</fullName>
            </value>
            <value>
                <fullName>Approve: Approved to Deploy</fullName>
            </value>
            <value>
                <fullName>Release: Design</fullName>
            </value>
            <value>
                <fullName>Release: Build</fullName>
            </value>
            <value>
                <fullName>Release: Test</fullName>
            </value>
            <value>
                <fullName>Release: SIT</fullName>
            </value>
            <value>
                <fullName>Release: UAT</fullName>
            </value>
            <value>
                <fullName>Release: Build Production</fullName>
            </value>
            <value>
                <fullName>Release: Test Production</fullName>
            </value>
            <value>
                <fullName>Close: Deployed</fullName>
            </value>
            <value>
                <fullName>Close: Rejected</fullName>
            </value>
            <value>
                <fullName>Close: Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Total_Estimate_Bottom_Up__c.field-meta.xml
<CustomField>
    <fullName>Total_Estimate_Bottom_Up__c</fullName>
    <description>Total estimated level of effort for build, design &amp; test of the request</description>
    <formula>Build_Total__c + Design_Total__c + Test_Total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Solution Capacity Estimate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Total_Priority_Ranking__c.field-meta.xml
<CustomField>
    <fullName>Total_Priority_Ranking__c</fullName>
    <description>Priority ranking of the request based on Business benefit, Urgency of request, User impact &amp; LOE</description>
    <formula>( Business_Benefit_Value__c  +  Urgency_of_Request_Value__c  +  User_Impact_of_Change_Value__c  +  Level_of_Effort_Value__c  )  / 4</formula>
    <label>Total Priority Ranking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SaaSRequestListViewCtrl.cls
/** 
 *  Author : Accenture 
 *  Description : Controller class for SaaSRequestListView
 *  Created Date : 05\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  05\06\2015        created 
 *
 */
public class SaaSRequestListViewCtrl
{

    private List<RequestWrapper> requestWrapLst;
    public String searchtxt {get;set;}
    /**
     * Constructor   
     *
     */    
    public SaaSRequestListViewCtrl ()
    {
        searchtxt = '';
    }    
    
    public ApexPages.StandardSetController con 
    {
        get 
        {
            if(con == null) 
            {
                     
                con = new ApexPages.StandardSetController(Database.query(getSoql()));
                con.setPageSize(SaaSTextConstant.LIST_VIEW_PAGE_SIZE);
            }
            return con;
        }
        set;
    }

    /**
     * Get Records form the Standardset controller 
     *
     * @param args none.
     * @return none 
     *
     */ 
    public List<RequestWrapper> getrequestWrapLst() 
    {
        requestWrapLst= new List<RequestWrapper>();
        for (Request__c  requestObj : (List<Request__c >)con.getRecords())
            requestWrapLst.add(new RequestWrapper(requestObj));

        return requestWrapLst;
    }
        
   /**
     * indicates whether there are more records after the current page set.
     *
     * @param args none.
     * @return none 
     *
     */    public Boolean hasNext {
        get {
            return con.getHasNext();
        }
        set;
    }

   /**
     * indicates whether there are more records before the current page set.
     *
     * @param args none.
     * @return none 
     *
     */        public Boolean hasPrevious {
        get {
            return con.getHasPrevious();
        }
        set;
    }

   /**
     *  returns the first page of records
     *
     * @param args none.
     * @return none 
     *
     */   
     public void first() {
         con.first();
     }

    /**
     *  returns the last page of records
     *
     * @param args none.
     * @return none 
     *
     */   
     public void last() {
         con.last();
     }

     /**
     *  returns the previous page of records
     *
     * @param args none.
     * @return none 
     *
     */   
     public void previous() {
         con.previous();
     }

  
    /**
     *  returns the next page of records
     *
     * @param args none.
     * @return none 
     *
     */       
     public void next() {
         con.next();
     }

    
    /**
     *  Request Wrapper Class 
     *
     */   
    public class RequestWrapper
    {
        public Boolean checked{ get; set;}
        public Request__c requestListObj{ get; set;}  
        
        public RequestWrapper(Request__c c)
        {
            requestListObj = c;
            checked = false;
        }      
    }
    /**
     * Search for relase records for given Srtring 
     *
     * @param args none.
     * @return PageReference 
     *
     */       
    public void search()
    {           
        // con = new ApexPages.StandardSetController(Database.getQueryLocator([Select name, Id,Request_Title__c,Request_Description__c,Request_Type__c,Status__c,Total_Priority_Ranking__c,Total_Estimate_Bottom_Up__c,Release__r.Status_Update__c from Request__c  where name like : ('%'+searchtxt+'%' )   Order By Name limit 100]));            
       //  con.setPageSize(5);  
       if(searchtxt!= null)
        {
            searchtxt =searchtxt.trim();
        }
        con = new ApexPages.StandardSetController(Database.query(getSoql()));
        con.setPageSize(SaaSTextConstant.LIST_VIEW_PAGE_SIZE);

  
    }    
    /**
     * Delete Selected Record
     *
     * @param args none.
     * @return PageReference 
     *
     */                
    public void deleteRequest()
    {
        String errMsg  = null;
        List<Request__c > delRequest = getSelectedElement();
        if(delRequest.size () > 0)
        {
           errMsg  = SaaSUtility.deleteSobject(delRequest);
           if(errMsg  != null)
           {
                SaaSUtility.displayErrMsg(errMsg   );    
           }
           else
           {
                con = null;
                SaaSUtility.displaySuccessMsg(SaaSTextConstant.DELETE_SELECT_ONE_RECORD_SAVE_MSG );
           }     
        }
        else 
        {
             SaaSUtility.displayErrMsg(SaaSTextConstant.DELETE_SELECT_ONE_RECORD_ERR_MSG );    
        }            
    
    }
    /**
     * Navigate to Update Request page 
     *
     * @param args none.
     * @return PageReference 
     *
     */    
    public PageReference updateRequest()
    {
        List<Request__c > updateRequest = getSelectedElement();
        if(updateRequest.size() > 1)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.EDIT_MULTIPLE_SELECT_ERR_MSG );               
            return null;
        }
        
        if(updateRequest.size() == 0)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.EDIT_SELECT_ONE_RECORD_ERR_MSG );           
            return null;            
        }          
        return  new  PageReference(SaaSTextConstant.CREATE_REQUEST_VF_PAGE_NAME_URL+'?id='+updateRequest.get(0).id);                 
    }
    /**
     * Navigate to Selected Record to Clone
     *
     * @param args none.
     * @return List<Release__c> 
     *
     */     
    public PageReference cloneRequest()
    {

        List<Request__c > cloneRequest = getSelectedElement();
        if(cloneRequest.size() > 1)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.CLONE_SELECT_ONE_RECORD_ERR_MSG );                   
            return null;
        }
        
        if(cloneRequest.size() == 0)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.CLONE_MULTIPLE_SELECT_ERR_MSG );                          
            return null;            
        }          
        return new PageReference(SaaSTextConstant.CREATE_REQUEST_VF_PAGE_NAME_URL +'?isClone=1&&id='+cloneRequest.get(0).id);                 
    }
    
   /*public void approveRequest()
    {
        List<Request__c> aprvRequest = getSelectedElement();
        List<Approval.ProcessSubmitRequest> approvalLst = new List<Approval.ProcessSubmitRequest>();
        if(aprvRequest.size() == 0)
        {
            SaaSPageMessages.addMessage(new SaaSPageMessages.PageMessage(SaaSPageMessages.Severity.WARN, 'Please select atleast one record to clone.'));                  
            return ;            
        }  
        for(Request__c req:aprvRequest)
        {
             Approval.ProcessSubmitRequest AppRequest = new Approval.ProcessSubmitRequest();
             AppRequest.setComments('Submitting price change request for approval');
             AppRequest.setObjectId(req.id);
             approvalLst.add(AppRequest);
    
        }
          Approval.ProcessResult[] result = Approval.process(approvalLst, true);
        
    }*/  
    
    /**
     * Get Selected Element from the list
     *
     * @param args none.
     * @return List<Release__c> 
     *
     */       
    public List<Request__c > getSelectedElement()
    {
        List<Request__c > slectedRequest = new List<Request__c >();    
        if(requestWrapLst!= null)
        {
            for(RequestWrapper wrapObj : requestWrapLst)
            {
                if(wrapObj.checked)
                {
                    slectedRequest.add(wrapObj.requestListObj);    
                }
            }
        }
        return slectedRequest;
    } 
    /**
    * To set a Direction either in ascending order or descending order.
    *
    */       
    public String sortDir 
    {   
       get  { if (sortDir == null) {  sortDir = SaaSTextConstant.ASCENDING_SORT_ORDER ; } return sortDir;}
       set;
    }

   /**
    * The current field to sort by. defaults to last name
    *
    */  
    public String sortField 
    {

        get  { if (sortField == null) {sortField = SaaSTextConstant.NAME_FIELD_API_NAME ; } return sortField;  }
        set;
    }
    
   /**
    * Sort List View By Column
    *
    */  
    public void sortByColumn()
    {
         sortDir = sortDir.equals(SaaSTextConstant.ASCENDING_SORT_ORDER ) ? SaaSTextConstant.DESCENDING_SORT_ORDER  :  SaaSTextConstant.ASCENDING_SORT_ORDER ;
         search();
         
    }
    
   /**
    * Get Soql For the List View
    *
    */          
    private String getSoql()
    {
        String soql = 'Select name, Id,Request_Title__c,Request_Description__c,Request_Type__c,Status__c,Release__r.name from Request__c where ';
               soql = soql +  'name like  \'%'+searchtxt+'%\'  or ';
               soql = soql +  'Request_Title__c like  \'%'+searchtxt+'%\'  or '; 
              // soql = soql +  'Request_Type__c like  \'%'+searchtxt+'%\'  or '; 
               soql = soql +  'Capability__r.name like  \'%'+searchtxt+'%\' or ';
               soql = soql +  'Status__c like \'%'+searchtxt+'%\'  Order By ' + sortField + ' ' + sortDir + ' NULLS LAST' ;
               
               
        return soql;              
    }         
}