force-app/main/default/objects/Capability__c/Capability__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents as set ability, such as managing opportunities.</description>
    <label>Capability</label>
    <nameField>
        <label>Capability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Capability__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related release to the capability</description>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Capabilities</relationshipLabel>
    <relationshipName>Capabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/Question_Log__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a question that a project team member has about a request.</description>
    <label>Question Log</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Question Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Log__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User responsible to answer the Question Log</description>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Question_Logs2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Capability__c.field-meta.xml
<CustomField>
    <fullName>Capability__c</fullName>
    <description>Related request&#39;s capability name</description>
    <formula>Request__r.Capability__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capability</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Additional details about Question Log.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Expected_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Close_Date__c</fullName>
    <description>Expected Closing Date for Question Log.</description>
    <label>Expected Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Severity of Question Log.</description>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Detailed question.</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related request to the question log</description>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Question Log</relationshipLabel>
    <relationshipName>Question_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Date__c</fullName>
    <description>Date of request of Question Log</description>
    <label>Requested Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of Question Log</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Clarification Requested</fullName>
            </value>
            <value>
                <fullName>Clarification Provided</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Submitter__c.field-meta.xml
<CustomField>
    <fullName>Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who submitted the Question Log</description>
    <label>Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Question_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about Release</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the  user that  is assigned to build the requirement</description>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Capability__c.field-meta.xml
<CustomField>
    <fullName>Capability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Capability related to the request</description>
    <label>Capability</label>
    <referenceTo>Capability__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>High 
Medium 
Low</description>
    <inlineHelpText>High 
Medium 
Low</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Question to be raised with Functional team</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Release in which the request will go</description>
    <inlineHelpText>The release in which the request will actually be deployed. If the requirement has not been approved for a release, there should not be a value in this field.</inlineHelpText>
    <label>Committed Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Requests (Committed Release)</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the request</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Identify: New Requirement</fullName>
                <default>true</default>
                <label>Identify: New Requirement</label>
            </value>
            <value>
                <fullName>Identify: Submit for Business Review</fullName>
            </value>
            <value>
                <fullName>Identify: Deferred</fullName>
            </value>
            <value>
                <fullName>Consolidate: Approve to Estimate</fullName>
            </value>
            <value>
                <fullName>Consolidate: Level of Effort Complete</fullName>
            </value>
            <value>
                <fullName>Approve: Approved to Deploy</fullName>
            </value>
            <value>
                <fullName>Release: Design</fullName>
            </value>
            <value>
                <fullName>Release: Build</fullName>
            </value>
            <value>
                <fullName>Release: Test</fullName>
            </value>
            <value>
                <fullName>Release: SIT</fullName>
            </value>
            <value>
                <fullName>Release: UAT</fullName>
            </value>
            <value>
                <fullName>Release: Build Production</fullName>
            </value>
            <value>
                <fullName>Release: Test Production</fullName>
            </value>
            <value>
                <fullName>Close: Deployed</fullName>
            </value>
            <value>
                <fullName>Close: Rejected</fullName>
            </value>
            <value>
                <fullName>Close: Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/recordTypes/Question.recordType-meta.xml
<RecordType>
    <fullName>Question</fullName>
    <active>true</active>
    <description>Question to be raised with Functional team</description>
    <label>Question</label>
</RecordType>

force-app/main/default/classes/SaaSQuestionLogListViewCtrl.cls
/** 
 *  Author : Accenture 
 *  Description : Controller class for SaaSQuestionLogListView
 *  Created Date : 05\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  05\06\2015        created 
 *
 */ 
public class SaaSQuestionLogListViewCtrl
{
    private List<SaaSQuestionLogWrapper> QuesLogWrapLst;
    public String searchtxt {get;set;}
    public Boolean isAccRep  {get;set;}
    
   /**
    * Constructor   
    *
    */          
    public SaaSQuestionLogListViewCtrl()
    {        
        isAccRep = SaaSUtility.isAccentureRepresentative();
        searchtxt = '';
    }    
    
    public ApexPages.StandardSetController con 
    {
        get 
        {
            if(con == null) 
            {
                //con = new ApexPages.StandardSetController(Database.getQueryLocator([Select Submitter__r.name,Assigned_To__r.name, (Select ID from Responses__r ), Question__c,Expected_Close_Date__c, Request__r.name, Capability__c ,Priority__c, Status__c, Description__c,Requested_Date__c,Id, recordType.name,recordType.DeveloperNAme, Name FROM Question_Log__c Order By CreatedDate DESC]));            
                con = new ApexPages.StandardSetController(Database.query(getSoql()));
                con.setPageSize(SaaSTextConstant.LIST_VIEW_PAGE_SIZE);
              }   
            return con;
        }
        set;
    }
    

   /**
     * Get Selected Element from the List
     *
     * @param args none.
     * @return List<Release__c> 
     *
     */    
    public List<SaaSQuestionLogWrapper> getQuesLogWrapLst() 
    {
        QuesLogWrapLst= new List<SaaSQuestionLogWrapper>();
        for (Question_Log__c QuesObj : (List<Question_Log__c>)con.getRecords())
            QuesLogWrapLst.add(new SaaSQuestionLogWrapper(QuesObj));

        return QuesLogWrapLst;
    }

   

    /**
     * indicates whether there are more records after the current page set.
     *
     * @param args none.
     * @return none 
     *
     */    
     public Boolean hasNext {
        get {
            return con.getHasNext();
        }
        set;
    }

  
    /**
     * indicates whether there are more records before the current page set.
     *
     * @param args none.
     * @return none 
     */       
     public Boolean hasPrevious {
        get {
            return con.getHasPrevious();
        }
        set;
    }

  
     /**
     *  returns the previous page of records
     *
     * @param args none.
     * @return none 
     *
     */     
     public void previous() {
         con.previous();
     }

  
    /**
     *  returns the next page of records
     *
     * @param args none.
     * @return none 
     *
     */      
     
     public void next() {
         con.next();
     }

   /**
    * Search for the question record  
    *
    * @param args none.     
    * @return none 
    *
    */         
    public void search()
    {
        // con = new ApexPages.StandardSetController(Database.getQueryLocator([Select Submitter__r.name,Assigned_To__r.name, (Select ID from Responses__r limit 1), Question__c,Expected_Close_Date__c, Request__r.name, Capability__c ,Priority__c, Status__c, Description__c,Requested_Date__c,Id, recordType.Name, Name FROM Question_Log__c where name like : ('%'+searchtxt+'%' )  ]));            
         // con.setPageSize(25);  
         if(searchtxt!= null)
        {
            searchtxt =searchtxt.trim();
        }
        con = new ApexPages.StandardSetController(Database.query(getSoql()));
        con.setPageSize(SaaSTextConstant.LIST_VIEW_PAGE_SIZE);
  
    }    
   /**
    * Delete Question 
    *
    * @param args none.     
    * @return none 
    *
    */      
   public void deleteQuestion()
   {
        List<Question_Log__c > deleteQuest = getSelectedElement();
        String errMsg= null;
         
        if(deleteQuest.size() == 0)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.DELETE_SELECT_ONE_RECORD_ERR_MSG ); 
            return ;            
        }   
        errMsg =  SaaSUtility.deleteSobject(deleteQuest);
        if(errMsg != null)
        {
            SaaSUtility.displayErrMsg(errMsg);
        }
        else
        {
             con = null;
             SaaSUtility.displaySuccessMsg(SaaSTextConstant.DELETE_SELECT_ONE_RECORD_SAVE_MSG );
        }                   
    
    }
    /**
     * Navigate to Selected Record to Edit
     *
     * @param args none.
     * @return List<Release__c> 
     *
     */         
    public PageReference updateQuestion()
    {
        List<Question_Log__c> questionLst = getSelectedElement();
        if(questionLst.size() > 1)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.EDIT_MULTIPLE_SELECT_ERR_MSG );                   
            return null;
        }
        
        if(questionLst .size() == 0)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.EDIT_SELECT_ONE_RECORD_ERR_MSG );                          
            return null;            
        }          
        return new PageReference(SaaSTextConstant.CREATE_QUESTION_VF_PAGE_NAME_URL  +'?id='+questionLst.get(0).id);                     
    }
     /**
     * Navigate to Selected Record to LinkToRequest
     *
     * @param args none.
     * @return List<Release__c> 
     *
     */         
    public PageReference linkToRequest()
    {
        List<Question_Log__c> questionLst = getSelectedElement();
        if(questionLst.size() > 1)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.EDIT_MULTIPLE_SELECT_ERR_MSG );                   
            return null;
        }
        
        if(questionLst .size() == 0)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.EDIT_SELECT_ONE_RECORD_ERR_MSG );                          
            return null;            
        }          
        return new PageReference(SaaSTextConstant.Link_To_QUESTION_VF_PAGE_NAME_URL+'?id='+questionLst.get(0).id);                     
    }
    /**
     * Navigate to Selected Record to convert question to request
     *
     * @param args none.
     * @return PageReference 
     *
     */  
    public PageReference convertToRequest()
    {
         List<Question_Log__c> questionLst = getSelectedElement();
        if(questionLst.size() > 1)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.CONVERT_QUEST_MULTIPLE_SELECT_ERR_MSG );                   
            return null;
        }
        
        if(questionLst .size() == 0)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.CONVERT_QUEST_SELECT_ONE_RECORD_ERR_MSG );                          
            return null;            
        }          
        return new PageReference(SaaSTextConstant.CREATE_REQUEST_VF_PAGE_NAME_URL+'?'+SaaSTextConstant.CONVERT_QUEST+'=1&&'+SaaSTextConstant.CONVERT_QUEST_ID+'='+questionLst.get(0).id);  
    }
   /**
     * Navigate to Selected Record to Clone
     *
     * @param args none.
     * @return PageReference  
     *
     */     
    public PageReference cloneQuestion()
    {

        List<Question_Log__c> cloneQuest = getSelectedElement();
        if(cloneQuest.size() > 1)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.CLONE_SELECT_ONE_RECORD_ERR_MSG );                   
            return null;
        }
        
        if(cloneQuest.size() == 0)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.CLONE_MULTIPLE_SELECT_ERR_MSG );                          
            return null;            
        }          
        return new PageReference(SaaSTextConstant.CREATE_QUESTION_VF_PAGE_NAME_URL +'?isClone=1&&id='+cloneQuest.get(0).id);                 
    }
    /**
     * Get Selected Element from the List
     *
     * @param args none.
     * @return List<Release__c> 
     *
     */         
    public List<Question_Log__c > getSelectedElement()
    {
        List<Question_Log__c > slectedQuestion = new List<Question_Log__c >();    
        if(QuesLogWrapLst!= null)
        {
            for(SaaSQuestionLogWrapper wrapObj : QuesLogWrapLst)
            {
                if(wrapObj.checked)
                {
                    slectedQuestion.add(wrapObj.questionLogObj);    
                }
            }
        }
        return slectedQuestion;
    }
      /**
     * Navigate to Comments page 
     *
     * @param args none.
     * @return List<Release__c> 
     *
     */    
    public PageReference commentQuestion()
    {
        PageReference pegRef = null;
        List<Question_Log__c > commentQuestion = getSelectedElement();
        if(commentQuestion.size() > 1)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.COMMENT_MULTIPLE_SELECT_ERR_MSG);        
            return null;
        }
        
        if(commentQuestion.size() == 0)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.COMMENT_SELECT_ONE_RECORD_ERR_MSG ); 
            return null;            
        }  
        
        if(commentQuestion.get(0).recordType.DeveloperNAme == SaaSTextConstant.VALUE_DELIVERY_QUESTION_RECORD_TYPE)
        {
            pegRef = new  PageReference(SaaSTextConstant.CREATE_QUESTION_RESP_VF_PAGE_NAME_URL+'?id='+commentQuestion.get(0).id);            
        }
        else
        {                
             pegRef = new  PageReference(SaaSTextConstant.CREATE_QUESTION_VF_PAGE_NAME_URL +'?id='+commentQuestion.get(0).id); 
        }    
        pegRef.setRedirect(true);
        return pegRef;             
    }
     /**
    * To set a Direction either in ascending order or descending order.
    *
    */       
    public String sortDir 
    {   
       get  { if (sortDir == null) {  sortDir = SaaSTextConstant.ASCENDING_SORT_ORDER ; } return sortDir;}
       set;
    }

   /**
    * The current field to sort by. defaults to last name
    *
    */  
    public String sortField 
    {

        get  { if (sortField == null) {sortField = SaaSTextConstant.NAME_FIELD_API_NAME ; } return sortField;  }
        set;
    }
    
   /**
    * Sort List View By Column
    *
    */  
    public void sortByColumn()
    {
         sortDir = sortDir.equals(SaaSTextConstant.ASCENDING_SORT_ORDER ) ? SaaSTextConstant.DESCENDING_SORT_ORDER  :  SaaSTextConstant.ASCENDING_SORT_ORDER ;
         search();
         
    }
    
   /**
    * Get Soql For the List View
    *
    */          
    private String getSoql()
    {
        String soql = 'Select recordType.DeveloperNAme  ,Submitter__r.name,Assigned_To__r.name,Question__c,Expected_Close_Date__c, Request__r.name,Status__c,Description__c,Requested_Date__c,Id,Name FROM Question_Log__c where ';
               soql = soql +  'name like  \'%'+searchtxt+'%\'  or ';
               soql = soql +  'Assigned_To__r.name like  \'%'+searchtxt+'%\'  or ';
               soql = soql +  'Submitter__r.name like  \'%'+searchtxt+'%\'  or ';
               soql = soql +  'Status__c like \'%'+searchtxt+'%\'  Order By ' + sortField + ' ' + sortDir + ' NULLS LAST' ; 
               
        System.debug('soql-----' + soql );               
        
        return soql;  
                   
    }      
}