force-app/main/default/objects/Key_Action_Decision__c/Key_Action_Decision__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object to track action items and key decisions related to the project.</description>
    <label>Key Action/Decision</label>
    <nameField>
        <label>Key Action/Decision Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Actions/Decisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Key_Action_Decision__c/fields/Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date__c</fullName>
    <description>Completion date of Key Action/Decision</description>
    <label>Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of Key Action/Decision</description>
    <inlineHelpText>Enter a detailed desription of the Action to be completed or the Decision needed.</inlineHelpText>
    <label>Description</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Display_on_Timeline__c.field-meta.xml
<CustomField>
    <fullName>Display_on_Timeline__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display on Timeline</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>Days exceeded</description>
    <inlineHelpText>Enter the date when the Action Item must be completed or the Decision must be made. Items not completed by the Due Date pose a risk to deliverables.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Key_Action_Decision__c.field-meta.xml
<CustomField>
    <fullName>Key_Action_Decision__c</fullName>
    <description>Key Action/Decision number</description>
    <displayFormat>KAD-{00000}</displayFormat>
    <label>Key Action/Decision #</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Days to close entered in Help Text are a suggestion, and can be changed by individual projects to meet their specific needs.</description>
    <inlineHelpText>Normal Priority items should be closed within 5 business days. High Priority items should be closed within 2 business days.</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>High</fullName>
                <color>#F3D904</color>
                <label>High</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Related_Release__c.field-meta.xml
<CustomField>
    <fullName>Related_Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Release related to current  Key Action/Decision</description>
    <inlineHelpText>Select the Release that this Key Action/Decision is related to.</inlineHelpText>
    <label>Related Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Key Actions/Decisions</relationshipLabel>
    <relationshipName>Key_Actions_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of  Key Action/Decision</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#A53711</color>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#F3D904</color>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#419249</color>
                <label>Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a significant event in the project&#39;s lifespan.</description>
    <label>Milestone</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Milestone ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Actual_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_End_Date__c</fullName>
    <description>Actual date of completion of Milestone.</description>
    <label>Actual End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Actual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Date__c</fullName>
    <label>Actual Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Milestone_Name__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Name__c</fullName>
    <description>Milestone Name</description>
    <inlineHelpText>Name/Label for this milestone.</inlineHelpText>
    <label>Milestone Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Milestones__c.field-meta.xml
<CustomField>
    <fullName>Milestones__c</fullName>
    <description>Stage of Milestone.</description>
    <label>Milestone</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Preliminary Release Scope</fullName>
            </value>
            <value>
                <fullName>Requirements Definition</fullName>
            </value>
            <value>
                <fullName>Level of Effort Estimates</fullName>
            </value>
            <value>
                <fullName>Preliminary Scope Lock</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Final Scope Lock (Design Sign-off)</fullName>
            </value>
            <value>
                <fullName>Development &amp; Unit Test</fullName>
            </value>
            <value>
                <fullName>SIT</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Deploy &amp; Train</fullName>
            </value>
            <value>
                <fullName>Optimize/Maintain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Planned_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_End_Date__c</fullName>
    <description>Expected or Preplanned date of completion of Milestone.</description>
    <label>Planned End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Planned_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Start_Date__c</fullName>
    <description>Baseline Plan Dates. Initial load, and not editable except after a re-baseline</description>
    <inlineHelpText>Baseline Plan Dates. Initial load, and not editable except after a re-baseline</inlineHelpText>
    <label>Planned Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <description>Current status of Milestone</description>
    <label>Progress</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Release related to this milestone.</description>
    <inlineHelpText>Release related to this milestone.</inlineHelpText>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about Release</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Cls_MilestoneGanttChart_Test.cls
@isTest
private class Cls_MilestoneGanttChart_Test{ 
    /* Passing test data */
  static testMethod void myTestMethodreleaseidnull() { 
    string gants='test';
    string s = 'Green';
    date startdate;
    date enddate;
    
    
    string[] str = new string[] {};
    
     Release__c res = new Release__c();
        res.Name='Test';
        //res.Program__c=acctmaster2.id;
        //ph.Phase_Start_Date__c=system.today();
        //ph.Phase_End_Date__c=system.today();
        insert res;
            
                          
        Milestone__c objMile = new Milestone__c();
           objMile.Milestone_Name__c = 'TestMilestone';
           objMile.Release__c = res.Id;
           objMile.Progress__c ='In Progress'; 
           objMile.Milestones__c = 'Requirements Definition'; 
           objMile.Actual_Start_Date__c =system.now().adddays(-4).date();
           objMile.Actual_End_Date__c = system.now().adddays(-2).date();
            
           objMile.Planned_Start_Date__c = system.now().adddays(-4).date();
           objMile.Planned_End_Date__c = system.today()+7;
           
           insert objMile;  
           
         Key_Action_Decision__c key = new Key_Action_Decision__c();
          key.Name = 'Key Decision';   
          key.Priority__c = 'Normal'; 
          Key.Status__c = 'In Progress';
          key.Description__c = 'Test Description'; 
          key.Display_on_Timeline__c = true;
          key.Related_Release__c = res.Id;
          //key.Due_Date__c = system.today()+2;
          key.Completed_Date__c = system.today()+3;
          
         insert key;                                                  
       
        Test.startTest();
    
  ApexPAges.StandardController sc = new ApexPages.StandardController(objMile);
  ApexPages.CurrentPage().getparameters().put('id', res.id);

  Cls_MilestoneGanttChart testController = new Cls_MilestoneGanttChart(sc);
    
  testController.ganttJson=gants;
  testController.selectedmilestoneValues = 'Requirements Definition';
  testController.color='Green';
  testController.startdate=objMile.Planned_Start_Date__c;
  testController.enddate=objMile.Planned_End_Date__c;
  testController.getmilestoneValues();
  testController.getStatusValues();
  testController.setselectedcheckboxvalues(str);
  testController.getselectedcheckboxvalues();
  testController.searchresults();
  
  Test.stopTest();         
    }
    
  static testMethod void myTestMethodreleaseidnotnull() { 
    string gants='test';
    string color = 'Green';
    date startdate;
    date enddate;
    string selectedmilestoneValues = null;
    string[] str = new string[] {'Not Started'};
     Release__c res = new Release__c();
        res.Name='Test';
        //res.Program__c=acctmaster2.id;
        //ph.Phase_Start_Date__c=system.today();
        //ph.Phase_End_Date__c=system.today();
        insert res;
           
        Milestone__c objMile = new Milestone__c();
           objMile.Milestone_Name__c = 'TestMilestone';
           objMile.Release__c = res.Id;
           objMile.Progress__c ='In Progress'; 
           //objMile.Planned_Start_Date__c = system.now().adddays(-4).date();
           //objMile.Planned_End_Date__c = system.today()+7;
           objMile.Milestones__c = 'Requirements Definition'; 
           objMile.Planned_Start_Date__c = system.now().adddays(-4).date();
           objMile.Planned_End_Date__c = system.today()+7;
           
           insert objMile;  
           
         Key_Action_Decision__c key = new Key_Action_Decision__c();
          key.Name = 'Key Decision';   
          key.Priority__c = 'Normal'; 
          Key.Status__c = 'In Progress';
          key.Description__c = 'Test Description'; 
          key.Display_on_Timeline__c = true;
          key.Related_Release__c = res.Id;
          key.Due_Date__c = system.today()+2;
          key.Completed_Date__c = system.today()+2;
          
         insert key;                                                  
       
        Test.startTest();
    
  ApexPAges.StandardController sc = new ApexPages.StandardController(objMile);
   
  ApexPages.CurrentPage().getparameters().put('ReleaseId', res.Id);
  //ApexPages.CurrentPage().getparameters().put('Id', res.Id);
   
  Cls_MilestoneGanttChart testController = new Cls_MilestoneGanttChart(sc);
    
  testController.ganttJson=gants;
  
  testController.getmilestoneValues();
  testController.getStatusValues();
  testController.startdate=objMile.Actual_Start_Date__c;
  testController.enddate=objMile.Actual_End_Date__c;
  testController.setselectedcheckboxvalues(str);
  testController.getselectedcheckboxvalues();
  testController.searchresults();
  
  Test.stopTest();         
    }
    
    
  static testMethod void myTestMethodmilestonetypenotnull() { 
    string gants='test';
    string color = 'Green';
    date startdate;
    date enddate;
    
    
    string[] str = new string[] {'In Progress'};
     Release__c res = new Release__c();
        res.Name='Test';
        //res.Program__c=acctmaster2.id;
        //ph.Phase_Start_Date__c=system.today();
        //ph.Phase_End_Date__c=system.today();
        insert res;
           
        Milestone__c objMile = new Milestone__c();
           objMile.Milestone_Name__c = 'TestMilestone';
           objMile.Release__c = res.Id;
           objMile.Progress__c ='In Progress'; 
           //objMile.Planned_Start_Date__c = system.now().adddays(-4).date();
           //objMile.Planned_End_Date__c = system.today()+7;
           objMile.Milestones__c = 'Requirements Definition'; 
           objMile.Planned_Start_Date__c = system.now().adddays(-4).date();
           objMile.Planned_End_Date__c = system.today()+7;
           
           insert objMile;  
           
         Key_Action_Decision__c key = new Key_Action_Decision__c();
          key.Name = 'Key Decision';   
          key.Priority__c = 'Normal'; 
          Key.Status__c = 'In Progress';
          key.Description__c = 'Test Description'; 
          key.Display_on_Timeline__c = true;
          key.Related_Release__c = res.Id;
          key.Due_Date__c = system.today()+2;
          key.Completed_Date__c = system.today()+2;
          
         insert key;                                                  
       
        Test.startTest();
    
  ApexPAges.StandardController sc = new ApexPages.StandardController(objMile);
   
  ApexPages.CurrentPage().getparameters().put('ReleaseId', res.Id);
  //ApexPages.CurrentPage().getparameters().put('Id', res.Id);
   
  Cls_MilestoneGanttChart testController = new Cls_MilestoneGanttChart(sc);
    
  testController.ganttJson=gants;
  testController.selectedmilestoneValues = 'Requirements Definition';
  testController.getmilestoneValues();
  testController.getStatusValues();
  testController.startdate=objMile.Actual_Start_Date__c;
  testController.enddate=objMile.Actual_End_Date__c;
  testController.setselectedcheckboxvalues(str);
  testController.getselectedcheckboxvalues();
  testController.searchresults();
  
  Test.stopTest();         
    }  
      

}