force-app/main/default/objects/Key_Action_Decision__c/Key_Action_Decision__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object to track action items and key decisions related to the project.</description>
    <label>Key Action/Decision</label>
    <nameField>
        <label>Key Action/Decision Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Actions/Decisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Key_Action_Decision__c/fields/Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date__c</fullName>
    <description>Completion date of Key Action/Decision</description>
    <label>Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Days_Open__c.field-meta.xml
<CustomField>
    <fullName>Days_Open__c</fullName>
    <description>Number of days Key Action/Decision remained open</description>
    <formula>IF(NOT(ISPICKVAL(Status__c, &quot;Completed&quot;)), NOW() - CreatedDate,  Completed_Date__c - (DATEVALUE(CreatedDate)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Open</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Key_Action_Decision__c.field-meta.xml
<CustomField>
    <fullName>Key_Action_Decision__c</fullName>
    <description>Key Action/Decision number</description>
    <displayFormat>KAD-{00000}</displayFormat>
    <label>Key Action/Decision #</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of  Key Action/Decision</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#A53711</color>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#F3D904</color>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#419249</color>
                <label>Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a significant event in the project&#39;s lifespan.</description>
    <label>Milestone</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Milestone ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Actual_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_End_Date__c</fullName>
    <description>Actual date of completion of Milestone.</description>
    <label>Actual End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Actual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Date__c</fullName>
    <label>Actual Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Asset_Initiative_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Asset_Initiative_Milestone__c</fullName>
    <description>Milestone for an Asset or a Initiative.</description>
    <inlineHelpText>Milestone for an Asset or a Initiative.</inlineHelpText>
    <label>Asset/Initiative Milestone</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Gain Stakeholder Buy-in</fullName>
            </value>
            <value>
                <fullName>Gather Requirements/ Define Scope</fullName>
            </value>
            <value>
                <fullName>Design/Draft</fullName>
            </value>
            <value>
                <fullName>Build/Develop Final Content</fullName>
            </value>
            <value>
                <fullName>Test/Validate</fullName>
            </value>
            <value>
                <fullName>Deploy/Publish</fullName>
            </value>
            <value>
                <fullName>Optimize/Maintain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <formula>if((Planned_End_Date__c &lt; TODAY()) &amp;&amp; ( VALUE ( TEXT (Complete2__c ) ) &lt;&gt; 100), &quot;Red&quot;,
 

if((Planned_End_Date__c &lt;= TODAY()+5) &amp;&amp; ( VALUE ( TEXT (Complete2__c ) ) &lt;&gt; 100), &quot;Yellow&quot;,
 

&quot;Green&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Color</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Comments or additional information about Milestone.</description>
    <inlineHelpText>Use this comment box to indicate the variance between milestone dates. (e.g. Holidays)</inlineHelpText>
    <label>Comments</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Complete2__c.field-meta.xml
<CustomField>
    <fullName>Complete2__c</fullName>
    <label>% Complete</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Milestone_Id__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Id__c</fullName>
    <description>Milestone Id to distinguish a milestone for an Asset/Initiative.</description>
    <displayFormat>{000}</displayFormat>
    <inlineHelpText>Milestone Id to distinguish a milestone for an Asset/Initiative.</inlineHelpText>
    <label>Milestone Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Milestone_Name__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Name__c</fullName>
    <description>Milestone Name</description>
    <inlineHelpText>Name/Label for this milestone.</inlineHelpText>
    <label>Milestone Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Milestones__c.field-meta.xml
<CustomField>
    <fullName>Milestones__c</fullName>
    <description>Stage of Milestone.</description>
    <label>Milestone</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Preliminary Release Scope</fullName>
            </value>
            <value>
                <fullName>Requirements Definition</fullName>
            </value>
            <value>
                <fullName>Level of Effort Estimates</fullName>
            </value>
            <value>
                <fullName>Preliminary Scope Lock</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Final Scope Lock (Design Sign-off)</fullName>
            </value>
            <value>
                <fullName>Development &amp; Unit Test</fullName>
            </value>
            <value>
                <fullName>SIT</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Deploy &amp; Train</fullName>
            </value>
            <value>
                <fullName>Optimize/Maintain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/On_Target__c.field-meta.xml
<CustomField>
    <fullName>On_Target__c</fullName>
    <description>Displays a status as red, green or yellow ball.</description>
    <formula>if((Planned_End_Date__c &lt; TODAY()) &amp;&amp; ( VALUE ( TEXT (Complete2__c ) ) &lt;&gt; 100), IMAGE(&quot;/img/samples/light_red.gif&quot;, &quot;Red&quot;),
 

if((Planned_End_Date__c &lt;= TODAY()+5) &amp;&amp; ( VALUE ( TEXT (Complete2__c ) ) &lt;&gt; 100), IMAGE(&quot;/img/samples/light_yellow.gif&quot;, &quot;Yellow&quot;),
 

IMAGE(&quot;/img/samples/light_green.gif&quot;, &quot;Green&quot;)))</formula>
    <label>On Target</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Owner of this Milestone</description>
    <inlineHelpText>Owner of this Milestone</inlineHelpText>
    <label>Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Planned_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_End_Date__c</fullName>
    <description>Expected or Preplanned date of completion of Milestone.</description>
    <label>Planned End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Planned_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Start_Date__c</fullName>
    <description>Baseline Plan Dates. Initial load, and not editable except after a re-baseline</description>
    <inlineHelpText>Baseline Plan Dates. Initial load, and not editable except after a re-baseline</inlineHelpText>
    <label>Planned Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <description>Current status of Milestone</description>
    <label>Progress</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Release related to this milestone.</description>
    <inlineHelpText>Release related to this milestone.</inlineHelpText>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Owner of this release.</description>
    <inlineHelpText>Owner of this release.</inlineHelpText>
    <label>Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Releases</relationshipLabel>
    <relationshipName>Releases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Use_Case__c/Use_Case__c.object-meta.xml
<CustomObject>
    <label>Use Case</label>
    <nameField>
        <displayFormat>UC-{000000}</displayFormat>
        <label>Use Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Use Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Use_Case__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Use Cases</relationshipLabel>
    <relationshipName>Use_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Cls_MilestoneGanttChart.cls
public with sharing class Cls_MilestoneGanttChart {

    public string ganttJson {get;set;}
    public string color{get;set;}
    public date startdate{get;set;}
    public date enddate{get;set;}
    public List<SelectOption> myList{get; set;}
    //public string selectedcheckboxstatusvalues{get;set;}
    public string selectedmilestoneValues{get;set;}
    //public string strStatus;
    public boolean noflag{get;set;}
    public boolean searchflag{get;set;}
    
    public List<Milestone__c> taskList{get;set;}
    //public String query{get;set;}
    
    set<string> setstring = new set<string>();
    string recordid = ApexPages.currentPage().getParameters().get('ReleaseId');
    // String selectedmilestonevalue = ApexPages.currentPage().getParameters().get('selectedmilestone');
        // String selectedstatusvalue = ApexPages.currentPage().getParameters().get('selectedstatus');
    
    //public string theSite{get;set;}


    
    public List<Key_Action_Decision__c> keydecisionList{get;set;}
    //List<sObject> milestoneandkeydecisionlist {get;set;} 
    
    
    String[] selectedcheckboxvalues = new String[]{};
    
    //public string recordid{get;set;}

    
    public String[] getselectedcheckboxvalues() {
         
        return selectedcheckboxvalues;
    }
    
    public void setselectedcheckboxvalues(String[] selectedcheckboxvalues) {
        this.selectedcheckboxvalues= selectedcheckboxvalues;
    }
    
    public Cls_MilestoneGanttChart(ApexPages.StandardController controller) {
         noflag = false;
         searchflag = false;
         //recordid = controller.getRecord().Id;
         recordid = ApexPages.currentPage().getParameters().get('ReleaseId');
         String selectedmilestonevalue = ApexPages.currentPage().getParameters().get('selectedmilestone');
         String selectedstatusvalue = ApexPages.currentPage().getParameters().get('selectedstatus');
         
        //string theSite = ApexPages.CurrentPage().getParameters().get('site');
            
        //system.debug('selectedstatusvalue123456 --> '+ theSite);
        if(ApexPages.CurrentPage().getParameters().get('ReleaseId') == null) {
            taskList = [Select Id, Name, Actual_Start_Date__c, Actual_End_Date__c,Planned_Start_Date__c,Planned_End_Date__c,Milestone_Name__c,
                        Asset_Initiative_Milestone__c,Comments__c,Milestones__c,Milestone_Id__c,On_Target__c,Owner__c,
                        Progress__c,Release__c,Release__r.Name,Status__c,Complete2__c,Color__c,Owner.Name
                        From Milestone__c Where Release__c =: controller.getRecord().Id order by Actual_Start_Date__c,Planned_Start_Date__c ASC ]; 
           
           keydecisionList  = [select Id,Name,RecordTypeId,Completed_Date__c,Days_Open__c,Decision_Outcome__c,Description__c,Due_Date__c,Key_Action_Decision__c,Options__c,
                               Priority__c,Related_Capability__c,Related_Issue_Risk__c,Related_Key_Action_Decision__c,Related_Question_Log__c,Related_Release__c,Owner.Name,
                               Related_Request__c,SOURCE_ID__c,Status__c,Use_Case__c from Key_Action_Decision__c where Display_on_Timeline__c = true and Related_Release__c =: controller.getRecord().Id order by Completed_Date__c ASC];               

       } else {
          
                taskList = [Select Id, Name, Actual_Start_Date__c, Actual_End_Date__c,Planned_Start_Date__c,Planned_End_Date__c,Milestone_Name__c,
                            Asset_Initiative_Milestone__c,Comments__c,Milestones__c,Milestone_Id__c,On_Target__c,Owner__c,
                            Progress__c,Release__c,Release__r.Name,Status__c,Complete2__c,Color__c,Owner.Name
                            From Milestone__c Where Release__c =: ApexPages.CurrentPage().getParameters().get('ReleaseId') 
                            order by Actual_Start_Date__c,Planned_Start_Date__c ASC];

             keydecisionList  = [select Id,Name,RecordTypeId,Completed_Date__c,Days_Open__c,Decision_Outcome__c,Description__c,Due_Date__c,Key_Action_Decision__c,Options__c,
                               Priority__c,Related_Capability__c,Related_Issue_Risk__c,Related_Key_Action_Decision__c,Related_Question_Log__c,Related_Release__c,Owner.Name,
                               Related_Request__c,SOURCE_ID__c,Status__c,Use_Case__c from Key_Action_Decision__c where Display_on_Timeline__c = true and Related_Release__c =: ApexPages.CurrentPage().getParameters().get('ReleaseId') order by Completed_Date__c ASC];             
            
        } 
        
            List<sObject> milestoneandkeydecisionlist = new List<sObject>();
            
            milestoneandkeydecisionlist.addAll((List<sObject>)(taskList));
            milestoneandkeydecisionlist.addAll((List<sObject>)(keydecisionList));
        
       
    
        for(Milestone__c taskRec : taskList) {
           
            color = taskRec.Color__c;
            system.debug('color-->' + color );
            
            if(taskRec.Actual_Start_Date__c != null){
                startdate = taskRec.Actual_Start_Date__c;
                } else{
                startdate = taskRec.Planned_Start_Date__c;
                }
                
             if(taskRec.Actual_End_Date__c!= null){
                enddate= taskRec.Actual_End_Date__c;
                } else{
                enddate= taskRec.Planned_End_Date__c;
                }
            
            if(taskRec.Milestone_Name__c== taskRec.Milestone_Name__c) {
                if(string.isBlank(ganttJson)) {
                    ganttJson = '[{"values":[{"customClass":"Milestone: '+taskRec.Milestone_Name__c+'<br/>Planned Start Date: '+startdate.format()+'<br/>Planned End Date: '+enddate.format()+'<br/>Progress: '+taskRec.Progress__c+'<br/>Owner: '+taskRec.Owner.Name+'","from":"'+startdate.format()+'","label":"'+taskRec.Id+'","color":"'+taskRec.Color__c+'","to":"'+enddate.format()+'","id":"'+taskRec.Id+
                                '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec.Milestone_Name__c+'","startDate":"'+startdate.format()+'","endDate":"'+enddate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';
                }
                else {
                    ganttJson = ganttJson+',{"values":[{"customClass":"Milestone: '+taskRec.Milestone_Name__c+'<br/>Planned Start Date: '+startdate.format()+'<br/>Planned End Date: '+enddate.format()+'<br/>Progress: '+taskRec.Progress__c+'<br/>Owner: '+taskRec.Owner.Name+'","from":"'+startdate.format()+'","label":"'+taskRec.Id+'","color":"'+taskRec.Color__c+'","to":"'+enddate.format()+'","id":"'+taskRec.Id+
                                '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec.Milestone_Name__c+'","startDate":"'+startdate.format()+'","endDate":"'+enddate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';
                }
            }
            /*else {
                if(string.isBlank(ganttJson)) {
                    ganttJson = '[{"values":[{"customClass":"Milestone: '+taskRec.Milestone_Name__c+'<br/>Planned Start Date: '+startdate.format()+'<br/>Planned End Date: '+enddate.format()+'<br/>Progress: '+taskRec.Progress__c+'<br/>Owner: '+taskRec.Owner.Name+'","from":"'+startdate.format()+'","label":"'+taskRec.Id+'","color":"'+taskRec.Color__c+'","to":"'+enddate.format()+'","id":"'+taskRec.Id+
                                 '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec.Milestone_Name__c+'","startDate":"'+startdate.format()+'","endDate":"'+enddate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';       
                }
                else {
                    ganttJson = ganttJson+',{"values":[{"customClass":"Milestone: '+taskRec.Milestone_Name__c+'<br/>Planned Start Date: '+startdate.format()+'<br/>Planned End Date: '+enddate.format()+'<br/>Progress: '+taskRec.Progress__c+'<br/>Owner: '+taskRec.Owner.Name+'","from":"'+startdate.format()+'","label":"'+taskRec.Id+'","color":"'+taskRec.Color__c+'","to":"'+enddate.format()+'","id":"'+taskRec.Id+
                                  '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec.Milestone_Name__c+'","startDate":"'+startdate.format()+'","endDate":"'+enddate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';      
                }
                
            } */
        }
        
        
        // for key decision 
            
            for(Key_Action_Decision__c taskRec1 : keydecisionList) {

            if(taskRec1.Due_Date__c!= null){
                    startdate = taskRec1.Due_Date__c;
                } else {
                    startdate = taskRec1.Completed_Date__c;
                 }   
                
              
             
            if(taskRec1.Name== taskRec1.Name) {
                if(string.isBlank(ganttJson)) {
                    ganttJson = '[{"values":[{"customClass":"KeyDecision: '+taskRec1.Name+'<br/>Description: '+taskRec1.Description__c+'<br/>Status: '+taskRec1.Status__c+'<br/>Due Date: '+startdate.format()+'<br/>Owner: '+taskRec1.Owner.Name+'","from":"'+startdate.format()+'","label":"'+taskRec1.Id+'","to":"'+startdate.format()+'","id":"'+taskRec1.Id+
                                '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec1.Name+'","startDate":"'+startdate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';
                }
                else {
                    ganttJson = ganttJson+',{"values":[{"customClass":"KeyDecision: '+taskRec1.Name+'<br/>Description: '+taskRec1.Description__c+'<br/>Status: '+taskRec1.Status__c+'<br/>Due Date: '+startdate.format()+'<br/>Owner: '+taskRec1.Owner.Name+'","from":"'+startdate.format()+'","label":"'+taskRec1.Id+'","to":"'+startdate.format()+'","id":"'+taskRec1.Id+
                                '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec1.Name+'","startDate":"'+startdate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';
                }
            }
           /* else {
                if(string.isBlank(ganttJson)) {
                    ganttJson = '[{"values":[{"customClass":"KeyDecision: '+taskRec1.Name+'<br/>Description: '+taskRec1.Description__c+'<br/>Status: '+taskRec1.Status__c+'<br/>Due Date: '+startdate.format()+'<br/>Owner: '+taskRec1.Owner.Name+'","label":"'+taskRec1.Id+'","id":"'+taskRec1.Id+
                                '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec1.Name+'","startDate":"'+startdate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';      
                }
                else {
                    ganttJson = ganttJson+',{"values":[{"customClass":"KeyDecision: '+taskRec1.Name+'<br/>Description: '+taskRec1.Description__c+'<br/>Status: '+taskRec1.Status__c+'<br/>Due Date: '+startdate.format()+'<br/>Owner: '+taskRec1.Owner.Name+'","label":"'+taskRec1.Id+'","id":"'+taskRec1.Id+
                                '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec1.Name+'","startDate":"'+startdate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';      
                }
                
            } */
        }
        
        system.debug('ganttJson 123  -->' + ganttJson);
        
         if(ganttJson == null || ganttJson == ']'){
           ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'No Milestones and keydecision records are for this search Criteria.'));
           noflag = true;
        } 
       
        //ganttJson.sort();        
        ganttJson = ganttJson + ']';
        system.debug('ganttJson -->' + ganttJson);

    }
    
    public PageReference searchresults(){
          
         noflag = false;
         searchflag = false;
        ganttJson = '';
        system.debug('ganttJson123-->' + ganttJson);
        //string theSite = ApexPages.CurrentPage().getParameters().get('site');
        
        //system.debug('helloo...21 >' + theSite);
        recordid = ApexPages.currentPage().getParameters().get('ReleaseId');
      
        integer count = selectedcheckboxvalues.size();
        system.debug('helloo...count' + count);
             
        system.debug('helloo...'+selectedcheckboxvalues);
        //strStatus='(\'';
        setstring.clear();
        for(integer i=0;i<count;i++){
        system.debug('helloo...inside');
        setstring.add(selectedcheckboxvalues[i]);
        }
        system.debug('helloo...');
        system.debug('selectedmilestoneValues --> ' + selectedmilestoneValues);
        system.debug('selectedcheckboxvalues--> ' + setstring);
            if(selectedmilestoneValues !=null && count > 0) {
                    taskList = [Select Id, Name, Actual_Start_Date__c, Actual_End_Date__c,Planned_Start_Date__c,Planned_End_Date__c,Milestone_Name__c,
                                    Asset_Initiative_Milestone__c,Comments__c,Milestones__c,Milestone_Id__c,On_Target__c,Owner__c,
                                    Progress__c,Release__c,Release__r.Name,Status__c,Complete2__c,Color__c,Owner.Name
                                    From Milestone__c Where Release__c =:recordid 
                                    and Milestones__c=:selectedmilestoneValues 
                                    and Progress__c  In :setstring
                                    order by Actual_Start_Date__c,Planned_Start_Date__c ASC];
               } else if(selectedmilestoneValues == null && count == 0) {
                    taskList = [Select Id, Name, Actual_Start_Date__c, Actual_End_Date__c,Planned_Start_Date__c,Planned_End_Date__c,Milestone_Name__c,
                            Asset_Initiative_Milestone__c,Comments__c,Milestones__c,Milestone_Id__c,On_Target__c,Owner__c,
                            Progress__c,Release__c,Release__r.Name,Status__c,Complete2__c,Color__c,Owner.Name
                            From Milestone__c Where Release__c =:recordid];
                           
                       // order by Actual_Start_Date__c,Planned_Start_Date__c ASC];
             }  else if(selectedmilestoneValues != null && count == 0) {
                    taskList = [Select Id, Name, Actual_Start_Date__c, Actual_End_Date__c,Planned_Start_Date__c,Planned_End_Date__c,Milestone_Name__c,
                            Asset_Initiative_Milestone__c,Comments__c,Milestones__c,Milestone_Id__c,On_Target__c,Owner__c,
                            Progress__c,Release__c,Release__r.Name,Status__c,Complete2__c,Color__c,Owner.Name
                            From Milestone__c Where Release__c =:recordid and Milestones__c=:selectedmilestoneValues];
             }  else if(selectedmilestoneValues == null && count > 0) {
                    taskList = [Select Id, Name, Actual_Start_Date__c, Actual_End_Date__c,Planned_Start_Date__c,Planned_End_Date__c,Milestone_Name__c,
                            Asset_Initiative_Milestone__c,Comments__c,Milestones__c,Milestone_Id__c,On_Target__c,Owner__c,
                            Progress__c,Release__c,Release__r.Name,Status__c,Complete2__c,Color__c,Owner.Name
                            From Milestone__c Where Release__c =:recordid and Progress__c  IN :setstring];
             }  
             
             
                       
  
         keydecisionList  = [select Id,Name,RecordTypeId,Completed_Date__c,Days_Open__c,Decision_Outcome__c,Description__c,Due_Date__c,Key_Action_Decision__c,Options__c,
                               Priority__c,Related_Capability__c,Related_Issue_Risk__c,Related_Key_Action_Decision__c,Related_Question_Log__c,Related_Release__c,Owner.Name,
                               Related_Request__c,SOURCE_ID__c,Status__c,Use_Case__c from Key_Action_Decision__c where Display_on_Timeline__c = true and Related_Release__c =:recordid order by Completed_Date__c ASC];               
                     
          
       system.debug('recordid-->' + recordid); 
       system.debug('taskList-->' + taskList);
       system.debug('keydecisionList -->' + keydecisionList );
        
            List<sObject> milestoneandkeydecisionlist = new List<sObject>();
            
            milestoneandkeydecisionlist.addAll((List<sObject>)(taskList));
            milestoneandkeydecisionlist.addAll((List<sObject>)(keydecisionList));
        
       
    
        for(Milestone__c taskRec : taskList) {
            
            color = taskRec.Color__c;
            system.debug('color-->' + color );
            
            if(taskRec.Actual_Start_Date__c != null){
                startdate = taskRec.Actual_Start_Date__c;
                } else{
                startdate = taskRec.Planned_Start_Date__c;
                }
                
             if(taskRec.Actual_End_Date__c!= null){
                enddate= taskRec.Actual_End_Date__c;
                } else{
                enddate= taskRec.Planned_End_Date__c;
                }
            
            if(taskRec.Milestone_Name__c== taskRec.Milestone_Name__c) {
                if(string.isBlank(ganttJson)) {
                    ganttJson = '[{"values":[{"customClass":"Milestone: '+taskRec.Milestone_Name__c+'<br/>Planned Start Date: '+startdate.format()+'<br/>Planned End Date: '+enddate.format()+'<br/>Progress: '+taskRec.Progress__c+'<br/>Owner: '+taskRec.Owner.Name+'","from":"'+startdate.format()+'","label":"'+taskRec.Id+'","color":"'+taskRec.Color__c+'","to":"'+enddate.format()+'","id":"'+taskRec.Id+
                                '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec.Milestone_Name__c+'","startDate":"'+startdate.format()+'","endDate":"'+enddate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';
                }
                else {
                    ganttJson = ganttJson+',{"values":[{"customClass":"Milestone: '+taskRec.Milestone_Name__c+'<br/>Planned Start Date: '+startdate.format()+'<br/>Planned End Date: '+enddate.format()+'<br/>Progress: '+taskRec.Progress__c+'<br/>Owner: '+taskRec.Owner.Name+'","from":"'+startdate.format()+'","label":"'+taskRec.Id+'","color":"'+taskRec.Color__c+'","to":"'+enddate.format()+'","id":"'+taskRec.Id+
                                '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec.Milestone_Name__c+'","startDate":"'+startdate.format()+'","endDate":"'+enddate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';
                }
            }
           /* else {
                if(string.isBlank(ganttJson)) {
                    ganttJson = '[{"values":[{"customClass":"Milestone: '+taskRec.Milestone_Name__c+'<br/>Planned Start Date: '+startdate.format()+'<br/>Planned End Date: '+enddate.format()+'<br/>Progress: '+taskRec.Progress__c+'<br/>Owner: '+taskRec.Owner.Name+'","from":"'+startdate.format()+'","label":"'+taskRec.Id+'","color":"'+taskRec.Color__c+'","to":"'+enddate.format()+'","id":"'+taskRec.Id+
                                 '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec.Milestone_Name__c+'","startDate":"'+startdate.format()+'","endDate":"'+enddate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';       
                }
                else {
                    ganttJson = ganttJson+',{"values":[{"customClass":"Milestone: '+taskRec.Milestone_Name__c+'<br/>Planned Start Date: '+startdate.format()+'<br/>Planned End Date: '+enddate.format()+'<br/>Progress: '+taskRec.Progress__c+'<br/>Owner: '+taskRec.Owner.Name+'","from":"'+startdate.format()+'","label":"'+taskRec.Id+'","color":"'+taskRec.Color__c+'","to":"'+enddate.format()+'","id":"'+taskRec.Id+
                                  '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec.Milestone_Name__c+'","startDate":"'+startdate.format()+'","endDate":"'+enddate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';      
                }
                
            } */
        }
        
        
        // for key decision 
            
            for(Key_Action_Decision__c taskRec1 : keydecisionList) {

            if(taskRec1.Due_Date__c!= null){
                    startdate = taskRec1.Due_Date__c;
                } else {
                    startdate = taskRec1.Completed_Date__c;
                 }   
                
              
             
            if(taskRec1.Name== taskRec1.Name) {
                if(string.isBlank(ganttJson)) {
                    ganttJson = '[{"values":[{"customClass":"KeyDecision: '+taskRec1.Name+'<br/>Description: '+taskRec1.Description__c+'<br/>Status: '+taskRec1.Status__c+'<br/>Due Date: '+startdate.format()+'<br/>Owner: '+taskRec1.Owner.Name+'","from":"'+startdate.format()+'","label":"'+taskRec1.Id+'","to":"'+startdate.format()+'","id":"'+taskRec1.Id+
                                '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec1.Name+'","startDate":"'+startdate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';
                }
                else {
                    ganttJson = ganttJson+',{"values":[{"customClass":"KeyDecision: '+taskRec1.Name+'<br/>Description: '+taskRec1.Description__c+'<br/>Status: '+taskRec1.Status__c+'<br/>Due Date: '+startdate.format()+'<br/>Owner: '+taskRec1.Owner.Name+'","from":"'+startdate.format()+'","label":"'+taskRec1.Id+'","to":"'+startdate.format()+'","id":"'+taskRec1.Id+
                                '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec1.Name+'","startDate":"'+startdate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';
                }
            }
          /*  else {
                if(string.isBlank(ganttJson)) {
                    ganttJson = '[{"values":[{"customClass":"KeyDecision: '+taskRec1.Name+'<br/>Description: '+taskRec1.Description__c+'<br/>Status: '+taskRec1.Status__c+'<br/>Due Date: '+startdate.format()+'<br/>Owner: '+taskRec1.Owner.Name+'","label":"'+taskRec1.Id+'","id":"'+taskRec1.Id+
                                '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec1.Name+'","startDate":"'+startdate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';      
                }
                else {
                    ganttJson = ganttJson+',{"values":[{"customClass":"KeyDecision: '+taskRec1.Name+'<br/>Description: '+taskRec1.Description__c+'<br/>Status: '+taskRec1.Status__c+'<br/>Due Date: '+startdate.format()+'<br/>Owner: '+taskRec1.Owner.Name+'","label":"'+taskRec1.Id+'","id":"'+taskRec1.Id+
                                '"}],"scale":"hours","itemsPerPage":"11","navigate":"scroll","name":"'+taskRec1.Name+'","startDate":"'+startdate.format()+'","fullScreen":"'+(ApexPages.CurrentPage().getParameters().get('ReleaseId')!=null ? 'true' : 'false')+'"}';      
                }
                
            } */
        }
        
        
        ganttJson = ganttJson + ']';
        
          
         if(ganttJson == null || ganttJson == ']'){
           //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'No Milestones and keydecision records are for this search Criteria.'));
           searchflag = true;
        } 
        system.debug('ganttJson -->' + ganttJson);
    return null;
    }
    
    
    public List<SelectOption> getStatusValues(){
        myList =new List<SelectOption>();
      
        Schema.DescribeFieldResult f = Milestone__c.Progress__c.getDescribe();
            List<Schema.PicklistEntry> p = f.getPicklistValues();
               for(Schema.PicklistEntry e:p){
                    myList.add(new SelectOption(e.getLabel(),e.getValue()));
                                       
            }
            return myList;
    }
    
     public List<SelectOption> getmilestoneValues(){
        myList =new List<SelectOption>();
        myList.add(new selectOption('', '--- None ---')); 
        Schema.DescribeFieldResult f = Milestone__c.Milestones__c.getDescribe();
            List<Schema.PicklistEntry> p = f.getPicklistValues();
               for(Schema.PicklistEntry e:p){
                    myList.add(new SelectOption(e.getLabel(),e.getValue()));
                                       
            }
            return myList;
    }
}