force-app/main/default/objects/Key_Action_Decision__c/Key_Action_Decision__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object to track action items and key decisions related to the project.</description>
    <label>Key Action/Decision</label>
    <nameField>
        <label>Key Action/Decision Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Actions/Decisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Key_Action_Decision__c/fields/Decision_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Decision_Outcome__c</fullName>
    <description>Description of outcome of Key Action/Decision</description>
    <inlineHelpText>Enter details of the outcome of the action item (what was determined) or the decision reached (what was agreed to, which option was selected). This field is required when Status is Completed.</inlineHelpText>
    <label>Decision/Outcome</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of Key Action/Decision</description>
    <inlineHelpText>Enter a detailed desription of the Action to be completed or the Decision needed.</inlineHelpText>
    <label>Description</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>Days exceeded</description>
    <inlineHelpText>Enter the date when the Action Item must be completed or the Decision must be made. Items not completed by the Due Date pose a risk to deliverables.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Key_Action_Decision__c.field-meta.xml
<CustomField>
    <fullName>Key_Action_Decision__c</fullName>
    <description>Key Action/Decision number</description>
    <displayFormat>KAD-{00000}</displayFormat>
    <label>Key Action/Decision #</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <description>Details of options which are under evaluation</description>
    <inlineHelpText>Enter the options under evaluation.</inlineHelpText>
    <label>Options</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Days to close entered in Help Text are a suggestion, and can be changed by individual projects to meet their specific needs.</description>
    <inlineHelpText>Normal Priority items should be closed within 5 business days. High Priority items should be closed within 2 business days.</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>High</fullName>
                <color>#F3D904</color>
                <label>High</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of  Key Action/Decision</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#A53711</color>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#F3D904</color>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#419249</color>
                <label>Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Key_Action_Decision__c/recordTypes/Action_Item.recordType-meta.xml
<RecordType>
    <fullName>Action_Item</fullName>
    <active>true</active>
    <description>Used to document Action Items that need to be completed by resources on the Program/Project.</description>
    <label>Action Item</label>
</RecordType>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about Release</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Plan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Start_Date__c</fullName>
    <description>Estimated date of Start</description>
    <label>Plan Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release_Planned_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Planned_End_Date__c</fullName>
    <description>Estimated date of end of release</description>
    <label>Release Planned End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status_Update__c.field-meta.xml
<CustomField>
    <fullName>Status_Update__c</fullName>
    <description>Release status update</description>
    <inlineHelpText>Release status update</inlineHelpText>
    <label>Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SaaSCreateKeyDecisionOrActionCtrlTest.cls
@isTest
/** 
 *  Author : Accenture 
 *  Description : Test Class for Controller class for SaaSCreateKeyDecisionOrActionCtrl
 *  Created Date : 05\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  09\06\2015        created 
 *
 */
  public class SaaSCreateKeyDecisionOrActionCtrlTest
{
    static testMethod void validateCreatekeyActionDecision() 
    {
        Key_Action_Decision__c key = new Key_Action_Decision__c();
        key.Name = 'Test Clone';
        key.Priority__c = 'High';
        key.Due_Date__c = System.today() + 10;
        //key.RecordType.Name= 'Action Item';
        key.Status__c = 'Completed';
        key.Description__c = 'Test description ';
        key.Decision_Outcome__c= 'Test Comments';
        insert key;    
        Release__c rel = new Release__c();
        List<Release__c> relLst = new List<Release__c>();
        relLst.add(rel);
        
        SaaSCreateKeyDecisionOrActionCtrl controller = new SaaSCreateKeyDecisionOrActionCtrl(new ApexPages.StandardController(key));
        controller.actionOrDecisionType = 'Action_Item';
        controller.disbaleRecordType();
        controller.getRecordType();
       
       // controller.validateKeyDecision();
        controller.saveKeyDecision();
        controller.keyDecisionObj.name =  null;
        controller.saveKeyDecision();
        controller.keyDecisionObj.name =  'Test name';
        controller.keyDecisionObj.Status__c = null;
        controller.saveKeyDecision();
        controller.keyDecisionObj.Status__c = 'Status';        
        controller.keyDecisionObj.Priority__c = null;        
        controller.saveKeyDecision();
        controller.keyDecisionObj.Priority__c = 'p21';        
        controller.keyDecisionObj.Description__c = '';
        controller.saveKeyDecision();
        controller.keyDecisionObj.Description__c = 'desc';
        controller.DueDate  = null;
        controller.saveKeyDecision();    
        controller.DueDate  = System.today();
        controller.saveKeyDecision();
        controller.KeyDecisionObj.Options__c = null;
        controller.saveKeyDecision();
        controller.KeyDecisionObj.Options__c = 'options'; 
        controller.saveKeyDecision();   
        controller.createActionOrDecision();
    }    
    
     static testMethod void validateCreatekeyActionDecision1() 
     {
         Key_Action_Decision__c key = new Key_Action_Decision__c();
         SaaSCreateKeyDecisionOrActionCtrl controller = new SaaSCreateKeyDecisionOrActionCtrl(new ApexPages.StandardController(key));
         controller.saveKeyDecision();
         controller.createActionOrDecision();     
     } 
     
       
     static testMethod void validatekeyActionDecisionClone() 
    {
         Release__c rel = new Release__c();
         rel.Name = 'Test Release ';
         rel.Release__c = 24;
         rel.Plan_Start_Date__c = System.today();
         rel.Release_Planned_End_Date__c= System.today() + 10;
         rel.Status__c = 'Red';
         rel.Description__c = 'Test description ';
         rel.Status_Update__c = 'Test Comments';
         insert rel;
         Key_Action_Decision__c key = SaaSTestUtility.createKeyAction(); 
         PageReference pageRef = page.SaaSCreateKeyDecisionOrAction;
         pageRef.getParameters().put(SaaSTextConstant.IS_CLONE_URL_PARAM, '1');
         pageRef.getParameters().put(SaaSTextConstant.RELEASEID_URL_PARAM,rel.id);
         Test.setCurrentPage(pageRef);
         SaaSCreateKeyDecisionOrActionCtrl controller = new SaaSCreateKeyDecisionOrActionCtrl(new ApexPages.StandardController(key));
         controller.saveKeyDecision();
    }    


}