force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <description>This Object is to capture the exception detail occurred in any apex code</description>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Name of the class where exception occured</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Exception detail</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>Name of the method where exception occured</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NS_Utility.cls
public without sharing class NS_Utility {
    
    public static void databaseSvResult(List<Database.SaveResult> srList, String methodNm, String classNm)
    {
        List<Exception__c> expList = new List<Exception__c>();
       
        for (Database.SaveResult sr : srList) {
            if (!sr.isSuccess()) {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('The following error has occurred.'); 
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Fields that affected this error: ' + err.getFields());
                    Exception__c excep = new Exception__c();
                    excep.Class_Name__c = classNm;
                    excep.Method_Name__c = methodNm;
                    //excep.Description__c = err.getStatusCode()+' : '+err.getMessage();
                    expList.add(excep);
                }
            } 
        }
        try{
            if(!expList.isEmpty()){
                insert expList;
            }    
        }
        catch(exception exp){
            system.debug('Error in Exception insertion for '+classNm +', '+methodNm+': '+exp.getMessage()) ;
        }
    }
    
    public static void databaseDelResult(List<Database.DeleteResult > srList, String methodNm, String classNm)
    {
        List<Exception__c> expList = new List<Exception__c>();
       
        for (Database.DeleteResult sr : srList) {
            if (!sr.isSuccess()) {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('The following error has occurred.'); 
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Fields that affected this error: ' + err.getFields());
                    Exception__c excep = new Exception__c();
                    excep.Class_Name__c = classNm;
                    excep.Method_Name__c = methodNm;
                    excep.Description__c = err.getStatusCode()+' : '+err.getMessage();
                    expList.add(excep);
                }
            } 
        }
        try{
            if(!expList.isEmpty()){
                insert expList;
            }    
        }
        catch(exception exp){
            system.debug('Error in Exception insertion for '+classNm +', '+methodNm+': '+exp.getMessage()) ;
        }
    }
}