force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <description>This Object is to capture the exception detail occurred in any apex code</description>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Name of the class where exception occured</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Exception detail</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>Name of the method where exception occured</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NS_ExceptionDeleteScheduler.cls
public class NS_ExceptionDeleteScheduler Implements Schedulable {
     public void execute(SchedulableContext sc){
         List<Exception__c> monthOldExps = [SELECT Id FROM Exception__c where CreatedDate > LAST_N_DAYS:31 ];
         Database.DeleteResult[] delExps = Database.delete(monthOldExps,false);
         List<Exception__c> expList = new List<Exception__c>();
         for(Database.DeleteResult dr : delExps) {
            if(!dr.isSuccess()) {
                Exception__c excep = new Exception__c();
            	for(Database.Error err : dr.getErrors()) {
                    excep.Class_Name__c = 'NS_ExceptionDeleteScheduler';
                    excep.Method_Name__c = 'execute';
                    excep.Description__c = err.getStatusCode()+' : '+err.getMessage();
                    expList.add(excep);
                    break;
                }
            }
        }
        try{
            if(!expList.isEmpty()){
                insert expList;
            }    
        }
        catch(exception exp){
            system.debug('Error in Exception insertion for NS_ExceptionDeleteScheduler') ;
        }
     }
}