force-app/main/default/objects/NS_Partnership__c/NS_Partnership__c.object-meta.xml
<CustomObject>
    <description>It is a Partner object for Account</description>
    <label>Authorized Company</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorized Companies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Partnership__c/fields/NS_CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>NS_CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>It indicates who is the Customer that is related to this partner</description>
    <inlineHelpText>Who is the Customer that this Partner is related to?</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Customer Account can only be of Type Corporate,Service,Business or Offline Customer</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business, Corporate, Service, Offline Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Authorized Companies</relationshipLabel>
    <relationshipName>NS_Partnerships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_Partnership__c/fields/NS_PartnerAccount__c.field-meta.xml
<CustomField>
    <fullName>NS_PartnerAccount__c</fullName>
    <description>It indicates who is the partner that this customer account is related to.</description>
    <inlineHelpText>Who is the Partner (3PL, Contractor, Vendor, etc) that this Customer is related to?</inlineHelpText>
    <label>Authorized Company</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Partner Account can only be of Type 3PL,Other Companies or Other Railroad</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>3PL, Other Railroad, Other Company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Authorized Customers</relationshipLabel>
    <relationshipName>NS_Partnerships1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NS_Partnership__c/fields/NS_PartnershipType__c.field-meta.xml
<CustomField>
    <fullName>NS_PartnershipType__c</fullName>
    <description>It indicates what is the business this partner do with this customer.</description>
    <inlineHelpText>What business does this partner do with this customer?</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3PL</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Other Railroad</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NS_Partnership__c/fields/NS_PrimaryPartnerContact__c.field-meta.xml
<CustomField>
    <fullName>NS_PrimaryPartnerContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>It indicates the PrimaryContact from the Partner Account for this Customer</description>
    <inlineHelpText>Who is the Primary Contact from the Partner Account for this Customer?</inlineHelpText>
    <label>Primary Contact (Authorized Company)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact must be an Active Contact</errorMessage>
        <filterItems>
            <field>Contact.NS_ContactStatus__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Authorized Companies</relationshipLabel>
    <relationshipName>NS_Partnerships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NSPartnershipTestFactory.cls
@isTest
public class NSPartnershipTestFactory {
    /*Create Test NS Partnership Record*/
    public static NS_Partnership__c buildNSPartnershipRecord(Id acc1Id,Id accId, Id conId,String pType){
        NS_Partnership__c partner = new NS_Partnership__c (
            NS_CustomerAccount__c = acc1Id,
            NS_PartnerAccount__c = accId,
            NS_PrimaryPartnerContact__c = conId,
            NS_PartnershipType__c= pType);
        return partner;
    }
    /*Insert Test NS Partnership Record*/
    public static NS_Partnership__c createNSPartnershipRecord(NS_Partnership__c pnr){
        insert pnr;
        return pnr;
    }
    /*Insert Bulk Test NS Partnership Record*/
    public static void createBulkNSPartnershipRecord(List<NS_Partnership__c> pnrList){
        database.insert(pnrList,false);
    }
}