force-app/main/default/objects/NS_Partnership__c/NS_Partnership__c.object-meta.xml
<CustomObject>
    <description>It is a Partner object for Account</description>
    <label>Authorized Company</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorized Companies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Partnership__c/fields/NS_CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>NS_CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>It indicates who is the Customer that is related to this partner</description>
    <inlineHelpText>Who is the Customer that this Partner is related to?</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Customer Account can only be of Type Corporate,Service,Business or Offline Customer</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business, Corporate, Service, Offline Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Authorized Companies</relationshipLabel>
    <relationshipName>NS_Partnerships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_Partnership__c/fields/NS_PartnershipType__c.field-meta.xml
<CustomField>
    <fullName>NS_PartnershipType__c</fullName>
    <description>It indicates what is the business this partner do with this customer.</description>
    <inlineHelpText>What business does this partner do with this customer?</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3PL</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Other Railroad</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NS_Partnership__c/fields/NS_PrimaryPartnerContact__c.field-meta.xml
<CustomField>
    <fullName>NS_PrimaryPartnerContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>It indicates the PrimaryContact from the Partner Account for this Customer</description>
    <inlineHelpText>Who is the Primary Contact from the Partner Account for this Customer?</inlineHelpText>
    <label>Primary Contact (Authorized Company)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact must be an Active Contact</errorMessage>
        <filterItems>
            <field>Contact.NS_ContactStatus__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Authorized Companies</relationshipLabel>
    <relationshipName>NS_Partnerships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_TriggerSettings__c/NS_TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings to enable/disable Trigger</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/NS_TriggerSettings__c/fields/NS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>NS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>To enable Contact Trigger</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NS_PartnershipTriggerHelper.cls
/**@author  Accenture
* @Created Date 2018-05-16
* @version  1.0
* @description This class contains method to restrict duplicate partnership record based on Customer Account,Primary Partner Contact and Partnership Type on 
before insert and before update
*/
public with sharing class NS_PartnershipTriggerHelper {
    
    /*Class Name*/
    private static final String CLASS_NAME = 'NS_PartnershipTriggerHelper';
    /*Method Name*/
    private static final String METHOD_NAME1 = 'duplicatePartnershipCheckOnInsert';
    private static final String METHOD_NAME2 = 'duplicatePartnershipCheckOnUpdate';
    
    /*Restricting Duplicate Partnership on Inserting/Updating a Record*/
    public static void duplicatePartnershipCheckOnInsert(List <NS_Partnership__c> pList)
    {
        NS_TriggerSettings__c customset = NS_TriggerSettings__c.getValues(NS_StaticVariablesUtility.partnershipTrigger);
        if(customset.NS_IsActive__c){
            set<Id> setCustomerAccounts=new set<Id>();
            set<Id> setPartnerContacts=new set<Id>();
            set<String> setPartnershipTypes=new set<String>();
            set<String> setUniqueKey=new set<String>();
            Integer count =limits.getLimitQueryRows();
            List<NS_Partnership__c> dupPartnership =new List<NS_Partnership__c>();
            try{
                for(NS_Partnership__c p : pList){ 
                    if(p.NS_PrimaryPartnerContact__c!=NULL){
                        if(setUniqueKey.contains(String.valueOf(p.NS_CustomerAccount__c) +
                                                 String.valueOf(p.NS_PrimaryPartnerContact__c) + 
                                                 String.valueOf(p.NS_PartnershipType__c))){
                           p.addError(Label.NS_DuplicatePartnershipErrorMessage2+NS_StaticVariablesUtility.Space+p.NS_CustomerAccount__c+
                                      NS_StaticVariablesUtility.Space+p.NS_PrimaryPartnerContact__c+
                                      NS_StaticVariablesUtility.Space+p.NS_PartnershipType__c);
                        }
                        else{
                            setCustomerAccounts.add(p.NS_CustomerAccount__c);
                            setPartnerContacts.add(p.NS_PrimaryPartnerContact__c);
                            setPartnershipTypes.add(p.NS_PartnershipType__c);
                            setUniqueKey.add(String.valueOf(p.NS_CustomerAccount__c) + 
                                             String.valueOf(p.NS_PrimaryPartnerContact__c)+ 
                                             String.valueOf(p.NS_PartnershipType__c));
                        }
                    } 
                }      
              for(NS_Partnership__c p2  : pList){
                    for(NS_Partnership__c p1 : [SELECT id,Name,NS_CustomerAccount__c,NS_PrimaryPartnerContact__c,NS_PartnershipType__c 
                                    FROM NS_Partnership__c 
                                    WHERE NS_CustomerAccount__c IN:setCustomerAccounts
                                    AND NS_PrimaryPartnerContact__c IN:setPartnerContacts
                                    AND NS_PartnershipType__c IN:setPartnershipTypes LIMIT:count]){
                        if(p2.NS_CustomerAccount__c.equals(p1.NS_CustomerAccount__c) 
                           && p2.NS_PrimaryPartnerContact__c.equals(p1.NS_PrimaryPartnerContact__c)
                           && p2.NS_PartnershipType__c.equals(p1.NS_PartnershipType__c))
                               {
                                    p2.addError(Label.NS_DuplicatePartnershipErrorMessage1+NS_StaticVariablesUtility.Space+p1.name);
                               }
                           }
                }
            }
            catch (Exception exp) {
                    /*Inserting a record in Exception object*/
                    NS_StaticVariablesUtility.createExceptionRecord(exp,CLASS_NAME,METHOD_NAME1);
            }
        }
    
    }
   
    /*Restricting Duplicate Partnership Record on Updating a Record*/
     public static void duplicatePartnershipCheckOnUpdate( Map<Id,NS_Partnership__c> newPartnershipMap, 
                                                     Map<Id,NS_Partnership__c> oldPartnershipmap){
        NS_TriggerSettings__c customset = NS_TriggerSettings__c.getValues(NS_StaticVariablesUtility.partnershipTrigger);
        List<NS_Partnership__c> duplicatePartner=new List<NS_Partnership__c>();                                                  
        if(customset.NS_IsActive__c){
          try{
              for(NS_Partnership__c p2  : newPartnershipMap.values()){
                 if(p2.NS_CustomerAccount__c!=oldPartnershipmap.get(p2.id).NS_CustomerAccount__c  ||
                       p2.NS_PrimaryPartnerContact__c!=oldPartnershipmap.get(p2.id).NS_PrimaryPartnerContact__c  ||
                       p2.NS_PartnershipType__c!=oldPartnershipmap.get(p2.id).NS_PartnershipType__c){
                       duplicatePartner.add(p2);
                 }          
              }
              if(!duplicatePartner.isEmpty()){
                  duplicatePartnershipCheckOnInsert(duplicatePartner);
              }
          } 
          catch (Exception exp) {
                /*Inserting a record in Exception object*/
                NS_StaticVariablesUtility.createExceptionRecord(exp,CLASS_NAME,METHOD_NAME2);
            }
      }
   }
}