force-app/main/default/objects/NS_Partnership__c/NS_Partnership__c.object-meta.xml
<CustomObject>
    <description>It is a Partner object for Account</description>
    <label>Authorized Company</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorized Companies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Partnership__c/fields/NS_PartnershipType__c.field-meta.xml
<CustomField>
    <fullName>NS_PartnershipType__c</fullName>
    <description>It indicates what is the business this partner do with this customer.</description>
    <inlineHelpText>What business does this partner do with this customer?</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3PL</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Other Railroad</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NS_TriggerSettings__c/NS_TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings to enable/disable Trigger</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/NS_TriggerSettings__c/fields/NS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>NS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>To enable Contact Trigger</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NS_PartnershipTriggerHelperTest.cls
/**@author  Accenture
* @Created Date 2018-05-21
* @version  1.0
* @description This test class for NS_PartnershipTriggerHelper and NSPartnershipTrigger.
*/ 
@isTest(SeeAllData=false)
private class NS_PartnershipTriggerHelperTest {
    /*When a Partnership record is created with existing Customer,Primary Partner Contact and Type combination, it throws duplicate error*/
    @isTest
    static void insertPartnershipTest(){
        Profile adminProf = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,adminProf.Id);
        Profile repProf = UserTestFactory.createProfile(NS_StaticVariablesUtility.UserRep);
        User rep= UserTestFactory.createUser(13,repProf.Id); 
        System.runAs(admin ){ 
            NS_TriggerSettings__c triggerSettings = new NS_TriggerSettings__c(Name= NS_StaticVariablesUtility.partnershipTrigger); 
            triggerSettings.NS_IsActive__c = true;
            system.test.StartTest();
            Database.insert(triggerSettings,false);
            Account onlineAcc = AccountTestFactory.createOnlineAccountRecord(NS_StaticVariablesUtility.Name);
            AccountTestFactory.accountShare(onlineAcc.Id,rep.Id,NS_StaticVariablesUtility.readAccess,
                                            NS_StaticVariablesUtility.readAccess,
                                            NS_StaticVariablesUtility.readAccess,NS_StaticVariablesUtility.rowCause);
            system.test.StopTest();
            system.assertNotEquals(null, onlineAcc.Id);
        }
        System.runAs(rep){
            
                
                NS_TriggerSettings__c customSet = new NS_TriggerSettings__c(Name= 'ActiveNSPartnershipTrigger'); 
        customSet.NS_IsActive__c = true;
        Database.insert(customSet,false);
            Account onlineAccount = [SELECT id FROM Account WHERE name = 'Name' limit 1];
            Account nonOnlineAccount = AccountTestFactory.createAccountRecord(NS_StaticVariablesUtility.Name);
            system.assertNotEquals(null, nonOnlineAccount.Id);
            Contact contact = ContactTestFactory.createContactRecord(nonOnlineAccount.id,NS_StaticVariablesUtility.CONST_BLANK);
            system.assertNotEquals(null, contact.Id);
            NS_Partnership__c partner = NSPartnershipTestFactory.buildNSPartnershipRecord(
                onlineAccount.Id,nonOnlineAccount.Id,contact.Id,NS_StaticVariablesUtility.partnershipType1);
            NS_Partnership__c partner1 = NSPartnershipTestFactory.createNSPartnershipRecord(partner);
            system.assertNotEquals(null, partner1.Id);
            try{
                NS_Partnership__c partner2 = NSPartnershipTestFactory.buildNSPartnershipRecord(
                    onlineAccount.Id,nonOnlineAccount.Id,contact.Id,NS_StaticVariablesUtility.partnershipType1);  
                NS_Partnership__c partner3 = NSPartnershipTestFactory.createNSPartnershipRecord(partner2);
                system.assertEquals(null, partner3.Id);
            }
            catch(DMLException exp){
                boolean expVal = exp.getMessage().contains('This partnership already exists')?true:false;
                system.Assert(true,expVal); 
            }
        }
    }
    
    /*When a Partnership record is updated with existing Customer,Primary Partner Contact and Type combination, it throws duplicate error*/
    @isTest
    static void updatePartnershipTest(){
        system.test.StartTest();
        Profile adminProf = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,adminProf.Id);
        Profile repProf = UserTestFactory.createProfile(NS_StaticVariablesUtility.UserRep);
        User rep = UserTestFactory.createUser(13,repProf.Id); 
        System.runAs( admin ){ 
            NS_TriggerSettings__c triggerSettings = new NS_TriggerSettings__c(Name= NS_StaticVariablesUtility.partnershipTrigger); 
            triggerSettings.NS_IsActive__c = true;
            Database.insert(triggerSettings,false);
            Account onlineAcc = AccountTestFactory.createOnlineAccountRecord(NS_StaticVariablesUtility.Name);
            AccountTestFactory.accountShare(onlineAcc.Id,rep.Id,NS_StaticVariablesUtility.readAccess,
                                            NS_StaticVariablesUtility.readAccess,
                                            NS_StaticVariablesUtility.readAccess,NS_StaticVariablesUtility.rowCause);
            system.assertNotEquals(null, onlineAcc.Id);
        }
        System.runAs(rep){
            Account onlineAccount = [SELECT id FROM Account WHERE name = :NS_StaticVariablesUtility.Name limit 1];
            Account nonOnlineAccount = AccountTestFactory.createAccountRecord(NS_StaticVariablesUtility.Name); 
            system.assertNotEquals(null, nonOnlineAccount.Id);
            Contact contact = ContactTestFactory.createContactRecord(nonOnlineAccount.id,NS_StaticVariablesUtility.CONST_BLANK);  
            system.assertNotEquals(null, contact.Id);
            NS_Partnership__c partner = NSPartnershipTestFactory.buildNSPartnershipRecord(
                onlineAccount.Id,nonOnlineAccount.Id,contact.Id,NS_StaticVariablesUtility.partnershipType1);
            NS_Partnership__c partner1 = NSPartnershipTestFactory.createNSPartnershipRecord(partner);
            system.assertNotEquals(null, partner1.Id);
            NS_Partnership__c partner2 = NSPartnershipTestFactory.buildNSPartnershipRecord(
                onlineAccount.Id,nonOnlineAccount.Id,contact.Id,NS_StaticVariablesUtility.partnershipType2);  
            NS_Partnership__c partner3 = NSPartnershipTestFactory.createNSPartnershipRecord(partner2);
            system.assertNotEquals(null, partner3.Id);  
            try{
                partner2.NS_PartnershipType__c=NS_StaticVariablesUtility.partnershipType1;
                Database.update(partner2);
            }
            catch(DMLException exp){
                system.assertNotEquals(null, partner2.Id);
                boolean expVal = exp.getMessage().contains('This partnership already exists')?true:false;
                system.Assert(true,expVal); 
            }
        }
        system.test.StopTest();
    }
    /*During partnership data load, if records to be loaded contain any duplicate data,it throws duplicate error*/
    @isTest
    static void insertBulkPartnershipTest(){
        Profile adminProf = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,adminProf.Id);
        Profile repProf = UserTestFactory.createProfile(NS_StaticVariablesUtility.UserRep);
        User rep = UserTestFactory.createUser(13,repProf.Id); 
        List<NS_Partnership__c> partnerList =new List<NS_Partnership__c>();
        System.runAs(admin ){ 
            NS_TriggerSettings__c triggerSettings = new NS_TriggerSettings__c(Name= NS_StaticVariablesUtility.partnershipTrigger); 
            triggerSettings.NS_IsActive__c = true;
            system.test.StartTest();
            Database.insert(triggerSettings,false);
            Account onlineAcc = AccountTestFactory.createOnlineAccountRecord(NS_StaticVariablesUtility.Name);
            AccountTestFactory.accountShare(onlineAcc.Id,rep.Id,NS_StaticVariablesUtility.readAccess,
                                            NS_StaticVariablesUtility.readAccess,
                                            NS_StaticVariablesUtility.readAccess,NS_StaticVariablesUtility.rowCause);
            system.test.StopTest();
            system.assertNotEquals(null, onlineAcc.Id);
        }
        System.runAs(rep){
            Account onlineAccount = [SELECT id FROM Account WHERE name = 'Name' limit 1];
            Account nonOnlineAccount = AccountTestFactory.createAccountRecord(NS_StaticVariablesUtility.Name);
            system.assertNotEquals(null, nonOnlineAccount.Id);
            Contact con = ContactTestFactory.createContactRecord(nonOnlineAccount.id,NS_StaticVariablesUtility.CONST_BLANK);
            system.assertNotEquals(null, con.Id);
            for(Integer i=0;i<=3;i++){
                NS_Partnership__c partner = NSPartnershipTestFactory.buildNSPartnershipRecord(
                    onlineAccount.Id,nonOnlineAccount.Id,con.Id,NS_StaticVariablesUtility.partnershipType1);
                partnerList.add(partner);
            }
            try{
                NSPartnershipTestFactory.createBulkNSPartnershipRecord(partnerList);
            }
            catch(DMLException exp){
                boolean expVal = exp.getMessage().contains('Duplicate record found for Customer Account:')?true:false;
                system.Assert(true,expVal); 
            }
        }
    }
}