force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about Release</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story__c/fields/Level_3_Process__c.field-meta.xml
<CustomField>
    <fullName>Level_3_Process__c</fullName>
    <label>Level 3 Process</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/Value_Delivery_Session__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session</label>
    <nameField>
        <label>Value Delivery Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>To store Session Details.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>To capture Value Delivery Session End Date And Time</description>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Releases__c.field-meta.xml
<CustomField>
    <fullName>Releases__c</fullName>
    <description>Add Session to The Existing Project</description>
    <label>Releases</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Value Delivery Sessions</relationshipLabel>
    <relationshipName>Value_Delivery_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>To capture Value Delivery Session Start Date And Time</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/Value_Delivery_Session_Outcomes__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session Outcomes</label>
    <nameField>
        <label>Session Outcomes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Session Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiate And Confirm</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/fields/Session_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Session_Outcome__c</fullName>
    <label>Session Outcome</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/fields/Value_Delivery_Session__c.field-meta.xml
<CustomField>
    <fullName>Value_Delivery_Session__c</fullName>
    <label>Value Delivery Session</label>
    <referenceTo>Value_Delivery_Session__c</referenceTo>
    <relationshipName>Session_Outcomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_User_Stories__c/Value_Delivery_Session_User_Stories__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session User Stories</label>
    <nameField>
        <displayFormat>Session User-{0000}</displayFormat>
        <label>Value Deliver Session User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Value Delivery Session User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session_User_Stories__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Value Delivery Session User Stories</relationshipLabel>
    <relationshipName>Value_Deliver_Session_User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_User_Stories__c/fields/Value_Delivery_Session_Outcomes__c.field-meta.xml
<CustomField>
    <fullName>Value_Delivery_Session_Outcomes__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Value Delivery Session Outcomes</label>
    <referenceTo>Value_Delivery_Session_Outcomes__c</referenceTo>
    <relationshipLabel>Value Delivery Session User Stories</relationshipLabel>
    <relationshipName>Value_Deliver_Session_User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SaasSessionUserStoriesTest.cls
/** 
 *  Author : Accenture 
 *  Description : Test class for SaasSessionUserStories
 *  Created Date : 04\04\2016
 * 
 *  Version History :
 *  Date              Changes 
 *  04\04\2016        created 
 *
 */
 
 @isTest(seealldata=false)

public class SaasSessionUserStoriesTest
{
    static testmethod void ValidateSaasSessionUserStories()
   {

      PageReference pageRef = Page.SaasSessionUserStories;
      Test.setCurrentPage(pageRef);  
      
        Release__c rel = SaaSTestUtility.CreateRelease();
        User_Story__c us = SaaSTestUtility.createUserStory(rel);
        
        Value_Delivery_Session__c vds = new Value_Delivery_Session__c();
        vds.Description__c = 'test delivery data';
        vds.End_Date__c = System.today() + 10; 
        vds.Start_Time__c=system.now();
        vds.Releases__c = rel.id;
        insert vds;        
        
        Value_Delivery_Session_Outcomes__c objVDSO = new Value_Delivery_Session_Outcomes__c();
        objVDSO.Name = 'Test outcome Data';
        objVDSO.Phase__c = 'Design';
        objVDSO.Start_Date__c = system.today();
        objVDSO.End_Date__c = system.today()+10;
        objVDSO.Session_Outcome__c = 'Test data preparation';
        objVDSO.Value_Delivery_Session__c = vds.id;         
        insert objVDSO;           
        
        User_Story__c userstory = new User_Story__c();
        userstory.Priority__c ='Low';
        userstory.Release__c =rel.ID;
        userstory.Level_3_Process__c ='testing';
        insert userstory;

       //create  2 childs  for userstory..
        Value_Delivery_Session_User_Stories__c userStories1 = new Value_Delivery_Session_User_Stories__c();
        userStories1.Value_Delivery_Session_Outcomes__c = objVDSO.Id;
        userStories1 .User_Story__c =userstory.ID;
        insert userStories1 ;
        
        Value_Delivery_Session_User_Stories__c userStories2 = new Value_Delivery_Session_User_Stories__c();
        userStories2.Value_Delivery_Session_Outcomes__c = objVDSO.Id;
        userStories2 .User_Story__c =userstory.ID;
        insert userStories2 ;
        
        set<Id> setId= new set<Id>();

        //there is no child for userstory1 and userstory2
        User_Story__c userstory1 = new User_Story__c();
        userstory1.Priority__c ='Low';
        userstory1.Release__c =rel.ID;
        userstory1.Level_3_Process__c ='testing1';
        insert userstory1;
        
        setId.add(userstory1.Id);
        
        Value_Delivery_Session_User_Stories__c userStories = new Value_Delivery_Session_User_Stories__c();
        userStories.Value_Delivery_Session_Outcomes__c = objVDSO.Id;
        userStories.User_Story__c =null;
        userStories.User_Story__c = userstory1.Id;

        insert userStories ;
        
        User_Story__c userstory2 = new User_Story__c();
        userstory2.Priority__c ='Low';
        userstory2.Release__c =rel.ID;
        userstory2.Level_3_Process__c ='testing2';
        insert userstory2;
        setId.add(userstory2.Id);

        SaasSessionUserStories sus = new SaasSessionUserStories(new ApexPages.StandardController(objVDSO)); 
        sus.getUserStoriesWrapLst();
      
        SaasSessionUserStories.UserStoriesWrapper wr = new SaasSessionUserStories.UserStoriesWrapper(us);
        sus.getUserStoriesWrapLst()[0].checked=true; 
      
        boolean bnext = sus.hasNext ;
        boolean bprevious = sus.hasPrevious;
        sus.previous();
        sus.next();
        sus.sortByColumn();
        sus.search();
        sus.getSelectedElement();
        sus.importUserStories();
    }
}