force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SaaSUserStoriesListViewCtrlTest.cls
/** 
 *  Author : Accenture 
 *  Description : Test class for SaaSCreateUserStoriesCtrl
 *  Created Date : 11\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  08\06\2015        created 
 *
 */
 @isTest
public class SaaSUserStoriesListViewCtrlTest 
{
  static testmethod void ValidateSaaSUserStoriesListViewCtrl()
  {
      Release__c rel = SaaSTestUtility.createRelease();
      User_Story__c us = SaaSTestUtility.createUserStory(rel);    

      PageReference pageRef = Page.SaaSUserStoriesListView;
      Test.setCurrentPage(pageRef);      
      
      SaaSUserStoriesListViewCtrl sus = new SaaSUserStoriesListViewCtrl();
      sus.getUserStoriesWrapLst();
      
      SaaSUserStoriesListViewCtrl.UserStoriesWrapper wr = new SaaSUserStoriesListViewCtrl.UserStoriesWrapper(us);
      sus.getUserStoriesWrapLst()[0].checked=true; 
      
      boolean bnext = sus.hasNext;
      boolean bprevious = sus.hasPrevious;
      sus.previous();
      sus.next();
      sus.sortByColumn();
      sus.search();
      sus.getSelectedElement();
      sus.cloneUserStory();
      sus.updateUserStory();
      sus.deleteUserStory();
      
  }
}