force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about Release</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Plan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Start_Date__c</fullName>
    <description>Estimated date of Start</description>
    <label>Plan Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release_Planned_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Planned_End_Date__c</fullName>
    <description>Estimated date of end of release</description>
    <label>Release Planned End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Value_Delivery_Key_Participants__c/Value_Delivery_Key_Participants__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Key Participants</label>
    <nameField>
        <label>Value Delivery Key Participants  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Key Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Key_Participants__c/fields/Participant_Type__c.field-meta.xml
<CustomField>
    <fullName>Participant_Type__c</fullName>
    <label>Participant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Project Blended Core Team</fullName>
            </value>
            <value>
                <fullName>Accenture Team</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Value_Delivery_Key_Participants__c/fields/Session_Outcomes__c.field-meta.xml
<CustomField>
    <fullName>Session_Outcomes__c</fullName>
    <label>Session Outcomes</label>
    <referenceTo>Value_Delivery_Session_Outcomes__c</referenceTo>
    <relationshipLabel>Value Delivery Key Participants</relationshipLabel>
    <relationshipName>Value_Delivery_Key_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/Value_Delivery_Session__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session</label>
    <nameField>
        <label>Value Delivery Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>To store Session Details.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>To capture Value Delivery Session End Date And Time</description>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Releases__c.field-meta.xml
<CustomField>
    <fullName>Releases__c</fullName>
    <description>Add Session to The Existing Project</description>
    <label>Releases</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Value Delivery Sessions</relationshipLabel>
    <relationshipName>Value_Delivery_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>To capture Value Delivery Session Start Date And Time</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/Value_Delivery_Session_Outcomes__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session Outcomes</label>
    <nameField>
        <label>Session Outcomes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Session Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiate And Confirm</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/fields/Session_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Session_Outcome__c</fullName>
    <label>Session Outcome</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/fields/Value_Delivery_Session__c.field-meta.xml
<CustomField>
    <fullName>Value_Delivery_Session__c</fullName>
    <label>Value Delivery Session</label>
    <referenceTo>Value_Delivery_Session__c</referenceTo>
    <relationshipName>Session_Outcomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_User_Config__c/Value_Delivery_User_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Value Delivery User Config</label>
</CustomObject>

force-app/main/default/objects/Value_Delivery_User_Config__c/fields/Selected_Session__c.field-meta.xml
<CustomField>
    <fullName>Selected_Session__c</fullName>
    <label>Selected Session</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SaaSCreateSessionOutcomeCtrlTest.cls
@isTest
Public class SaaSCreateSessionOutcomeCtrlTest 
{
    static testMethod void validateCreateSessionOutcome() 
    {        
        Release__c rel = new Release__c();
        rel.Name = 'Test Release Data';
        rel.Id = null;
        rel.Plan_Start_Date__c = System.today();
        rel.Release_Planned_End_Date__c= System.today() + 10;
        rel.Status__c = 'Red';
        rel.Description__c = 'Test description ';
        insert rel;
        
        Value_Delivery_Session__c vds = new Value_Delivery_Session__c();
        vds.Description__c = 'test delivery data';
        vds.End_Date__c = System.today() + 10; 
        vds.Start_Time__c=system.now();
        vds.Releases__c = rel.id;
        insert vds;        
        
        Value_Delivery_Session_Outcomes__c objVDSO = new Value_Delivery_Session_Outcomes__c();
        objVDSO.Name = 'Test outcome Data';
        objVDSO.Phase__c = 'Design';
        objVDSO.Start_Date__c = system.today();
        objVDSO.End_Date__c = system.today()+10;
        objVDSO.Session_Outcome__c = 'Test data preparation';
        objVDSO.Value_Delivery_Session__c = vds.id; 
        insert objVDSO; 
  
        Value_Delivery_Key_Participants__c  vdp = new Value_Delivery_Key_Participants__c(); 
        vdp.name = 'TestName';
        vdp.Role__c = 'TestRole';
        vdp.Participant_Type__c = 'Accenture Team';
        vdp.Comments__c ='Test Comment';
        vdp.Session_Outcomes__c = objVDSO.id;
        insert vdp;
        
        List<Value_Delivery_Key_Participants__c> lstVDP = [select id, name, Role__c, Participant_Type__c,Comments__c from Value_Delivery_Key_Participants__c where id =:vdp.id LIMIT 1];
               
        Value_Delivery_Key_Participants__c vd = new Value_Delivery_Key_Participants__c();
        Integer i = 1;
        String s = 'Test';
        vd.name = 'TestNewName';
        vd.Role__c = 'TestNewRole';
        vd.Participant_Type__c = 'Accenture Team';
        vd.Comments__c ='TestNew Comment';
        vd.Session_Outcomes__c = objVDSO.id;
        insert vd;
        
        Value_Delivery_User_Config__c vdU = new Value_Delivery_User_Config__c();
        vdu.Name = 'TestUser';      
        vdu.Selected_Session__c= vds.Id;
        insert vdu;
        
        SaaSCreateSessionOutcomeCtrl ctrl = new SaaSCreateSessionOutcomeCtrl(new ApexPages.StandardController(objVDSO));                
        ctrl.sessonStartDate = Date.today();
        ctrl.sessonEndDate = Date.today()+10;
        ctrl.isDetail = false;
        ctrl.isInsert = false;
        ctrl.isSaved = false;
        ctrl.success = false;
        ctrl.participantsObj = lstVDP;        
        ctrl.sessOutcomeObj = objVDSO;

        SaaSCreateSessionOutcomeCtrl.ParticipantsWrapper pw = new SaaSCreateSessionOutcomeCtrl.ParticipantsWrapper(vdp);        
        SaaSCreateSessionOutcomeCtrl.ParticipantsWrapper pwList = new SaaSCreateSessionOutcomeCtrl.ParticipantsWrapper(i,vd,s);
        
        
        ctrl.newParticipantsLst.add(pwList);
        
        ctrl.saveSessionOutcome();
        
        ctrl.displayImport();
        
        ctrl.getImportParticipants();
        ctrl.add();
        
        
        ctrl.getAllKeyParticipants();        
        ctrl.importPreviousSessionOutome();
        ctrl.remove();
        
        
        
    }
    
    static testMethod void validateCreateSessionOutcomeNegative() 
    {
        Release__c rel = new Release__c();
        rel.Name = 'Test Release Data';
        rel.Id = null;
        rel.Plan_Start_Date__c = System.today();
        rel.Release_Planned_End_Date__c= System.today() + 10;
        rel.Status__c = 'Red';
        rel.Description__c = 'Test description ';
        insert rel;
        
        Value_Delivery_Session__c vds = new Value_Delivery_Session__c();
        vds.Description__c = 'test delivery data';
        vds.End_Date__c = System.today() + 10; 
        vds.Start_Time__c=system.now();
        vds.Releases__c = rel.id;
        insert vds;        
        
        Value_Delivery_Session_Outcomes__c objVDSO = new Value_Delivery_Session_Outcomes__c();
        objVDSO.Name = 'Test outcome Data';
        objVDSO.Phase__c = Null;
        objVDSO.Start_Date__c = system.today();
        objVDSO.End_Date__c = system.today()+10;
        objVDSO.Session_Outcome__c = Null;
        objVDSO.Value_Delivery_Session__c = vds.id; 
        insert objVDSO; 

        SaaSCreateSessionOutcomeCtrl ctrl = new SaaSCreateSessionOutcomeCtrl(new ApexPages.StandardController(objVDSO));
        
        ctrl.displayImport();
        ctrl.saveSessionOutcome();
        ctrl.importPreviousSessionOutome();
        ctrl.remove();
 
    }
}