force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about Release</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/User_Story_Description__c.field-meta.xml
<CustomField>
    <fullName>User_Story_Description__c</fullName>
    <label>User Story Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User_Story_Options__c/User_Story_Options__c.object-meta.xml
<CustomObject>
    <label>User Story Option</label>
    <nameField>
        <displayFormat>OPT-{0000}</displayFormat>
        <label>User Story Options Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story_Options__c/fields/Value_Deliver_Session_User_Stories__c.field-meta.xml
<CustomField>
    <fullName>Value_Deliver_Session_User_Stories__c</fullName>
    <label>Value Deliver Session User Stories</label>
    <referenceTo>Value_Delivery_Session_User_Stories__c</referenceTo>
    <relationshipLabel>User Story Options</relationshipLabel>
    <relationshipName>User_Story_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/Value_Delivery_Session__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session</label>
    <nameField>
        <label>Value Delivery Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>To store Session Details.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>To capture Value Delivery Session End Date And Time</description>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Releases__c.field-meta.xml
<CustomField>
    <fullName>Releases__c</fullName>
    <description>Add Session to The Existing Project</description>
    <label>Releases</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Value Delivery Sessions</relationshipLabel>
    <relationshipName>Value_Delivery_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>To capture Value Delivery Session Start Date And Time</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/Value_Delivery_Session_Outcomes__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session Outcomes</label>
    <nameField>
        <label>Session Outcomes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Session Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiate And Confirm</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/fields/Session_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Session_Outcome__c</fullName>
    <label>Session Outcome</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/fields/Value_Delivery_Session__c.field-meta.xml
<CustomField>
    <fullName>Value_Delivery_Session__c</fullName>
    <label>Value Delivery Session</label>
    <referenceTo>Value_Delivery_Session__c</referenceTo>
    <relationshipName>Session_Outcomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_User_Stories__c/Value_Delivery_Session_User_Stories__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session User Stories</label>
    <nameField>
        <displayFormat>Session User-{0000}</displayFormat>
        <label>Value Deliver Session User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Value Delivery Session User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session_User_Stories__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Value Delivery Session User Stories</relationshipLabel>
    <relationshipName>Value_Deliver_Session_User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_User_Stories__c/fields/Value_Delivery_Session_Outcomes__c.field-meta.xml
<CustomField>
    <fullName>Value_Delivery_Session_Outcomes__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Value Delivery Session Outcomes</label>
    <referenceTo>Value_Delivery_Session_Outcomes__c</referenceTo>
    <relationshipLabel>Value Delivery Session User Stories</relationshipLabel>
    <relationshipName>Value_Deliver_Session_User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SaaSCreateUserStoriesCtrlTest.cls
/** 
 *  Author : Accenture 
 *  Description : Test class for SaaSCreateUserStoriesCtrl
 *  Created Date : 11\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  08\06\2015        created 
 *
 */
@isTest
public class SaaSCreateUserStoriesCtrlTest 
{

  static testmethod void ValidateSaaSCreateUserStoriesCtrl()
  {
      Release__c rel = SaaSTestUtility.createRelease();
      User_Story__c us = SaaSTestUtility.createUserStory(rel); 
      
      Value_Delivery_Session__c vds = new Value_Delivery_Session__c();
      vds.Description__c = 'test delivery data';
      vds.End_Date__c = System.today() + 10; 
      vds.Start_Time__c=system.now();
      vds.Releases__c = rel.id;
      insert vds;        
        
      Value_Delivery_Session_Outcomes__c objVDSO = new Value_Delivery_Session_Outcomes__c();
      objVDSO.Name = 'Test outcome Data';
      objVDSO.Phase__c = 'Design';
      objVDSO.Start_Date__c = system.today();
      objVDSO.End_Date__c = system.today()+10;
      objVDSO.Session_Outcome__c = 'Test data preparation';
      objVDSO.Value_Delivery_Session__c = vds.id; 
      insert objVDSO;   
       
      User_Story__c userstory = new User_Story__c();
      userstory.name ='how to implement';
      userstory.Release__c = rel.Id;
      insert userstory;
      
      Value_Delivery_Session_User_Stories__c stories = new Value_Delivery_Session_User_Stories__c();
      stories.Value_Delivery_Session_Outcomes__c = objVDSO.Id;
      stories.User_Story__c =userstory.Id;
      insert stories;
      
      User_Story_Options__c userStoryoption = new User_Story_Options__c ();
      integer i=1;
      string s ='test';
      userStoryoption.Value_Deliver_Session_User_Stories__c=stories.Id;
      insert userStoryoption;
      
      User_Story_Options__c userStoryoption1 = new User_Story_Options__c ();
      userStoryoption1.Value_Deliver_Session_User_Stories__c=stories.Id;
      insert userStoryoption1;
      List<User_Story_Options__c> userStoryoptionlist = [select id from User_Story_Options__c where id=:userStoryoption1.Id LIMIT 1]; 
      
      SaaSCreateUserStoriesCtrl ctrl = new SaaSCreateUserStoriesCtrl(new ApexPages.StandardController(us)); 
      ctrl.userStoryObj.name='test';
      ctrl.userStoryObj.Release__c =rel.Id;
      ctrl.createNewUserStory();
      ctrl.addUserStoryOptions();

      SaaSCreateUserStoriesCtrl.UserStoryOptionWrapper pwt = new SaaSCreateUserStoriesCtrl.UserStoryOptionWrapper(userStoryoption1); 
      pwt.disableLookup = true;
      pwt.hash ='2';
      ctrl.clientHash ='1';
      SaaSCreateUserStoriesCtrl.UserStoryOptionWrapper pw = new SaaSCreateUserStoriesCtrl.UserStoryOptionWrapper(i,userStoryoption,s); 
      ctrl.userStoryOptionLst.add(pw);
      ctrl.initlizeOptions();
      pw.valueDeliverySession =objVDSO.ID;
      ctrl.userStoryOptionLst.add(pw);
      ctrl.saveUserStory();
      try{
      ctrl.saveUserStoryOption();
      }Catch(Exception ex){}
      ctrl.remove();
      ctrl.updatelookupToReadOnly();
  }
    
    static testmethod void ValidateSaaSCreateUserStoriesCtrlNegative()
    {
      Release__c rel = SaaSTestUtility.createRelease();
      User_Story__c usc = SaaSTestUtility.createUserStory(rel);   
       
      ApexPages.CurrentPage().getparameters().put('isClone', '1');  
      ApexPages.CurrentPage().getparameters().put('releaseid', rel.id);
      SaaSCreateUserStoriesCtrl ctrls = new SaaSCreateUserStoriesCtrl(new ApexPages.StandardController(usc)); 
      ctrls.saveUserStory();   
      ctrls.userStoryObj.name  = null;  
      ctrls.saveUserStory();   
      ctrls.userStoryObj.name  = 'test';        
      ctrls.saveUserStory();         
      ctrls.userStoryObj.User_Story_Description__c = null;
      ctrls.saveUserStory();   
      ctrls.userStoryObj.User_Story_Description__c = 'dec';
      ctrls.userStoryObj.Release__c =null; 
      ctrls.saveUserStory();   
     
      rel = SaaSTestUtility.createRelease();
      usc = SaaSTestUtility.createUserStory(rel);    
       
      SaaSCreateUserStoriesCtrl ctrl = new SaaSCreateUserStoriesCtrl(new ApexPages.StandardController(usc)); 
      ctrl.saveUserStory();   
      ctrl = new SaaSCreateUserStoriesCtrl(new ApexPages.StandardController(new User_Story__c())); 
    
         
   }
}