force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about Release</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Plan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Start_Date__c</fullName>
    <description>Estimated date of Start</description>
    <label>Plan Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release_Planned_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Planned_End_Date__c</fullName>
    <description>Estimated date of end of release</description>
    <label>Release Planned End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status_Update__c.field-meta.xml
<CustomField>
    <fullName>Status_Update__c</fullName>
    <description>Release status update</description>
    <inlineHelpText>Release status update</inlineHelpText>
    <label>Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SaaSCreateReleaseCtrlTest.cls
@isTest
/** 
 *  Author : Accenture 
 *  Description : Test Class for Controller class for SaaSCreateReleaseCtrl
 *  Created Date : 05\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  09\06\2015        created 
 *
 */
  public class SaaSCreateReleaseCtrlTest
{
    static testMethod void validateCreateRelease() 
    {
        Release__c rel = new Release__c();
        rel.Name = 'Test Release ';
        rel.Release__c = 24;
        rel.Id = null;
        rel.Plan_Start_Date__c = System.today();
        rel.Release_Planned_End_Date__c= System.today() + 10;
        rel.Status__c = 'Red';
        rel.Description__c = 'Test description ';
        rel.Status_Update__c = 'Test Comments';
        insert rel;
        
        SaaSCreateReleaseCtrl controller = new SaaSCreateReleaseCtrl(new ApexPages.StandardController(rel));
        controller.saveRelease();
        controller.validateKeyDecision();
        
    }
    
    static testMethod void validateCreateRelease1()
    {
       Release__c rel = new Release__c(); 
       SaaSCreateReleaseCtrl controller = new SaaSCreateReleaseCtrl(new ApexPages.StandardController(rel));
       controller.saveRelease();
       controller.createNewRelease();
       controller.validateKeyDecision();
       
       
     
    }
    
    static testMethod void validateReleaseClone()
    {
        Release__c rel = new Release__c();
        rel.Name = 'Test Release ';
        rel.Release__c = 24;
        rel.Plan_Start_Date__c = System.today();
        rel.Release_Planned_End_Date__c= System.today() + 10;
        rel.Status__c = 'Red';
        rel.Description__c = 'Test description ';
        rel.Status_Update__c = 'Test Comments';
        insert rel;
        
        PageReference pageRef = Page.SaaSCreateRelease;
        pageRef.getParameters().put(SaaSTextConstant.IS_CLONE_URL_PARAM, '1');
        pageRef.getParameters().put(SaaSTextConstant.RELEASEID_URL_PARAM,rel.id);
        Test.setCurrentPage(pageRef);
        SaaSCreateReleaseCtrl controller = new SaaSCreateReleaseCtrl(new ApexPages.StandardController(rel));
        Controller.saveRelease();
        Controller.validateKeyDecision();
    }
}