force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about Release</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Plan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Start_Date__c</fullName>
    <description>Estimated date of Start</description>
    <label>Plan Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release_Planned_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Planned_End_Date__c</fullName>
    <description>Estimated date of end of release</description>
    <label>Release Planned End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Story_Options__c/User_Story_Options__c.object-meta.xml
<CustomObject>
    <label>User Story Option</label>
    <nameField>
        <displayFormat>OPT-{0000}</displayFormat>
        <label>User Story Options Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story_Options__c/fields/User_Story_Option__c.field-meta.xml
<CustomField>
    <fullName>User_Story_Option__c</fullName>
    <label>User Story Option</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User_Story_Options__c/fields/Value_Deliver_Session_User_Stories__c.field-meta.xml
<CustomField>
    <fullName>Value_Deliver_Session_User_Stories__c</fullName>
    <label>Value Deliver Session User Stories</label>
    <referenceTo>Value_Delivery_Session_User_Stories__c</referenceTo>
    <relationshipLabel>User Story Options</relationshipLabel>
    <relationshipName>User_Story_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Key_Participants__c/Value_Delivery_Key_Participants__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Key Participants</label>
    <nameField>
        <label>Value Delivery Key Participants  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Key Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Key_Participants__c/fields/Participant_Type__c.field-meta.xml
<CustomField>
    <fullName>Participant_Type__c</fullName>
    <label>Participant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Project Blended Core Team</fullName>
            </value>
            <value>
                <fullName>Accenture Team</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Value_Delivery_Key_Participants__c/fields/Session_Outcomes__c.field-meta.xml
<CustomField>
    <fullName>Session_Outcomes__c</fullName>
    <label>Session Outcomes</label>
    <referenceTo>Value_Delivery_Session_Outcomes__c</referenceTo>
    <relationshipLabel>Value Delivery Key Participants</relationshipLabel>
    <relationshipName>Value_Delivery_Key_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/Value_Delivery_Session__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session</label>
    <nameField>
        <label>Value Delivery Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>To store Session Details.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>To capture Value Delivery Session End Date And Time</description>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Releases__c.field-meta.xml
<CustomField>
    <fullName>Releases__c</fullName>
    <description>Add Session to The Existing Project</description>
    <label>Releases</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Value Delivery Sessions</relationshipLabel>
    <relationshipName>Value_Delivery_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>To capture Value Delivery Session Start Date And Time</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/Value_Delivery_Session_Outcomes__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session Outcomes</label>
    <nameField>
        <label>Session Outcomes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Session Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiate And Confirm</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/fields/Session_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Session_Outcome__c</fullName>
    <label>Session Outcome</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/fields/Value_Delivery_Session__c.field-meta.xml
<CustomField>
    <fullName>Value_Delivery_Session__c</fullName>
    <label>Value Delivery Session</label>
    <referenceTo>Value_Delivery_Session__c</referenceTo>
    <relationshipName>Session_Outcomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_User_Stories__c/Value_Delivery_Session_User_Stories__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session User Stories</label>
    <nameField>
        <displayFormat>Session User-{0000}</displayFormat>
        <label>Value Deliver Session User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Value Delivery Session User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session_User_Stories__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Value Delivery Session User Stories</relationshipLabel>
    <relationshipName>Value_Deliver_Session_User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_User_Stories__c/fields/Value_Delivery_Session_Outcomes__c.field-meta.xml
<CustomField>
    <fullName>Value_Delivery_Session_Outcomes__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Value Delivery Session Outcomes</label>
    <referenceTo>Value_Delivery_Session_Outcomes__c</referenceTo>
    <relationshipLabel>Value Delivery Session User Stories</relationshipLabel>
    <relationshipName>Value_Deliver_Session_User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vote_User_Story__c/Vote_User_Story__c.object-meta.xml
<CustomObject>
    <label>Vote User Story</label>
    <nameField>
        <displayFormat>Vote-{0000}</displayFormat>
        <label>Vote User Story Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vote User Story</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote_User_Story__c/fields/User_Story_Option__c.field-meta.xml
<CustomField>
    <fullName>User_Story_Option__c</fullName>
    <label>User Story Option</label>
    <referenceTo>User_Story_Options__c</referenceTo>
    <relationshipLabel>Vote User Story</relationshipLabel>
    <relationshipName>Vote_User_Story</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SaaSSessionOutcomeDetailCtrlTest.cls
@isTest
public class SaaSSessionOutcomeDetailCtrlTest 
{
   static testMethod void validateSaaSSessionOutcomeDetail() 
   {
        Release__c rel = new Release__c();
        rel.Name = 'Test Release Data';
        rel.Id = null;
        rel.Plan_Start_Date__c = System.today();
        rel.Release_Planned_End_Date__c= System.today() + 10;
        rel.Status__c = 'Red';
        rel.Description__c = 'Test description ';
        insert rel;
        
        Value_Delivery_Session__c vds = new Value_Delivery_Session__c();
        vds.Description__c = 'test delivery data';
        vds.End_Date__c = System.today() + 10; 
        vds.Start_Time__c=system.now();
        vds.Releases__c = rel.id;
        insert vds;        
                
        Value_Delivery_Session_Outcomes__c objVDSO = new Value_Delivery_Session_Outcomes__c();
        objVDSO.Name = 'Test outcome Data';
        objVDSO.Phase__c = 'Design';
        objVDSO.Start_Date__c = system.today();
        objVDSO.End_Date__c = system.today()+10;
        objVDSO.Session_Outcome__c = 'Test data preparation';
        objVDSO.Value_Delivery_Session__c = vds.id; 
        insert objVDSO;   
       
                

        Value_Delivery_Key_Participants__c  vdp = new Value_Delivery_Key_Participants__c(); 
        vdp.name = 'TestName';
        vdp.Role__c = 'TestRole';
        vdp.Participant_Type__c = 'Accenture Team';
        vdp.Comments__c ='Test Comment';
        vdp.Session_Outcomes__c = objVDSO.id;
        insert vdp;
       
        Value_Delivery_Key_Participants__c  vd = new Value_Delivery_Key_Participants__c(); 
        vd.name = 'TestNewName';
        vd.Role__c = 'TestNewRole';
        vd.Participant_Type__c = 'Accenture Team';
        vd.Comments__c ='TestNew Comment';
        vd.Session_Outcomes__c = objVDSO.id;
        insert vd;
          
        ApexPages.CurrentPage().getparameters().put('participantsId', vd.id);
        SaaSSessionOutcomeDetailCtrl ctrl = new SaaSSessionOutcomeDetailCtrl(new ApexPages.StandardController(objVDSO));
        ctrl.getParticipants();
        ctrl.newParticipantsObj = vdp;
        ctrl.isDetail = false;
        ctrl.sessionsOutcomeLst = new List<SelectOption>();
        ctrl.sessOutcomeID = objVDSO.id;
        ctrl.participantsObj = vd;        
        ctrl.saveSessionOutcome(); 
        objVDSO.Name = Null;
        try {
            ctrl.validateSessionOutcome();
        } catch(DMLException e) {
            system.assertEquals(e.getMessage(), e.getMessage());
        } 
        ctrl.addPartcipants();   
        
        ctrl.getAllKeyParticipants();        
        ctrl.updateParticipants();
        ctrl.deleteParticipants();
        User_Story__c userstory = new User_Story__c();
        userstory.name ='how to implement';
        userstory.Release__c = rel.Id;
        insert userstory;
        
        Value_Delivery_Session_User_Stories__c stories = new Value_Delivery_Session_User_Stories__c();
        stories.Value_Delivery_Session_Outcomes__c = objVDSO.Id;
        stories.User_Story__c =userstory.Id;
        insert stories;
       
        Value_Delivery_Session_User_Stories__c stories1 = new Value_Delivery_Session_User_Stories__c();
        boolean flag = true;
        stories1.Value_Delivery_Session_Outcomes__c = objVDSO.Id;
        stories1.User_Story__c =userstory.Id;
        insert stories1;
      
       User_Story_Options__c userStoryoption = new User_Story_Options__c ();
       integer i=1;
       string s ='test';
       userStoryoption.Value_Deliver_Session_User_Stories__c=stories.Id;
       insert userStoryoption;
       
       User_Story_Options__c userStoryoption1 = new User_Story_Options__c ();
       userStoryoption1.Value_Deliver_Session_User_Stories__c=stories.Id;
       insert userStoryoption1;
       
       List<User_Story_Options__c> userStoryoptionlist = [select id from User_Story_Options__c where id=:userStoryoption1.Id LIMIT 1]; 
       
       SaaSSessionOutcomeDetailCtrl.OptionsWrapper pwr = new SaaSSessionOutcomeDetailCtrl.OptionsWrapper (userStoryoption1); 
       SaaSSessionOutcomeDetailCtrl.OptionsWrapper pw = new SaaSSessionOutcomeDetailCtrl.OptionsWrapper(i,userStoryoption,s);        
       ctrl.newOptionsLst.add(pw);
       ctrl.getSessionUserStory();
       ctrl.getUserStoryOptions();
       ctrl.saveUserVote();
       ctrl.saveUserStory();
       list<Vote_User_Story__c>  userVoteLst = new List<Vote_User_Story__c>();
       SaaSSessionOutcomeDetailCtrl.VoteUserStoryWrapper  pwt = new SaaSSessionOutcomeDetailCtrl.VoteUserStoryWrapper ();  
        pwt.userVote = null;
        try {
           ctrl.validateUserVote(); 
       } catch(DMLException e) {
         system.assertEquals(e.getMessage(), e.getMessage());
       }
       

       userVoteLst.add(pwt.userVoteObj);   
       ctrl.add();
       ctrl.remove();
       //ctrl.validateSessionOutcome();
       ctrl.validateParticipant(vdp);
       boolean flag1 =ctrl.voteFlag;
      // ctrl.deleteSessionUserStory();
       SaaSSessionOutcomeDetailCtrl.SessionUserStoryWrapper session = new SaaSSessionOutcomeDetailCtrl.SessionUserStoryWrapper(stories);        

       Vote_User_Story__c voteUserStory = new Vote_User_Story__c();
       voteUserStory.User_Story_Option__c =userStoryoption1.Id;
       insert voteUserStory ;

       SaaSSessionOutcomeDetailCtrl.SessionUserStoryWrapper session1 = new SaaSSessionOutcomeDetailCtrl.SessionUserStoryWrapper(stories1,true);        
   }
    
   static testMethod void validateSaaSSessionOutcomeDetailNegative() 
   {
        Release__c rel = new Release__c();
        rel.Name = 'Test Release Data';
        rel.Id = null;
        rel.Plan_Start_Date__c = System.today();
        rel.Release_Planned_End_Date__c= System.today() + 10;
        rel.Status__c = 'Red';
        rel.Description__c = 'Test description ';
        insert rel;
        
        Value_Delivery_Session__c vds = new Value_Delivery_Session__c();
        vds.Description__c = 'test delivery data';
        vds.End_Date__c = System.today() + 10; 
        vds.Start_Time__c=system.now();
        vds.Releases__c = rel.id;
        insert vds;        
        
        Value_Delivery_Session_Outcomes__c objVDSO = new Value_Delivery_Session_Outcomes__c();
        objVDSO.Name = 'Test Data';
        objVDSO.Phase__c = Null;
        objVDSO.Start_Date__c = system.today();
        objVDSO.End_Date__c = system.today()+10;
        objVDSO.Session_Outcome__c = 'Test data preparation';
        objVDSO.Value_Delivery_Session__c = vds.id;         
        insert objVDSO;

        Value_Delivery_Key_Participants__c  vd = new Value_Delivery_Key_Participants__c(); 
        vd.name = 'TestNewName';
        vd.Role__c = 'TestNewRole';
        vd.Participant_Type__c = 'Accenture Team';
        vd.Comments__c ='TestNew Comment';
        vd.Session_Outcomes__c = objVDSO.id;
       
        SaaSSessionOutcomeDetailCtrl ctrl = new SaaSSessionOutcomeDetailCtrl(new ApexPages.StandardController(objVDSO));        
        
        ctrl.newParticipantsObj = vd;

        ctrl.addPartcipants();
        ctrl.saveSessionOutcome();
       
        ctrl.participantsObj = Null;
        ctrl.updateParticipants();
        ctrl.deleteParticipants();
              
        Value_Delivery_Session_Outcomes__c objVDSOs = new Value_Delivery_Session_Outcomes__c();
        objVDSOs.Name = '   ';
        objVDSOs.Phase__c = 'Design';
        objVDSOs.Start_Date__c = system.today();
        objVDSOs.End_Date__c = system.today()+10;
        objVDSOs.Session_Outcome__c = 'Test data preparation';
        objVDSOs.Value_Delivery_Session__c = vds.id;            
        insert objVDSOs;
               
        SaaSSessionOutcomeDetailCtrl ctrls = new SaaSSessionOutcomeDetailCtrl(new ApexPages.StandardController(objVDSOs));
        ctrls.saveSessionOutcome();
   }
   
    static testMethod void SaaSSessionOutcomeDetailNegativeTest() 
   {
        Release__c rel = new Release__c();
        rel.Name = 'Test Release Data';
        rel.Id = null;
        rel.Plan_Start_Date__c = System.today();
        rel.Release_Planned_End_Date__c= System.today() + 10;
        rel.Status__c = 'Red';
        rel.Description__c = 'Test description ';
        insert rel;
        
        Value_Delivery_Session__c vds = new Value_Delivery_Session__c();
        vds.Description__c = 'test delivery data';
        vds.End_Date__c = System.today() + 10; 
        vds.Start_Time__c=system.now();
        vds.Releases__c = rel.id;
        insert vds;        
        
        Value_Delivery_Session_Outcomes__c objVDSO = new Value_Delivery_Session_Outcomes__c();
        objVDSO.Name = 'Test Data';
        objVDSO.Phase__c = Null;
        objVDSO.Start_Date__c = system.today();
        objVDSO.End_Date__c = system.today()+10;
        objVDSO.Session_Outcome__c = 'Test data preparation';
        objVDSO.Value_Delivery_Session__c = vds.id;         
        insert objVDSO;
        
        
        Value_Delivery_Key_Participants__c  vd = new Value_Delivery_Key_Participants__c(); 
        vd.name = Null;
        vd.Role__c = 'Test Roll';
        vd.Participant_Type__c = 'Accenture Team';
        vd.Comments__c ='TestNew Comment';
        vd.Session_Outcomes__c = Null;
        
         Value_Delivery_Key_Participants__c  vdp = new Value_Delivery_Key_Participants__c(); 
        vdp.name = 'Rahul';
        vdp.Role__c = Null;
        vdp.Participant_Type__c = 'Accenture Team';
        vdp.Comments__c ='TestNew Comment';
        vdp.Session_Outcomes__c = objVDSO.ID;
  
        Value_Delivery_Session_User_Stories__c stories = new Value_Delivery_Session_User_Stories__c();
        stories.Value_Delivery_Session_Outcomes__c = objVDSO.Id;
        stories.User_Story__c =null;
       
        
        SaaSSessionOutcomeDetailCtrl ctrl = new SaaSSessionOutcomeDetailCtrl(new ApexPages.StandardController(objVDSO));        
        
        ctrl.participantsObj = vd;
        ctrl.deleteSessionUsrStory = stories;
        ctrl.deleteSessionUserStory();
        ctrl.deleteParticipants();
        //ctrl.newSessionUserStoriesObj = stories;
        //ctrl.saveUserStory();
        ctrl.updateParticipants();
        
   }      
}