force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Execution__c/Test_Execution__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents the execution of a test script in a specific case.</description>
    <label>Test Script Execution</label>
    <nameField>
        <displayFormat>TE-{0}</displayFormat>
        <label>Test Execution ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Execution__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Comments on the test execution</description>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Execution__c/fields/Description_of_Script__c.field-meta.xml
<CustomField>
    <fullName>Description_of_Script__c</fullName>
    <formula>Test_Script_Description__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Description of Script</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Execution__c/fields/Execution_Cycle_Name__c.field-meta.xml
<CustomField>
    <fullName>Execution_Cycle_Name__c</fullName>
    <label>Execution Cycle Name</label>
    <referenceTo>Test_Execution_Cycle__c</referenceTo>
    <relationshipName>Test_Executions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Test_Execution__c/fields/Execution_Date__c.field-meta.xml
<CustomField>
    <fullName>Execution_Date__c</fullName>
    <description>Date of test execution</description>
    <label>Execution Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Test_Execution__c/fields/Request_Description__c.field-meta.xml
<CustomField>
    <fullName>Request_Description__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request ID</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Test Script Executions</relationshipLabel>
    <relationshipName>Test_Script_Executions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Execution__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <description>Result of test execution</description>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Execution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Execution__c/fields/Test_Executor__c.field-meta.xml
<CustomField>
    <fullName>Test_Executor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Executor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Test_Script_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Execution__c/fields/Test_Script_Description__c.field-meta.xml
<CustomField>
    <fullName>Test_Script_Description__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Script ID</label>
    <referenceTo>Test_Script__c</referenceTo>
    <relationshipLabel>Test Script Executions</relationshipLabel>
    <relationshipName>Test_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Execution_Cycle__c/Test_Execution_Cycle__c.object-meta.xml
<CustomObject>
    <label>Test Execution Cycle</label>
    <nameField>
        <label>Execution Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Execution Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Execution_Cycle__c/fields/Execution_Type__c.field-meta.xml
<CustomField>
    <fullName>Execution_Type__c</fullName>
    <label>Execution Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unit Test</fullName>
            </value>
            <value>
                <fullName>SIT</fullName>
            </value>
            <value>
                <fullName>Regression Test</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Execution_Cycle__c/fields/Release_Name__c.field-meta.xml
<CustomField>
    <fullName>Release_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release Name</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Test Execution Cycles</relationshipLabel>
    <relationshipName>Test_Execution_Cycles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Execution_Steps__c/Test_Execution_Steps__c.object-meta.xml
<CustomObject>
    <label>Test Execution Steps</label>
    <nameField>
        <label>Execution Steps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Execution Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Execution_Steps__c/fields/Actual_Result__c.field-meta.xml
<CustomField>
    <fullName>Actual_Result__c</fullName>
    <label>Actual Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Execution_Steps__c/fields/Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Execution_Steps__c/fields/Input_Data__c.field-meta.xml
<CustomField>
    <fullName>Input_Data__c</fullName>
    <label>Input Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Execution_Steps__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Execution_Steps__c/fields/Step_Order__c.field-meta.xml
<CustomField>
    <fullName>Step_Order__c</fullName>
    <label>Step Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Test_Execution_Steps__c/fields/Test_Execution_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Execution_Name__c</fullName>
    <label>Test Execution Name</label>
    <referenceTo>Test_Execution__c</referenceTo>
    <relationshipLabel>Test Execution Steps</relationshipLabel>
    <relationshipName>Test_Execution_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VFC_EmployeeCycle_Releasee.cls
public with sharing class VFC_EmployeeCycle_Releasee {
    Public List<TestExecutionSteps> wrpexctnsptsLst {get;set;}
    Public List<Test_Execution_Steps__c> tstExcstpLst{get;set;}
    Public List<Test_Execution__c> testEctn {get;set;}
    Public String ExtsId{get;set;}
    private ApexPages.StandardController stdController;
    Public Id usrId{get;set;}
    
    public VFC_EmployeeCycle_Releasee (ApexPages.StandardController controller) {
        this.stdController= Controller;    
        testEctn = new List<Test_Execution__c>();
        tstExcstpLst = new List<Test_Execution_Steps__c>();
        usrId = userInfo.getUserId();
       
        System.debug('Current Logged in User Id Informaion');
       
                
        
        wrpexctnsptsLst = new List<TestExecutionSteps>();
        for(Test_Execution__c te: [select Id, Name,Execution_Date__c,Test_Executor__c,Execution_Type__c,Execution_Cycle_Name__r.OwnerId,CreatedBy.Id,Execution_Cycle_Name__c,Execution_Cycle_Name__r.Name,
                                    Execution_Cycle_Name__r.Release_Name__r.Name,Result__c,Status__c,Test_Script_Description__c,Description_of_Script__c,Test_Executor__r.name,Request_Description__c,
                                    (select Id, Name,Status__c,Actual_Result__c,Step_Order__c,Test_Execution_Name__r.Name,Test_Execution_Name__r.Execution_Cycle_Name__r.Release_Name__r.Name
                                      ,Test_Execution_Name__r.Execution_Cycle_Name__r.Name,Test_Execution_Name__r.Execution_Date__c,Input_Data__c,User_Login_Details__c,Expected_Result__c,Test_Execution_Name__r.Execution_Type__c
                                      from Test_Execution_Steps__r ORDER BY Step_Order__c ASC  )
                                    FROM Test_Execution__c 
                                    WHERE Execution_Cycle_Name__c =: apexpages.currentPage().getParameters().get('id')
                                    ]){
                                    
               if(te.Test_Executor__c == usrId){
                    testEctn.add(te);
               
                    for(Test_Execution_Steps__c testps: te.Test_Execution_Steps__r){
                      
                      
                        wrpexctnsptsLst.add(new TestExecutionSteps(testps,false));                 
                    } 
        
                //wrpexctnsptsLst.add(new TestExecutionSteps(te,tstExcstpLst,false));        
               }
           
            }
         
       tstExcstpLst = [Select id,Name,Actual_Result__c,Status__c,Step_Order__c, Expected_Result__c,Input_Data__c,User_Login_Details__c,Test_Execution_Name__c,
                       Test_Execution_Name__r.Comments__c,Test_Execution_Name__r.Status__c from Test_Execution_Steps__c 
                       where Test_Execution_Name__c IN: testEctn];
                       
                       System.debug('Execution steps list is>>>>>>>>>'+tstExcstpLst+'Size is******'+tstExcstpLst.size());
      
    }
    
    Public Void submitStpStaus(){
    
      if(stdController.save()!=null){ // This takes care of the details for you.
       PageReference pageRef = new PageReference('/');
       pageRef.setRedirect(false);      
      }
     
      
      
                   
     List<Test_Execution_Steps__c > stpLst = new List<Test_Execution_Steps__c >();
        for(TestExecutionSteps ts: wrpexctnsptsLst){
           {
                System.debug('Selected Test Execution Id is>>>>>'+ts.tes);
                stpLst.add(ts.tes);          
            }
        }
        
        if(stpLst.size()>0){
        try{
            Update stpLst;
            }Catch(Exception Ex){}
            }
        //System.debug('Execution step Id as follows>>>>>'+ExtsId);
        
    }
    
    Public class TestExecutionSteps{
        Public Boolean checkSelectd{get;set;}
        Public Test_Execution_Steps__c tes{get;set;}
        
        
        Public TestExecutionSteps(Test_Execution_Steps__c tstps, Boolean chs){        
            tes = tstps;
            checkSelectd = chs;
        }
        
    }
    public PageReference cancelB(){
    return null;

}
}