force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about Release</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Plan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Start_Date__c</fullName>
    <description>Estimated date of Start</description>
    <label>Plan Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release_Planned_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Planned_End_Date__c</fullName>
    <description>Estimated date of end of release</description>
    <label>Release Planned End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Value_Delivery_Objectives_Options__c/Value_Delivery_Objectives_Options__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Objectives Options</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Value Delivery Objectives Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Value Delivery Objectives Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Objectives_Options__c/fields/Objectives_and_Attendees_for_Participant__c.field-meta.xml
<CustomField>
    <fullName>Objectives_and_Attendees_for_Participant__c</fullName>
    <description>Objectives And Key Participants - Record type F</description>
    <label>Objectives and Attendees for Participant</label>
    <referenceTo>Value_Delivery_Setup__c</referenceTo>
    <relationshipLabel>Value Delivery Objectives Options</relationshipLabel>
    <relationshipName>Value_Delivery_Objectives_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Objectives_Options__c/fields/Option_Description__c.field-meta.xml
<CustomField>
    <fullName>Option_Description__c</fullName>
    <description>To Store Option Description</description>
    <label>Option Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Objectives_Options__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <description>To retrieve the option in order</description>
    <label>Sequence Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/Value_Delivery_Session__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session</label>
    <nameField>
        <label>Value Delivery Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>To store Session Details.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>To capture Value Delivery Session End Date And Time</description>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Releases__c.field-meta.xml
<CustomField>
    <fullName>Releases__c</fullName>
    <description>Add Session to The Existing Project</description>
    <label>Releases</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Value Delivery Sessions</relationshipLabel>
    <relationshipName>Value_Delivery_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>To capture Value Delivery Session Start Date And Time</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Setup__c/Value_Delivery_Setup__c.object-meta.xml
<CustomObject>
    <label>Objectives and Attendees for Participant</label>
    <nameField>
        <label>Value Delivery Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives and Attendees for Participant</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Setup__c/fields/Component_Title__c.field-meta.xml
<CustomField>
    <fullName>Component_Title__c</fullName>
    <label>Component Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Setup__c/fields/Project_Phase__c.field-meta.xml
<CustomField>
    <fullName>Project_Phase__c</fullName>
    <label>Project Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiate And Confirm</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Value_Delivery_Setup__c/fields/Sequence_Order__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Order__c</fullName>
    <label>Sequence Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Setup__c/fields/Value_Delivery_Session__c.field-meta.xml
<CustomField>
    <fullName>Value_Delivery_Session__c</fullName>
    <label>Value Delivery Session</label>
    <referenceTo>Value_Delivery_Session__c</referenceTo>
    <relationshipLabel>Objectives and Attendees for Participant</relationshipLabel>
    <relationshipName>Objectives_and_Attendees_for_Participant</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SaaSCreateSessionCtrlTest.cls
@isTest
public class SaaSCreateSessionCtrlTest
{
    public static testMethod void validateCreateSession() 
    {
        Release__c rel = new Release__c();
        rel.Name = 'Test Release ';
        rel.Id = null;
        rel.Plan_Start_Date__c = System.today();
        rel.Release_Planned_End_Date__c= System.today() + 10;
        rel.Status__c = 'Red';
        rel.Description__c = 'Test description ';
       
        insert rel;
        
        Value_Delivery_Session__c vds = new Value_Delivery_Session__c();
        vds.Description__c = 'test data';
        vds.Name='VALUE Delivery Session template';
        vds.End_Date__c = System.today() + 10; 
        vds.Start_Time__c=system.now();
        vds.Releases__c = rel.id;
        insert vds;
        
       Value_Delivery_Setup__c vds1 = new Value_Delivery_Setup__c();
      //vds1.TeamDescription__c= 'test Description' ;
       vds1.Value_Delivery_Session__c=vds.id;
      // vds1.Component_Content__c='test content';
       vds1.Component_Title__c='test title';  
      // vds1.Role__c='test role';
       vds1.Sequence_Order__c=25;
      // vds1.Team_Name__c='test name';
       vds1.Project_Phase__c='test';
       insert vds1;
       
       Value_Delivery_Objectives_Options__c Vdo1=new Value_Delivery_Objectives_Options__c();
       Vdo1.Option_Description__c='Test Description';
       Vdo1.Sequence_No__c=314564613;
       Vdo1.Objectives_and_Attendees_for_Participant__c=vds1.id;
       insert Vdo1; 
       
        Value_Delivery_Objectives_Options__c vdo2 = new Value_Delivery_Objectives_Options__c();
         
        vdo2.Objectives_and_Attendees_for_Participant__c = vds1.id;
       
        insert vdo2;
     
  
        SaasCreateSessionCtrl controller = new SaasCreateSessionCtrl();
        SaasCreateSessionCtrl.BusinessOptionWrpper objBusOpt = new SaasCreateSessionCtrl.BusinessOptionWrpper(vdo2);
        
        controller.selectedSession = 'existingSession';
        controller.selectPrjAndSessionSetp();
        controller.selectCreateSessionSetp();
        
        //controller.selectPrjAndSessionSetp();
        controller.validateSession();
        controller.createSessionPrevoiusStep();
        controller.releaseID =rel.id; 
        controller.createSessionPrevoiusStep();
        controller.sessionID =  vds.id;               
        controller.createSessionPrevoiusStep();
        controller.valueDeliverySesObj.Releases__c = rel.id; 

        controller.createSessionPrevoiusStep();        
        
        
        controller.createSessionNextStep();
        controller.valueDeliverySesObj.name = 'Test'; 
        controller.createSessionNextStep();
        controller.valueDeliverySesObj.name = 'Test';         
        controller.initlizeValueDeliverySession();
      
        controller.finish();
        controller.step1();
        controller.objectiveDetailPrevious();
        controller.previous();
        controller.getReleaseList1();
        controller.getdetailSession();
        controller.step1();
       
    }
    
    static testMethod void validateCreateSession1()
    {
        Release__c rel = new Release__c();
        rel.Name = 'Test Release ';
        rel.Id = null;
        rel.Plan_Start_Date__c = System.today();
        rel.Release_Planned_End_Date__c= System.today() + 10;
        rel.Status__c = 'Red';
        rel.Description__c = 'Test description ';
        insert rel;
        
        Value_Delivery_Session__c vds = new Value_Delivery_Session__c();
        vds.Name='VALUE Delivery Session template';
        vds.Description__c = 'test data';
        vds.End_Date__c = System.today() + 10; 
        vds.Start_Time__c=system.now();
        vds.Releases__c = rel.id;
        insert vds;
        
       Value_Delivery_Setup__c vds1 = new Value_Delivery_Setup__c();
      // vds1.TeamDescription__c= 'test Description' ;
       vds1.Value_Delivery_Session__c=vds.id;
     //  vds1.Component_Content__c='test content';
       vds1.Component_Title__c='test title';  
      // vds1.Role__c='test role';
       vds1.Sequence_Order__c=25;
     //  vds1.Team_Name__c='test name';
        vds1.Project_Phase__c='test';
       insert vds1;
       
       
        Value_Delivery_Objectives_Options__c vdo2 = new Value_Delivery_Objectives_Options__c();
         
        vdo2.Objectives_and_Attendees_for_Participant__c = vds1.id;
       
        insert vdo2;
       
       SaasCreateSessionCtrl controller = new SaasCreateSessionCtrl();
       SaasCreateSessionCtrl.BusinessOptionWrpper objBusOpt = new SaasCreateSessionCtrl.BusinessOptionWrpper(vdo2);
        
       controller.selectedSession = null;
       controller.releaseID =rel.id;
        controller.selectCreateSessionSetp();
        controller.selectPrjAndSessionSetp();
        controller.createSessionPrevoiusStep();
       controller.prjPhase = 'pagNo'; 
       controller.initlizeValueDeliverySession();
       controller.next();
       controller.previous();
       controller.cancel();
       
       
     
    }
    
    static testMethod void validateSession2()
    {
       Release__c rel = new Release__c();
        rel.Name = 'Test Release ';
        rel.Id = null;
        rel.Plan_Start_Date__c = System.today();
        rel.Release_Planned_End_Date__c= System.today() + 10;
        rel.Status__c = 'Red';
        rel.Description__c = 'Test description ';
        insert rel;
        
        Value_Delivery_Session__c vds = new Value_Delivery_Session__c();
        vds.Name='VALUE Delivery Session template';
        vds.Description__c = 'test data';
        vds.End_Date__c = System.today() + 10; 
        vds.Start_Time__c=system.now();
        vds.Releases__c = rel.id;
        insert vds;
        
        
        
       Value_Delivery_Setup__c vds1 = new Value_Delivery_Setup__c();
     //vds1.TeamDescription__c= 'test Description' ;
       vds1.Value_Delivery_Session__c=vds.id;
   //    vds1.Component_Content__c='test content';
       vds1.Component_Title__c='test title';  
   //    vds1.Role__c='test role';
       vds1.Sequence_Order__c=25;
   //    vds1.Team_Name__c='test name';
       vds1.Project_Phase__c='test';
       
       insert vds1; 
       
        Value_Delivery_Objectives_Options__c vdo2 = new Value_Delivery_Objectives_Options__c();
         
        vdo2.Objectives_and_Attendees_for_Participant__c = vds1.id;
       
        insert vdo2;
        
       // BusinessOptionWrpper objBusOpt = new BusinessOptionWrpper(vdo2);
        
        SaasCreateSessionCtrl controller = new SaasCreateSessionCtrl();
        SaasCreateSessionCtrl.BusinessOptionWrpper objBusOpt = new SaasCreateSessionCtrl.BusinessOptionWrpper(vdo2);
        controller.selectedSession = 'template';
        controller.selectCreateSessionSetp();
        
        controller.sessonStartDate=system.now();
        controller.sessonEndDate=System.today() + 10;
       
    }
    public static testMethod void validateCreateSession2() 
    {
        Release__c rel = new Release__c();
        rel.Name = 'Test Release ';
        rel.Id = null;
        rel.Plan_Start_Date__c = System.today();
        rel.Release_Planned_End_Date__c= System.today() + 10;
        rel.Status__c = 'Red';
        rel.Description__c = 'Test description ';
       
        insert rel;
        
        Value_Delivery_Session__c vds = new Value_Delivery_Session__c();
        vds.Description__c = 'test data';
        vds.Name='VALUE Delivery Session template';
        vds.End_Date__c = System.today() + 10; 
        vds.Start_Time__c=system.now();
        vds.Releases__c = rel.id;
        insert vds;
        
       Value_Delivery_Setup__c vds1 = new Value_Delivery_Setup__c();
     //  vds1.TeamDescription__c= 'test Description' ;
       vds1.Value_Delivery_Session__c=vds.id;
     //  vds1.Component_Content__c='test content';
       vds1.Component_Title__c='test title';  
     //  vds1.Role__c='test role';
       vds1.Sequence_Order__c=25;
    //   vds1.Team_Name__c='test name';
       vds1.Project_Phase__c=null;
       insert vds1;
       
       Value_Delivery_Objectives_Options__c Vdo1=new Value_Delivery_Objectives_Options__c();
       Vdo1.Option_Description__c='Test Description';
       Vdo1.Sequence_No__c=314564613;
       Vdo1.Objectives_and_Attendees_for_Participant__c=vds1.id;
       insert Vdo1; 
       
        Value_Delivery_Objectives_Options__c vdo2 = new Value_Delivery_Objectives_Options__c();
         
        vdo2.Objectives_and_Attendees_for_Participant__c = vds1.id;
       
        insert vdo2;
     
  
        SaasCreateSessionCtrl controller = new SaasCreateSessionCtrl();
       // SaasCreateSessionCtrl.BusinessOptionWrpper objBusOpt = new SaasCreateSessionCtrl.BusinessOptionWrpper(vdo2);
        
        controller.selectedSession = 'existingSession';
        controller.selectPrjAndSessionSetp();
        controller.selectCreateSessionSetp();
        
        //controller.selectPrjAndSessionSetp();
        controller.validateSession();
        controller.createSessionPrevoiusStep();
        controller.releaseID =rel.id; 
        controller.createSessionPrevoiusStep();
        controller.sessionID =  vds.id;               
        controller.createSessionPrevoiusStep();
        controller.valueDeliverySesObj.Releases__c = rel.id; 

        controller.createSessionPrevoiusStep();        
        
        
        controller.createSessionNextStep();
        controller.valueDeliverySesObj.name = 'Test'; 
        controller.createSessionNextStep();
        controller.valueDeliverySesObj.name = 'Test';         
        controller.initlizeValueDeliverySession();
        controller.finish();
        controller.step1();
        controller.objectiveDetailPrevious();
        controller.previous();
        controller.getReleaseList1();
        controller.getdetailSession();
        controller.step1();
       
    }
}