force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about Release</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Design__c.field-meta.xml
<CustomField>
    <fullName>Design__c</fullName>
    <description>Number of days required for design</description>
    <label>Design</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Objectives_Options__c/Value_Delivery_Objectives_Options__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Objectives Options</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Value Delivery Objectives Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Value Delivery Objectives Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Objectives_Options__c/fields/Objectives_and_Attendees_for_Participant__c.field-meta.xml
<CustomField>
    <fullName>Objectives_and_Attendees_for_Participant__c</fullName>
    <description>Objectives And Key Participants - Record type F</description>
    <label>Objectives and Attendees for Participant</label>
    <referenceTo>Value_Delivery_Setup__c</referenceTo>
    <relationshipLabel>Value Delivery Objectives Options</relationshipLabel>
    <relationshipName>Value_Delivery_Objectives_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Objectives_Options__c/fields/Option_Description__c.field-meta.xml
<CustomField>
    <fullName>Option_Description__c</fullName>
    <description>To Store Option Description</description>
    <label>Option Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Objectives_Options__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <description>To retrieve the option in order</description>
    <label>Sequence Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/Value_Delivery_Session__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session</label>
    <nameField>
        <label>Value Delivery Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>To store Session Details.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>To capture Value Delivery Session End Date And Time</description>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Releases__c.field-meta.xml
<CustomField>
    <fullName>Releases__c</fullName>
    <description>Add Session to The Existing Project</description>
    <label>Releases</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Value Delivery Sessions</relationshipLabel>
    <relationshipName>Value_Delivery_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>To capture Value Delivery Session Start Date And Time</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Setup__c/Value_Delivery_Setup__c.object-meta.xml
<CustomObject>
    <label>Objectives and Attendees for Participant</label>
    <nameField>
        <label>Value Delivery Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives and Attendees for Participant</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Setup__c/fields/Component_Title__c.field-meta.xml
<CustomField>
    <fullName>Component_Title__c</fullName>
    <label>Component Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Setup__c/fields/Project_Phase__c.field-meta.xml
<CustomField>
    <fullName>Project_Phase__c</fullName>
    <label>Project Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiate And Confirm</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Value_Delivery_Setup__c/fields/Sequence_Order__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Order__c</fullName>
    <label>Sequence Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Setup__c/fields/Value_Delivery_Session__c.field-meta.xml
<CustomField>
    <fullName>Value_Delivery_Session__c</fullName>
    <label>Value Delivery Session</label>
    <referenceTo>Value_Delivery_Session__c</referenceTo>
    <relationshipLabel>Objectives and Attendees for Participant</relationshipLabel>
    <relationshipName>Objectives_and_Attendees_for_Participant</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_User_Config__c/Value_Delivery_User_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Value Delivery User Config</label>
</CustomObject>

force-app/main/default/objects/Value_Delivery_User_Config__c/fields/Selected_Session__c.field-meta.xml
<CustomField>
    <fullName>Selected_Session__c</fullName>
    <label>Selected Session</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SaaSOverviewCompCtrlTest.cls
/** 
 *  Author : Accenture 
 *  Description : Test class for SaaSOverviewCompCtrl
 *  Created Date : 01\10\2015
 * 
 *  
 *
 */ 

@istest
private class SaaSOverviewCompCtrlTest
{
 static testMethod void UnitMethod() {
 
     string itemkey;
     itemkey= SaaSUtility.getURLParameter(SaaSTextConstant.VALUE_DELIVERY_OPTIONS_ID_URL_PARAM);

     Release__c release = new Release__c(Name ='test',Design__c =1,Release__c =12);
     insert release;
     Value_Delivery_Session__c ValueDeliverySetup = new Value_Delivery_Session__c(Description__c ='testing',End_Date__c = system.today()+10,Start_Time__c =system.today(),Releases__c = release.ID);
     insert ValueDeliverySetup;
     
     Value_Delivery_Setup__c vds = new Value_Delivery_Setup__c(Id=itemkey,name ='Test Delivery',Project_Phase__c='Initiate and Confirm',Value_Delivery_Session__c=ValueDeliverySetup.ID,Component_Title__c = 'Test Component',Sequence_Order__c=1);
     insert vds;
     
     Value_Delivery_Setup__c vdsp = new Value_Delivery_Setup__c(name ='Test Delivery',Project_Phase__c='Initiate and Confirm',Value_Delivery_Session__c=ValueDeliverySetup.ID,Component_Title__c = 'Test Component',Sequence_Order__c=1);
     insert vdsp;
     
     Value_Delivery_Objectives_Options__c  deliverysetup = new Value_Delivery_Objectives_Options__c (Objectives_and_Attendees_for_Participant__c=vds.Id,Id=itemkey,Sequence_No__c =1,Option_Description__c ='test');
     insert deliverysetup;
     
     Value_Delivery_User_Config__c vdU = new Value_Delivery_User_Config__c();
     vdu.Name = 'TestUser';           
     vdu.Selected_Session__c = ValueDeliverySetup.id;
     insert vdu;

     ApexPages.CurrentPage().getparameters().put('valueDeliveryOptionsID', deliverysetup.id);
     ApexPages.CurrentPage().getparameters().put('valueDeliveryObjID', vds.id);  

     SaaSOverviewCompCtrl Comp= new SaaSOverviewCompCtrl();
     comp.newObjectivesOptions = deliverysetup;     
     comp.valueDeliveryObjectiveObj = vds;
     comp.valueDeliveryObj = vds;
     comp.itemList = vds;
     List<String> lst = new List<String>{'test'};   
     comp.mapKeys = lst;
     
     List<Value_Delivery_Setup__c> stp = comp.overViewDetail;
     comp.dynamciContentLst = stp;

     comp.getValueDeliveryOption();
     
     
     comp.addValueDelivery();           
     comp.valueDeliveryObj = new Value_Delivery_Setup__c();
     comp.valueDeliveryObj.Component_Title__c ='Test';
     comp.valueDeliveryObj.Sequence_Order__c =1;
     comp.bussinesOnjectiveOption = 'ss \n dd';
     
     comp.addValueDelivery();           
     comp.valueDeliveryObj = new Value_Delivery_Setup__c();
     comp.valueDeliveryObj.Component_Title__c ='Test';
     comp.valueDeliveryObj.Sequence_Order__c =-1;
     comp.bussinesOnjectiveOption = 'ss \n dd';
     
     comp.addValueDelivery();           
     
     comp.updateValueDeliveryObjective();
     
     comp.insertBusinessOption();
     comp.updateValueDeliveryOption();
     comp.getValueDeliveryObjective();
     comp.deleteValueDeliveryObjective();
     comp.deleteValueDeliveryOption();
     
     comp.assignBusinessObjectiveID();
          
   }
    
    static testMethod void UnitMethodNegative() {
 
     string itemkey;
     itemkey= SaaSUtility.getURLParameter(SaaSTextConstant.VALUE_DELIVERY_OPTIONS_ID_URL_PARAM);

     Release__c release = new Release__c(Name ='test',Design__c =1,Release__c =12);
     insert release;
     Value_Delivery_Session__c ValueDeliverySetup = new Value_Delivery_Session__c(Description__c ='testing',End_Date__c = system.today()+10,Start_Time__c =system.today(),Releases__c = release.ID);
     insert ValueDeliverySetup;
     
     Value_Delivery_Setup__c vds = new Value_Delivery_Setup__c(Id=itemkey,name ='Test Delivery',Project_Phase__c='Initiate and Confirm',Value_Delivery_Session__c=ValueDeliverySetup.ID,Component_Title__c = '',Sequence_Order__c=-1);
     insert vds;
     
     Value_Delivery_Setup__c vdsp = new Value_Delivery_Setup__c(name ='Test Delivery',Project_Phase__c='Initiate and Confirm',Value_Delivery_Session__c=ValueDeliverySetup.ID,Component_Title__c = 'Test Component');
     //insert vdsp;
     
     Value_Delivery_Objectives_Options__c  deliverysetup = new Value_Delivery_Objectives_Options__c (Objectives_and_Attendees_for_Participant__c=vds.Id,Id=itemkey,Sequence_No__c =1,Option_Description__c ='');
     insert deliverysetup;
     
     Value_Delivery_User_Config__c vdU = new Value_Delivery_User_Config__c();
     vdu.Name = 'TestUser';           
     vdu.Selected_Session__c = ValueDeliverySetup.id;
     insert vdu;
     
     ApexPages.CurrentPage().getparameters().put('valueDeliveryOptionsID', deliverysetup.id);
     ApexPages.CurrentPage().getparameters().put('valueDeliveryObjID', vds.id);  

     SaaSOverviewCompCtrl Comp= new SaaSOverviewCompCtrl();
     comp.newObjectivesOptions = deliverysetup;     
     comp.valueDeliveryObjectiveObj = vds;
     comp.valueDeliveryObj = vdsp;
     comp.itemList = vds;
     comp.updateValueDeliveryObjective(); 
        
     comp.valueDeliveryObjectiveObj = vdsp;
     comp.deleteValueDeliveryObjective();  
          
     comp.valueDelOptionObj = deliverysetup;
     comp.updateValueDeliveryOption();
     comp.insertBusinessOption();  
     comp.getValueDeliveryObjective();   
   }
    
}