force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session__c/Value_Delivery_Session__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session</label>
    <nameField>
        <label>Value Delivery Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_User_Config__c/Value_Delivery_User_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Value Delivery User Config</label>
</CustomObject>

force-app/main/default/objects/Value_Delivery_User_Config__c/fields/Selected_Session__c.field-meta.xml
<CustomField>
    <fullName>Selected_Session__c</fullName>
    <label>Selected Session</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SaaSValueDeliveryCtrlTest.cls
/** 
 *  Author : Accenture 
 *  Description : Test class for SaaSCreateUserStoriesCtrl
 *  Created Date : 11\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  08\06\2015        created 
 *
 */
@isTest
public class SaaSValueDeliveryCtrlTest 
{
   static testMethod void ValidateSaaSValueDeliveryCtrl()
   {
       Release__c rel = SaaSTestUtility.createRelease();
       Value_Delivery_Session__c sessiom  = SaaSTestUtility.createValueDeliverySession(rel);
       
       Value_Delivery_User_Config__c vdU = new Value_Delivery_User_Config__c();
       vdu.Name = 'TestUser';      
       vdu.Selected_Session__c= sessiom.id;
       insert vdu;
       
       SaaSValueDeliveryCtrl vdc = new SaaSValueDeliveryCtrl();      
       vdc.getReleases();      
        vdc.updateValueDelSession();
       vdc.releaseID = rel.id;
       vdc.updateValueDelSession();       
       vdc.sessionID = vdu.id;
       vdc.updateValueDelSession();       
       List<SelectOption> opt = vdc.getSession();
       vdc.updateValueDelSession();
   }
  
}