force-app/main/default/objects/Question_Log__c/Question_Log__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a question that a project team member has about a request.</description>
    <label>Question Log</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Question Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Log__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <description>Answer for the Question Log</description>
    <label>Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Detailed question.</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related request to the question log</description>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Question Log</relationshipLabel>
    <relationshipName>Question_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of Question Log</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Clarification Requested</fullName>
            </value>
            <value>
                <fullName>Clarification Provided</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_Request__c/Related_Request__c.object-meta.xml
<CustomObject>
    <label>Related Request</label>
    <nameField>
        <displayFormat>RR-{000000}</displayFormat>
        <label>Related Request Numbers</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Request__c/fields/Converted_Request__c.field-meta.xml
<CustomField>
    <fullName>Converted_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Related_Request__c/fields/Question_Log__c.field-meta.xml
<CustomField>
    <fullName>Question_Log__c</fullName>
    <label>Question Log</label>
    <referenceTo>Question_Log__c</referenceTo>
    <relationshipLabel>Related Requests</relationshipLabel>
    <relationshipName>Related_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_Request__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Related Requests</relationshipLabel>
    <relationshipName>Related_Requests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <description>Answer from Functional team for the Questions raised from Norfolk</description>
    <label>Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Question to be raised with Functional team</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Related_Request__c.field-meta.xml
<CustomField>
    <fullName>Related_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Requests (Related Request)</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Release in which the request will go</description>
    <inlineHelpText>The release in which the request will actually be deployed. If the requirement has not been approved for a release, there should not be a value in this field.</inlineHelpText>
    <label>Committed Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Requests (Committed Release)</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Description__c.field-meta.xml
<CustomField>
    <fullName>Request_Description__c</fullName>
    <description>Gathers further details for requirements.</description>
    <inlineHelpText>Detailed Summary* 
Screen(s) Impacted* 
Field Name(s) &amp; Type(s)* 
Picklist Values 
Calculation 
Dependency 
Workflow/Approval Rules 
Interfacing System Updates 
Interface Frequency 
Data Volumes 
*Indicates information required for all requests!</inlineHelpText>
    <label>Initial Request</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>Type of the request</description>
    <inlineHelpText>If you are unsure of the type of request you are submitting, please select Unknown.</inlineHelpText>
    <label>Request Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Configuration</fullName>
            </value>
            <value>
                <fullName>Custom Code</fullName>
            </value>
            <value>
                <fullName>Data Access</fullName>
            </value>
            <value>
                <fullName>Data Migration</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>User Administration</fullName>
            </value>
            <value>
                <fullName>User Story</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the request</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Identify: New Requirement</fullName>
                <default>true</default>
                <label>Identify: New Requirement</label>
            </value>
            <value>
                <fullName>Identify: Submit for Business Review</fullName>
            </value>
            <value>
                <fullName>Identify: Deferred</fullName>
            </value>
            <value>
                <fullName>Consolidate: Approve to Estimate</fullName>
            </value>
            <value>
                <fullName>Consolidate: Level of Effort Complete</fullName>
            </value>
            <value>
                <fullName>Approve: Approved to Deploy</fullName>
            </value>
            <value>
                <fullName>Release: Design</fullName>
            </value>
            <value>
                <fullName>Release: Build</fullName>
            </value>
            <value>
                <fullName>Release: Test</fullName>
            </value>
            <value>
                <fullName>Release: SIT</fullName>
            </value>
            <value>
                <fullName>Release: UAT</fullName>
            </value>
            <value>
                <fullName>Release: Build Production</fullName>
            </value>
            <value>
                <fullName>Release: Test Production</fullName>
            </value>
            <value>
                <fullName>Close: Deployed</fullName>
            </value>
            <value>
                <fullName>Close: Rejected</fullName>
            </value>
            <value>
                <fullName>Close: Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/recordTypes/Question.recordType-meta.xml
<RecordType>
    <fullName>Question</fullName>
    <active>true</active>
    <description>Question to be raised with Functional team</description>
    <label>Question</label>
</RecordType>

force-app/main/default/classes/SaaSCreateRequestCtrl.cls
/** 
 *  Author : Accenture 
 *  Description : Controller class for SaaSCreateRequest
 *  Created Date : 05\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  05\06\2015        created 
 *
 */
public class SaaSCreateRequestCtrl
{
    private Boolean isConvertToReq = false; 
    public Boolean isSaved {get;set;}    
    public Request__c requestObj  {get;set;}
    public List<Release__c> releaseLst {get;set;} 
    //public Id reqid {get;set;}
    public Boolean isDetail {get;set;}
    private Related_Request__c relatRequest;
    
   /**
    * Construtor 
    * @param ApexPages.StandardController controller
    *
    */    
    public SaaSCreateRequestCtrl(ApexPages.StandardController controller)
    {
        Boolean isClone = false; 
        Request__c tempRequest = null;
        String release = null;
        isSaved  = false;        
        List<Request__c>  requestLst = null;        
        isClone  = SaaSUtility.getURLParameter(SaaSTextConstant.IS_CLONE_URL_PARAM) == SaaSTextConstant.NUMERIC_ONE ?true:false;
        isConvertToReq = SaaSUtility.getURLParameter(SaaSTextConstant.CONVERT_QUEST) == SaaSTextConstant.NUMERIC_ONE ?true:false;     
        isDetail = SaaSUtility.getURLParameter(SaaSTextConstant.DETAIL_URL_PARAM ) == SaaSTextConstant.NUMERIC_ONE  ?true:false;     
        release =  SaaSUtility.getURLParameter(SaaSTextConstant.RELEASEID_URL_PARAM );
        
              
        tempRequest = (Request__c )controller.getRecord();
        
        // Check if this is edit mode
        if(tempRequest.id != null )
        {
            requestLst = Database.query(SaaSUtility.getCreatableFieldsSOQL(SaaSTextConstant.REQUEST_OBJ_API_NAME , 'id=\''+tempRequest.id+'\''));
            if(requestLst.size() > 0)
            {
                requestObj = requestLst.get(0);  
            }
        }  
        else 
        {
            requestObj= new Request__c();
        }  
              
        if(isClone)
        {
            requestObj= requestObj.clone();
            requestObj.ownerID = Userinfo.getUserID();
        }               
        // Check if Question has to be converted to Request 
        if(isConvertToReq)
        {
            String questionID = SaaSUtility.getURLParameter(SaaSTextConstant.CONVERT_QUEST_ID);
            List<Question_Log__c> questionLst =  [Select id,Question__c, answer__c from Question_Log__c where id =:questionID ];

            if(questionLst.size () > 0)
            {
                relatRequest = new Related_Request__c();
                relatRequest.Question_Log__c =  questionLst.get(0).id;
                requestObj.Request_Description__c = SaaSTextConstant.QUESTION + SaaSTextConstant.NEXT_LINE + questionLst.get(0).Question__c;
                requestObj.Request_Description__c  =  requestObj.Request_Description__c +   SaaSTextConstant.NEXT_LINE+  SaaSTextConstant.RESPONSE;
                requestObj.Request_Description__c  =  requestObj.Request_Description__c +   (questionLst.get(0).answer__c!= null?questionLst.get(0).answer__c :'') ;
            }
        }
        if(release !=null && release.trim() != SaaSTextConstant.EMPTY_STRING )
        {
            requestObj.Release__c = release ;
        }

        
       
        
    }
   
   /**
    * Save the Request record
    * @return 
    *
    */                   
    public PageReference saveRequest() 
    {                
        PageReference pageRef= null;        
        String errMSg = null;
        try
        {         
            errMSg  =  validateKeyDecision();
            if(errMSg   != null)
            {
                 SaaSUtility.displayErrMsg(errMSg);           
                return null;
            }                             
            upsert requestObj;            
            if(isConvertToReq &&relatRequest !=null && relatRequest.Question_Log__c!=null )
            {
                relatRequest.Converted_Request__c = true;
                relatRequest.Request__c = requestObj.id;
                upsert relatRequest;
            }     
            SaaSUtility.displaySuccessMsg(SaaSTextConstant.REQUEST_RECORD_SAVE_MSG); 
            isSaved  = true;            
        }
        catch(DmlException e)
        {
            SaaSUtility.displayErrMsg(e.getDmlMessage(0) );           
        } 
        catch(Exception e)
        {
            SaaSUtility.displayErrMsg(SaaSTextConstant.EXCEPTION_ERR_MSG );         
            e.getMessage();        
        }
        return pageRef;
    }  
    
  
   /**
    * Validate the data entered by the user.
    * @return String errmsg
    *
    */       
    @TestVisible private String validateKeyDecision()
    {
        String errMsg = null;                          
        if(requestObj.Status__c==Null || requestObj.Status__c==SaaSTextConstant.EMPTY_STRING)
        {
            errMsg =    SaaSTextConstant.REQUEST_STATUS_EMPTY_ERR_MSG;
        }
            
        if(requestObj.Request_Description__c== Null || requestObj.Request_Description__c==SaaSTextConstant.EMPTY_STRING)
        {
            errMsg =    SaaSTextConstant.REQUEST_DESC_EMPTY_ERR_MSG; 
        }
         
        if(requestObj.Release__c== Null || requestObj.Release__c+''==SaaSTextConstant.EMPTY_STRING)
        {
            errMsg =    SaaSTextConstant.REQUEST_PLANNED_RELEASE_EMPTY_ERR_MSG; 
        }
            
        if(requestObj.Request_Type__c== Null || requestObj.Request_Type__c==SaaSTextConstant.EMPTY_STRING)
        {
            errMsg =    SaaSTextConstant.REQUEST_TYPE_EMPTY_ERR_MSG; 
        }            
        return errMsg; 
    }   
     /**
    * Create new Request
    * 
    *    
    */    
    public void createNewRequest()
    {
        isDetail = false;
        requestObj = new   Request__c ();
    }              
}