force-app/main/default/objects/Question_Log__c/Question_Log__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a question that a project team member has about a request.</description>
    <label>Question Log</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Question Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related request to the question log</description>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Question Log</relationshipLabel>
    <relationshipName>Question_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Request__c/Related_Request__c.object-meta.xml
<CustomObject>
    <label>Related Request</label>
    <nameField>
        <displayFormat>RR-{000000}</displayFormat>
        <label>Related Request Numbers</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Request__c/fields/Question_Log__c.field-meta.xml
<CustomField>
    <fullName>Question_Log__c</fullName>
    <label>Question Log</label>
    <referenceTo>Question_Log__c</referenceTo>
    <relationshipLabel>Related Requests</relationshipLabel>
    <relationshipName>Related_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_Request__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Related Requests</relationshipLabel>
    <relationshipName>Related_Requests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Related_Request__c.field-meta.xml
<CustomField>
    <fullName>Related_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Requests (Related Request)</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/recordTypes/Question.recordType-meta.xml
<RecordType>
    <fullName>Question</fullName>
    <active>true</active>
    <description>Question to be raised with Functional team</description>
    <label>Question</label>
</RecordType>

force-app/main/default/classes/RelatedRequestTriggerUtility.cls
/*------------------------------------------------------------
Author:        Accenture IDC
Company:       Accenture
Description:   This is Handler class for Question Log Trigger
Test Class:    TBD : The name of the test class that is used to verify its function
History
<Date>      <Authors Name>     <Brief Description of Change>
15/06/2015  Accenture IDC       Initial Draft
------------------------------------------------------------*/
public without sharing class RelatedRequestTriggerUtility {

    public static void IsRelatedRequestDuplicate(List<Related_Request__c> lTriggerNew)
        {
        set<Id> RequestIds = new set<Id>();          
         
          for(Related_Request__c objrr : lTriggerNew)
            {
            RequestIds.add(objrr.Request__c);
            }

            List<Related_Request__c> lstrr = [SELECT Name, Request__c, Question_Log__c FROM Related_Request__c Where Request__c =: RequestIds];
            
            for(Related_Request__c rrobj : lstrr)
                {
                if(rrobj.Question_Log__c == lTriggerNew[0].Question_Log__c){
                        Trigger.new[0].addError('Combination of selected Request and Question Log is already exist.');                            
                    }               
                }
            }
}