force-app/main/default/objects/Question_Log__c/Question_Log__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a question that a project team member has about a request.</description>
    <label>Question Log</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Question Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Log__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <description>Answer for the Question Log</description>
    <label>Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Detailed question.</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related request to the question log</description>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Question Log</relationshipLabel>
    <relationshipName>Question_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of Question Log</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Clarification Requested</fullName>
            </value>
            <value>
                <fullName>Clarification Provided</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_Request__c/Related_Request__c.object-meta.xml
<CustomObject>
    <label>Related Request</label>
    <nameField>
        <displayFormat>RR-{000000}</displayFormat>
        <label>Related Request Numbers</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Request__c/fields/Converted_Request__c.field-meta.xml
<CustomField>
    <fullName>Converted_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Related_Request__c/fields/Question_Log__c.field-meta.xml
<CustomField>
    <fullName>Question_Log__c</fullName>
    <label>Question Log</label>
    <referenceTo>Question_Log__c</referenceTo>
    <relationshipLabel>Related Requests</relationshipLabel>
    <relationshipName>Related_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_Request__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Related Requests</relationshipLabel>
    <relationshipName>Related_Requests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <description>Answer from Functional team for the Questions raised from Norfolk</description>
    <label>Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Closed_Deferred__c.field-meta.xml
<CustomField>
    <fullName>Closed_Deferred__c</fullName>
    <description>Reason of closing or deferring the request</description>
    <label>Reason Closed/Deferred</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deferred: Waiting Architecture Availabiity</fullName>
            </value>
            <value>
                <fullName>Deferred: Product Enhancement Request</fullName>
            </value>
            <value>
                <fullName>Deferred: Waiting Approval</fullName>
            </value>
            <value>
                <fullName>Closed: Architecturally Not Recommended</fullName>
            </value>
            <value>
                <fullName>Closed: Satisfied Through Business Process Change</fullName>
            </value>
            <value>
                <fullName>Closed: Canceled by Business</fullName>
            </value>
            <value>
                <fullName>Closed: Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed: Technically Not Feasible</fullName>
            </value>
            <value>
                <fullName>Closed: Existing Functionality</fullName>
            </value>
            <value>
                <fullName>Deferred: Aligned to Future State Capabilities</fullName>
            </value>
            <value>
                <fullName>Closed: Consolidated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Question to be raised with Functional team</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Related_Request__c.field-meta.xml
<CustomField>
    <fullName>Related_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Requests (Related Request)</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Description__c.field-meta.xml
<CustomField>
    <fullName>Request_Description__c</fullName>
    <description>Gathers further details for requirements.</description>
    <inlineHelpText>Detailed Summary* 
Screen(s) Impacted* 
Field Name(s) &amp; Type(s)* 
Picklist Values 
Calculation 
Dependency 
Workflow/Approval Rules 
Interfacing System Updates 
Interface Frequency 
Data Volumes 
*Indicates information required for all requests!</inlineHelpText>
    <label>Initial Request</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the request</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Identify: New Requirement</fullName>
                <default>true</default>
                <label>Identify: New Requirement</label>
            </value>
            <value>
                <fullName>Identify: Submit for Business Review</fullName>
            </value>
            <value>
                <fullName>Identify: Deferred</fullName>
            </value>
            <value>
                <fullName>Consolidate: Approve to Estimate</fullName>
            </value>
            <value>
                <fullName>Consolidate: Level of Effort Complete</fullName>
            </value>
            <value>
                <fullName>Approve: Approved to Deploy</fullName>
            </value>
            <value>
                <fullName>Release: Design</fullName>
            </value>
            <value>
                <fullName>Release: Build</fullName>
            </value>
            <value>
                <fullName>Release: Test</fullName>
            </value>
            <value>
                <fullName>Release: SIT</fullName>
            </value>
            <value>
                <fullName>Release: UAT</fullName>
            </value>
            <value>
                <fullName>Release: Build Production</fullName>
            </value>
            <value>
                <fullName>Release: Test Production</fullName>
            </value>
            <value>
                <fullName>Close: Deployed</fullName>
            </value>
            <value>
                <fullName>Close: Rejected</fullName>
            </value>
            <value>
                <fullName>Close: Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/recordTypes/Question.recordType-meta.xml
<RecordType>
    <fullName>Question</fullName>
    <active>true</active>
    <description>Question to be raised with Functional team</description>
    <label>Question</label>
</RecordType>

force-app/main/default/classes/QuestionToRequestConversion.cls
public with sharing class QuestionToRequestConversion {

   Public Question_Log__c QuestionLog {get; set;}
   
    //Public List<Response__c> Responses {get; set;}
    
    public Request__c reqst { get; set; }

     public Related_Request__c RelatedRequest;
    
    public string QUESTIONANDANSWER {get; set;}
    
    public QuestionToRequestConversion(ApexPages.StandardController standardController) {
        
        String theId = ApexPages.currentPage().getParameters().get('id');
        reqst = new Request__c();
        QuestionLog = [Select Id, Name,Question__C,Answer__c from Question_Log__c where Id =:theId];
        
        QUESTIONANDANSWER = 'Question :' +  QuestionLog.Question__C+'\n\n' + 'Answer:' +  QuestionLog.Answer__C;
        
        reqst.Request_Description__c = QUESTIONANDANSWER;
        
        //Responses = [Select Id, Name, Response__c,Average_Rating__C,Question_Log__r.Question__C from Response__c  where Question_Log__r.Id =:theId ORDER BY Average_Rating__C DESC NULLS LAST ];    

        /*QUESTIONANDANSWER = 'Question :' +  Responses[0].Question_Log__r.Question__C+'\n\n'+ 'Response :' +  Responses[0].Response__c;
        
        reqst.Request_Description__c = QUESTIONANDANSWER;*/
        
        RelatedRequest = new Related_Request__c();
        
        RelatedRequest.Question_Log__c=  QuestionLog.id;
        RelatedRequest.Request__c =  QuestionLog.id;
        RelatedRequest.Converted_Request__c = true;
    }


     public PageReference save() {
         
         if(reqst.Status__c == 'Identify: Deferred' || reqst.Status__c == 'Close: Rejected' || reqst.Status__c == 'Close: Duplicate' )
         {
             if(reqst.Closed_Deferred__c == '')
             {
             reqst.Closed_Deferred__c.addError( 'You must pick a value for the Closed/Deferred Reason.');
             return null;
             }
             
         }
        
         
        try
        {
        
         insert reqst;
        } catch(DMLException e){
            
            
           ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getdmlMessage(0));
            ApexPages.addMessage(myMsg);
            return null;
        }
         QuestionLog.Request__c = reqst.Id;
         update QuestionLog;
         
         RelatedRequest.Request__c = reqst.Id;
         insert RelatedRequest;
         
         PageReference requestpage = new ApexPages.StandardController(reqst).view();
        
        requestpage.setRedirect(true);
        return requestpage;

     }
    
      public PageReference Cancel() {
         PageReference requestpage = new ApexPages.StandardController(QuestionLog).view();
        
        requestpage.setRedirect(true);
        return requestpage;
    }
}