force-app/main/default/objects/Question_Log__c/Question_Log__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a question that a project team member has about a request.</description>
    <label>Question Log</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Question Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Log__c/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <label>Domain</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Assets/Install Base</fullName>
            </value>
            <value>
                <fullName>Campaign Management</fullName>
            </value>
            <value>
                <fullName>Case Management</fullName>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>Communications Media and Technologies</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Currency Management</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Forecasting</fullName>
            </value>
            <value>
                <fullName>Lead Management</fullName>
            </value>
            <value>
                <fullName>Life Sciences</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Opportunity Management</fullName>
            </value>
            <value>
                <fullName>Outlook</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Reports and Dashboards</fullName>
            </value>
            <value>
                <fullName>Retail Marketing</fullName>
            </value>
            <value>
                <fullName>Search Marketing</fullName>
            </value>
            <value>
                <fullName>Tasks and Activities</fullName>
            </value>
            <value>
                <fullName>User Management</fullName>
            </value>
            <value>
                <fullName>Website Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Expected_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Close_Date__c</fullName>
    <description>Expected Closing Date for Question Log.</description>
    <label>Expected Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Communications, Media and Technology</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Health &amp; Public Services</fullName>
            </value>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Resources</fullName>
            </value>
            <value>
                <fullName>Cross-Industry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Detailed question.</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related request to the question log</description>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Question Log</relationshipLabel>
    <relationshipName>Question_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Date__c</fullName>
    <description>Date of request of Question Log</description>
    <label>Requested Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Plan and Analyze</fullName>
            </value>
            <value>
                <fullName>Scope</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Deploy</fullName>
            </value>
            <value>
                <fullName>Initiate and Confirm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Sub_Capability__c.field-meta.xml
<CustomField>
    <fullName>Sub_Capability__c</fullName>
    <label>Sub-Capability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Account Hierarchy</fullName>
            </value>
            <value>
                <fullName>Account Maintenance</fullName>
            </value>
            <value>
                <fullName>Account Ownership and Assignment</fullName>
            </value>
            <value>
                <fullName>Case Solutions</fullName>
            </value>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Custom Reports</fullName>
            </value>
            <value>
                <fullName>Dashboards</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Definition</fullName>
            </value>
            <value>
                <fullName>Email Marketing</fullName>
            </value>
            <value>
                <fullName>Fields</fullName>
            </value>
            <value>
                <fullName>Files and Attachments</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Knowledge Articles</fullName>
            </value>
            <value>
                <fullName>Lead Assignment</fullName>
            </value>
            <value>
                <fullName>Lead Conversion</fullName>
            </value>
            <value>
                <fullName>Lead Creation</fullName>
            </value>
            <value>
                <fullName>Lead Qualification</fullName>
            </value>
            <value>
                <fullName>Lead Source</fullName>
            </value>
            <value>
                <fullName>Lead Workflow Process</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Managing Multiple Currencies</fullName>
            </value>
            <value>
                <fullName>Ownership</fullName>
            </value>
            <value>
                <fullName>Page Layouts</fullName>
            </value>
            <value>
                <fullName>Permissions</fullName>
            </value>
            <value>
                <fullName>Pricing Book</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Product Catalog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Submitter__c.field-meta.xml
<CustomField>
    <fullName>Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who submitted the Question Log</description>
    <label>Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Question_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Request__c/Related_Request__c.object-meta.xml
<CustomObject>
    <label>Related Request</label>
    <nameField>
        <displayFormat>RR-{000000}</displayFormat>
        <label>Related Request Numbers</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Request__c/fields/Converted_Request__c.field-meta.xml
<CustomField>
    <fullName>Converted_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Related_Request__c/fields/Question_Log__c.field-meta.xml
<CustomField>
    <fullName>Question_Log__c</fullName>
    <label>Question Log</label>
    <referenceTo>Question_Log__c</referenceTo>
    <relationshipLabel>Related Requests</relationshipLabel>
    <relationshipName>Related_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_Request__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Related Requests</relationshipLabel>
    <relationshipName>Related_Requests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Question to be raised with Functional team</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Related_Request__c.field-meta.xml
<CustomField>
    <fullName>Related_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Requests (Related Request)</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Description__c.field-meta.xml
<CustomField>
    <fullName>Request_Description__c</fullName>
    <description>Gathers further details for requirements.</description>
    <inlineHelpText>Detailed Summary* 
Screen(s) Impacted* 
Field Name(s) &amp; Type(s)* 
Picklist Values 
Calculation 
Dependency 
Workflow/Approval Rules 
Interfacing System Updates 
Interface Frequency 
Data Volumes 
*Indicates information required for all requests!</inlineHelpText>
    <label>Initial Request</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/recordTypes/Question.recordType-meta.xml
<RecordType>
    <fullName>Question</fullName>
    <active>true</active>
    <description>Question to be raised with Functional team</description>
    <label>Question</label>
</RecordType>

force-app/main/default/classes/SaaSCreateQuestionLogCtrl.cls
/** 
 *  Author : Accenture 
 *  Description : Controller class for SaaSCreateQuestionLog
 *  Created Date : 05\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  05\06\2015        created 
 *
 */
public class SaaSCreateQuestionLogCtrl
{
    public  Question_Log__c QuesLogObj {get;set;}
    public Boolean isDetail {get;set;}
    public Boolean isCreate {get;set;}   
    public String questionType {get;set;}     
    public Date requestedDate{get;set;}
    public Date expectedCloseDate{get;set;}
    public Boolean disableRecType {get;set;}  
    public boolean showanswer {get;set;}  
  //  public Response__c userRespose {get;set;}
    public Id RecordToDelete {get; set;}
    public Boolean isSaved {get;set;}            
    public Boolean isAccentureRepresentative{get;set;}
    
    
   /**
    * Constructor   
    * @param args ApexPages.StandardController.
    *
    */   
    public SaaSCreateQuestionLogCtrl(ApexPages.StandardController controller) 
    {
     
        String requestID = null;
        List<Question_Log__c> questionLogLst = null;
        Boolean isClone = false; 
        Question_Log__c tempQuestObj = null;
        questionType =SaaSTextConstant.EMPTY_STRING;
        isAccentureRepresentative= SaaSUtility.isAccentureRepresentative();
        showanswer = false;
        isCreate = false;
        isSaved = false;
        isDetail = SaaSUtility.getURLParameter(SaaSTextConstant.DETAIL_URL_PARAM ) ==  SaaSTextConstant.NUMERIC_ONE ?true:false;
        isClone =   SaaSUtility.getURLParameter(SaaSTextConstant.IS_CLONE_URL_PARAM) ==  SaaSTextConstant.NUMERIC_ONE ? true :false; 
        disableRecType = isDetail? true :false;
        
        tempQuestObj = (Question_Log__c)controller.getRecord();   
        requestID  = SaaSUtility.getURLParameter(SaaSTextConstant.REQUEST_ID_URL_PARAM);
      //  questionType = (tempQuestObj.id != null)?tempQuestObj.RecordType.developerName:SaaSTextConstant.EMPTY_STRING;

        if(tempQuestObj.id != null )
        {
            questionLogLst = Database.query(SaaSUtility.getCreatableFieldsSOQL(SaaSTextConstant.QUESTION_OBJ_API_NAME, 'id=\''+tempQuestObj.id+'\''));
            if(questionLogLst.size() > 0)
            {
                quesLogObj = questionLogLst.get(0);  
                questionType  = SaaSUtility.getRecordTypeDeveloperName(questionLogLst.get(0).recordTypeID);
                requestedDate =   questionLogLst.get(0).Requested_Date__c;
                expectedCloseDate =   questionLogLst.get(0).Expected_Close_Date__c;  
            /*    List<Response__c> respLst = [select id,Response__c,Question_Log__c  from Response__c where Question_Log__c = :quesLogObj.id  and User__C = :userInfo.getUserId()];
                if(respLst.size () > 0)
                {
                    userRespose  = respLst.get(0);
                    showanswer  = true;

                }else
                {
                    userRespose  = new Response__c();
                    userRespose.user__c = userinfo.getUserId();  
                } */
            }
        }  
        else 
        {
            QuesLogObj = new Question_Log__c();
         //   userRespose  = new Response__c();
         //   userRespose.user__c = userinfo.getUserId();  
            isCreate = true;
        }
        
        if(isClone)
        {
            QuesLogObj = QuesLogObj.clone();
         //   userRespose  = new Response__c();
        //    userRespose.user__c = userinfo.getUserId();  
            QuesLogObj.ownerID = Userinfo.getUserID();
            showanswer  = false;
            isCreate = true;

        }
        if(requestID != null && requestID.trim()  != SaaSTextConstant.EMPTY_STRING)
        {
            quesLogObj.Request__c = requestID;
        }
    
    } 
    
        
   /**
    * Save Question 
    * @param args ApexPages.StandardController.
    *
    */        
    public void saveQuestionLog() 
    {                
        String errMsg = null;   
        List<Question_Log__c> questionLst = new List<Question_Log__c>();
        
        quesLogObj.Requested_Date__c = requestedDate;
        quesLogObj.Expected_Close_Date__c = expectedCloseDate;   
        
        List<RecordType> recLst = [Select id from RecordType where  SobjectType = :SaaSTextConstant.QUESTION_OBJ_API_NAME and developerName = :questionType];        
        if(recLst.size() > 0)
        {
            quesLogObj.recordTypeID  = recLst.get(0).id;
        }
        errMsg = validateQuestion();
        // Check if user has entered some invalid data 
        if(errMsg != null)
        {
            SaaSUtility.displayErrMsg(errMsg); 
            return;
        }                                  
        questionLst.add(quesLogObj);
        
        errMsg = SaaSUtility.insertSobject(questionLst);  
        if(errMsg != null)
        {
           SaaSUtility.displayErrMsg(errMsg);     
           return;
        }
        else 
        {
            isSaved  = true;
            SaaSUtility.displaySuccessMsg(SaaSTextConstant.QUESTION_RESPONSE_RECORD_SAVE_MSG );            
        }        
    }
    
   /**
    * Validate the data entered by the user.
    * @return String errmsg
    *
    */    
    @TestVisible private String validateQuestion()
    {
        String errMsg = null;              
        // Validation for Value Delivery Question Type 
        if(questionType == SaaSTextConstant.VALUE_DELIVERY_QUESTION_RECORD_TYPE)
        {
            if(quesLogObj.Scope__c == null || quesLogObj.Scope__c == SaaSTextConstant.EMPTY_STRING)
            {
                errMsg = SaaSTextConstant.QUESTION_SCOPE_EMPTY_ERR_MSG;
            }
            else if(quesLogObj.Sub_Capability__c == null || quesLogObj.Sub_Capability__c == SaaSTextConstant.EMPTY_STRING)
            {
              errMsg =   SaaSTextConstant.QUESTION_SUB_CAPABILITY_EMPTY_ERR_MSG; 
            }
            else if(quesLogObj.Industry__c == Null || quesLogObj.Industry__c ==SaaSTextConstant.EMPTY_STRING )
            {
                errMsg = SaaSTextConstant.QUESTION_INDUSTRY_EMPTY_ERR_MSG;
            }
            else if(quesLogObj.Domain__c== Null || quesLogObj.Domain__c==SaaSTextConstant.EMPTY_STRING )
            {
                errMsg = SaaSTextConstant.QUESTION_DOMAIN_EMPTY_ERR_MSG ;
            }
            
        }
        else if(questionType == SaaSTextConstant.SAAS_QUESTION_RECORD_TYPE)                
        {

            
            if(QuesLogObj.Submitter__c== Null)
            {
                errMsg =  SaaSTextConstant.QUESTION_SUBMITTER_EMPTY_ERR_MSG;
            }
                      
            else if(QuesLogObj.Request__c == Null)
            {
                errMsg =  SaaSTextConstant.QUESTION_REQUEST_EMPTY_ERR_MSG;
            }
        }
        if(questionType == Null || questionType.trim() ==SaaSTextConstant.EMPTY_STRING)
        {
            errMsg =  SaaSTextConstant.QUESTION_RECORD_TYPE_ERROR_MSG;
        } 
        else if(QuesLogObj.Question__c== Null || QuesLogObj.Question__c.trim() ==SaaSTextConstant.EMPTY_STRING)
        {
            errMsg =  SaaSTextConstant.QUESTION_FIELD_EMPTY_ERR_MSG;
        }
        //elseif()
        
        return errMsg; 
    }          
       
   /**
    * Get all record type of question object 
    * @return List<SelectOption>
    *
    */   
    public List<SelectOption> getRecordType() 
    {
        List<SelectOption> recType = new List<SelectOption>();
        recType.add(new SelectOption(SaaSTextConstant.EMPTY_STRING,SaaSTextConstant.NONE_PICKLIST_VALUE ));
        
        List<RecordType> rcordType1 = [Select id ,Name,developerName from RecordType where SobjectType = :SaaSTextConstant.QUESTION_OBJ_API_NAME];
        for(RecordType obj : rcordType1 )
        {
              recType.add(new SelectOption(obj.developerName ,Obj.name));
        }
        return recType;
    }
    
    /**
    *  Disable record type picklist field after picklist is selected 
    * 
    */ 
    public void disbaleRecordType()
    {
        if(questionType != SaaSTextConstant.EMPTY_STRING)
        {
          disableRecType = true;
        }          
    }
 
 
     /**
     * Navigate to Selected Record to convert question to request
     *
     * @param args none.
     * @return PageReference 
     *
     */  
    public PageReference convertToRequest()
    {       
        return new PageReference(SaaSTextConstant.CREATE_REQUEST_VF_PAGE_NAME_URL+'?'+SaaSTextConstant.CONVERT_QUEST+'=1&&'+SaaSTextConstant.CONVERT_QUEST_ID+'='+QuesLogObj.id);  
    } 
   /**
     * Get All Related Request
     *
     * @return List<Related_Request__c >
     *
     */
    public List<Related_Request__c > getRelatedReqLst() 
    {
        return [Select Id, Question_Log__c ,Question_Log__r.name,Request__r.name,Request__r.Request_Description__c,Request__c,Converted_Request__c from Related_Request__c where Question_Log__c = :quesLogObj.id ];      
    } 
     
 
   /**
    * Delete Related Request
    *
    * @param args none.
    * @return none
    *
    */
    public void deleteRecord()
    {
         List<Related_Request__c >   relRequest=[Select Id,Request__c from Related_Request__c where id = :RecordToDelete  ];
         delete relRequest;
    }
    
   /**
    * Create new Question
    * 
    */    
    public void createQuestion()
    {
        isDetail = false;
        quesLogObj = new   Question_Log__c ();
        
        requestedDate = null;    
        expectedCloseDate = null;
        questionType = SaaSTextConstant.EMPTY_STRING;  
        disableRecType  = false;       
        isCreate  = true;     
        showanswer = false; 
    }
    
}