force-app/main/default/objects/Question_Log__c/Question_Log__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a question that a project team member has about a request.</description>
    <label>Question Log</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Question Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Log__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Additional details about Question Log.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Detailed question.</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related request to the question log</description>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Question Log</relationshipLabel>
    <relationshipName>Question_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of Question Log</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Clarification Requested</fullName>
            </value>
            <value>
                <fullName>Clarification Provided</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Submitter__c.field-meta.xml
<CustomField>
    <fullName>Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who submitted the Question Log</description>
    <label>Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Question_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about Release</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Plan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Start_Date__c</fullName>
    <description>Estimated date of Start</description>
    <label>Plan Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Release_Planned_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Planned_End_Date__c</fullName>
    <description>Estimated date of end of release</description>
    <label>Release Planned End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Displays a status as red, green or yellow ball</description>
    <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release__c/fields/Status_Update__c.field-meta.xml
<CustomField>
    <fullName>Status_Update__c</fullName>
    <description>Release status update</description>
    <inlineHelpText>Release status update</inlineHelpText>
    <label>Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Planned_Release__c.field-meta.xml
<CustomField>
    <fullName>Planned_Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates each request to a Release or Project.</description>
    <inlineHelpText>This is the suggested release in which the requirement should be deployed.</inlineHelpText>
    <label>Planned Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipName>CRM_Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Question to be raised with Functional team</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Release in which the request will go</description>
    <inlineHelpText>The release in which the request will actually be deployed. If the requirement has not been approved for a release, there should not be a value in this field.</inlineHelpText>
    <label>Committed Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Requests (Committed Release)</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Description__c.field-meta.xml
<CustomField>
    <fullName>Request_Description__c</fullName>
    <description>Gathers further details for requirements.</description>
    <inlineHelpText>Detailed Summary* 
Screen(s) Impacted* 
Field Name(s) &amp; Type(s)* 
Picklist Values 
Calculation 
Dependency 
Workflow/Approval Rules 
Interfacing System Updates 
Interface Frequency 
Data Volumes 
*Indicates information required for all requests!</inlineHelpText>
    <label>Initial Request</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Title__c.field-meta.xml
<CustomField>
    <fullName>Request_Title__c</fullName>
    <description>Captures the requirement title</description>
    <inlineHelpText>Captures the requirement title</inlineHelpText>
    <label>Request Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>Type of the request</description>
    <inlineHelpText>If you are unsure of the type of request you are submitting, please select Unknown.</inlineHelpText>
    <label>Request Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Configuration</fullName>
            </value>
            <value>
                <fullName>Custom Code</fullName>
            </value>
            <value>
                <fullName>Data Access</fullName>
            </value>
            <value>
                <fullName>Data Migration</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>User Administration</fullName>
            </value>
            <value>
                <fullName>User Story</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the request</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Identify: New Requirement</fullName>
                <default>true</default>
                <label>Identify: New Requirement</label>
            </value>
            <value>
                <fullName>Identify: Submit for Business Review</fullName>
            </value>
            <value>
                <fullName>Identify: Deferred</fullName>
            </value>
            <value>
                <fullName>Consolidate: Approve to Estimate</fullName>
            </value>
            <value>
                <fullName>Consolidate: Level of Effort Complete</fullName>
            </value>
            <value>
                <fullName>Approve: Approved to Deploy</fullName>
            </value>
            <value>
                <fullName>Release: Design</fullName>
            </value>
            <value>
                <fullName>Release: Build</fullName>
            </value>
            <value>
                <fullName>Release: Test</fullName>
            </value>
            <value>
                <fullName>Release: SIT</fullName>
            </value>
            <value>
                <fullName>Release: UAT</fullName>
            </value>
            <value>
                <fullName>Release: Build Production</fullName>
            </value>
            <value>
                <fullName>Release: Test Production</fullName>
            </value>
            <value>
                <fullName>Close: Deployed</fullName>
            </value>
            <value>
                <fullName>Close: Rejected</fullName>
            </value>
            <value>
                <fullName>Close: Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SaaSCreateRequestCtrlTest.cls
@isTest
/** 
 *  Author : Accenture 
 *  Description : Test Class for Controller class for SaaSCreateRequestCtrl
 *  Created Date : 17\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  08\06\2015        created 
 *
 */
 public class SaaSCreateRequestCtrlTest
 {
        static testMethod void validateCreateRequest() 
        {
        Release__c rel = new Release__c();
        rel.Name = 'Test Release ';
        rel.Release__c = 24;
        rel.Plan_Start_Date__c = System.today();
        rel.Release_Planned_End_Date__c= System.today() + 10;
        rel.Status__c = 'Red';
        rel.Description__c = 'Test description ';
        rel.Status_Update__c = 'Test Comments';
        insert rel;
        
               
        Request__c req = new Request__c();
        req.Status__c= 'Identify: New Requirement';
        req.id= null;
        req.Request_Title__c = 'Test description ';
        req.Request_Type__c ='Integration ';
        req.Request_Description__c= 'Test description ';
        req.Planned_Release__c = rel.id;
        insert req;
        
        Question_Log__c questionLogObj  = new Question_Log__c();
       // questionLogObj.RecordTypeId =  '012J00000005IbZ';
        questionLogObj.Request__c = req.id;
        questionLogObj.Submitter__c = Userinfo.getUserId();
        questionLogObj.Question__c = 'Test description ';
        insert questionLogObj; 
        
        
        SaaSCreateRequestCtrl controller = new SaaSCreateRequestCtrl(new ApexPages.StandardController(req));
        controller.saveRequest();
        //controller.validateKeyDecision();
        controller.requestObj.Status__c = null;
        controller.saveRequest();
        controller.requestObj.Status__c = 'Status'; 
        controller.requestObj.Request_Description__c = null;
        controller.saveRequest();
        controller.requestObj.Request_Description__c = 'desc';
        controller.saveRequest();
        controller.requestObj.Request_Type__c = null;
        controller.saveRequest();
        controller.requestObj.Request_Type__c = 'req';
        controller.saveRequest();
        }
        
        static testMethod void validateCreateRequest1()
        {
           Request__c req = new Request__c(); 
           SaaSCreateRequestCtrl controller = new SaaSCreateRequestCtrl(new ApexPages.StandardController(req));
           controller.saveRequest();
           controller.createNewRequest();
           
     
    }
      static testMethod void validateConvertRequest() 
      {
           Release__c rel =SaaSTestUtility.createRelease();
           Request__c req = new Request__c();
           req.Status__c= 'Identify: New Requirement';
           req.Request_Title__c = 'Test description ';
           req.Request_Type__c ='Integration ';
           req.Request_Description__c= 'Test description ';
           req.Release__c = rel.id;
           insert req;
        
           Question_Log__c questionLogObj  = new Question_Log__c();
       // questionLogObj.RecordTypeId =  '012J00000005IbZ';
           questionLogObj.Request__c = req.id;
           questionLogObj.Submitter__c = Userinfo.getUserId();
           questionLogObj.Question__c = 'Test description ';
           insert questionLogObj; 
         
          PageReference pageRef = Page.SaaSCreateRequest;
          pageRef.getParameters().put(SaaSTextConstant.CONVERT_QUEST_ID,questionLogObj.id);
          pageRef.getParameters().put(SaaSTextConstant.RELEASEID_URL_PARAM,rel.id);
          pageRef.getParameters().put(SaaSTextConstant.CONVERT_QUEST, '1');          
          Test.setCurrentPage(pageRef);
          
       /*   Response__c questionLogObj  = SaaSTestUtility.createQuestionResponse();
          PageReference pageRef = Page.SaaSCreateRequest;
          pageRef.getParameters().put(SaaSTextConstant.CONVERT_QUEST_ID,questionLogObj.Question_Log__c);
          pageRef.getParameters().put(SaaSTextConstant.RELEASEID_URL_PARAM,rel.id);
          pageRef.getParameters().put(SaaSTextConstant.CONVERT_QUEST, '1');          
          Test.setCurrentPage(pageRef); */
          SaaSCreateRequestCtrl ctrlObj = new SaaSCreateRequestCtrl(new ApexPages.StandardController(req));
          ctrlObj.saveRequest();
          
          
          
          ctrlObj.createNewRequest();
      
      }        
        static testMethod void validateRequestClone()
        {    
            Release__c rel = new Release__c();
            rel.Name = 'Test Release ';
            rel.Release__c = 24;
            rel.Plan_Start_Date__c = System.today();
            rel.Release_Planned_End_Date__c= System.today() + 10;
            rel.Status__c = 'Red';
            rel.Description__c = 'Test description ';
            rel.Status_Update__c = 'Test Comments';
            insert rel;
        
               
            Request__c req = new Request__c();
            req.Status__c= 'Identify: New Requirement';
            req.Request_Title__c = 'Test description ';
            req.Request_Type__c ='Integration ';
            req.Request_Description__c= 'Test description ';
            req.Release__c = rel.id;
            insert req;
        
            Question_Log__c questionLogObj  = new Question_Log__c();
           // questionLogObj.RecordTypeId =  '012J00000005IbZ';
            questionLogObj.Request__c = req.id;
            questionLogObj.Submitter__c = Userinfo.getUserId();
            questionLogObj.Question__c = 'Test description ';
            insert questionLogObj; 
            
            
            
            PageReference pageRef = Page.SaaSClientQuestionSearch;
            pageRef.getParameters().put(SaaSTextConstant.IS_CLONE_URL_PARAM, '1');
            Test.setCurrentPage(pageRef);
            SaaSCreateRequestCtrl controller = new SaaSCreateRequestCtrl(new ApexPages.StandardController(req));
            controller.saveRequest();
            controller.validateKeyDecision();
        }
        
      
            
 }