force-app/main/default/objects/Question_Log__c/Question_Log__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a question that a project team member has about a request.</description>
    <label>Question Log</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Question Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related request to the question log</description>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Question Log</relationshipLabel>
    <relationshipName>Question_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/recordTypes/Question.recordType-meta.xml
<RecordType>
    <fullName>Question</fullName>
    <active>true</active>
    <description>Question to be raised with Functional team</description>
    <label>Question</label>
</RecordType>

force-app/main/default/classes/SaaSQuestionLogController.cls
public with sharing class SaaSQuestionLogController {
    
    public Question_Log__c QuesLog { get; set; }
    
    public Request__c req;
    
    public SaaSQuestionLogController(ApexPages.StandardController stdcontroller) {
        
        string theId = ApexPages.currentPage().getParameters().get('id');

       QuesLog =new Question_Log__c (); 
       
       QuesLog.Request__c= theId;


    }
    
     public PageReference save() { 
         Id SaaSDeliveryQuestionLogRecTypeId = Schema.SObjectType.Question_Log__c.getRecordTypeInfosByName().get('PMO Question').getRecordTypeid();
         this.QuesLog.RecordTypeId = SaaSDeliveryQuestionLogRecTypeId; 
         
         insert QuesLog;
         
         PageReference requestpage = new ApexPages.StandardController(QuesLog).view();
         requestpage.setRedirect(true);
         return requestpage;
         
     }  
     
     public PageReference cancel() {
        
        PageReference requestpage = new ApexPages.StandardController(QuesLog).view();
        requestpage.setRedirect(true);
        return requestpage;
         
     }   
    
    

}