force-app/main/default/objects/Question_Log__c/Question_Log__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a question that a project team member has about a request.</description>
    <label>Question Log</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Question Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Log__c/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <label>Domain</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Assets/Install Base</fullName>
            </value>
            <value>
                <fullName>Campaign Management</fullName>
            </value>
            <value>
                <fullName>Case Management</fullName>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>Communications Media and Technologies</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Currency Management</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Forecasting</fullName>
            </value>
            <value>
                <fullName>Lead Management</fullName>
            </value>
            <value>
                <fullName>Life Sciences</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Opportunity Management</fullName>
            </value>
            <value>
                <fullName>Outlook</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Reports and Dashboards</fullName>
            </value>
            <value>
                <fullName>Retail Marketing</fullName>
            </value>
            <value>
                <fullName>Search Marketing</fullName>
            </value>
            <value>
                <fullName>Tasks and Activities</fullName>
            </value>
            <value>
                <fullName>User Management</fullName>
            </value>
            <value>
                <fullName>Website Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Communications, Media and Technology</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Health &amp; Public Services</fullName>
            </value>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Resources</fullName>
            </value>
            <value>
                <fullName>Cross-Industry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Detailed question.</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related request to the question log</description>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Question Log</relationshipLabel>
    <relationshipName>Question_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Plan and Analyze</fullName>
            </value>
            <value>
                <fullName>Scope</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Deploy</fullName>
            </value>
            <value>
                <fullName>Initiate and Confirm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Sub_Capability__c.field-meta.xml
<CustomField>
    <fullName>Sub_Capability__c</fullName>
    <label>Sub-Capability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Account Hierarchy</fullName>
            </value>
            <value>
                <fullName>Account Maintenance</fullName>
            </value>
            <value>
                <fullName>Account Ownership and Assignment</fullName>
            </value>
            <value>
                <fullName>Case Solutions</fullName>
            </value>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Custom Reports</fullName>
            </value>
            <value>
                <fullName>Dashboards</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Definition</fullName>
            </value>
            <value>
                <fullName>Email Marketing</fullName>
            </value>
            <value>
                <fullName>Fields</fullName>
            </value>
            <value>
                <fullName>Files and Attachments</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Knowledge Articles</fullName>
            </value>
            <value>
                <fullName>Lead Assignment</fullName>
            </value>
            <value>
                <fullName>Lead Conversion</fullName>
            </value>
            <value>
                <fullName>Lead Creation</fullName>
            </value>
            <value>
                <fullName>Lead Qualification</fullName>
            </value>
            <value>
                <fullName>Lead Source</fullName>
            </value>
            <value>
                <fullName>Lead Workflow Process</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Managing Multiple Currencies</fullName>
            </value>
            <value>
                <fullName>Ownership</fullName>
            </value>
            <value>
                <fullName>Page Layouts</fullName>
            </value>
            <value>
                <fullName>Permissions</fullName>
            </value>
            <value>
                <fullName>Pricing Book</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Product Catalog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Log__c/fields/Submitter__c.field-meta.xml
<CustomField>
    <fullName>Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who submitted the Question Log</description>
    <label>Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Question_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <description>Release Number</description>
    <label>Release #</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Question to be raised with Functional team</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Release in which the request will go</description>
    <inlineHelpText>The release in which the request will actually be deployed. If the requirement has not been approved for a release, there should not be a value in this field.</inlineHelpText>
    <label>Committed Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Requests (Committed Release)</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SaaSCreateQuestionLogCtrlTest.cls
@isTest
/** 
 *  Author : Accenture 
 *  Description : Test Class for Controller class for SaaSCreateQuestionLogCtrl
 *  Created Date : 05\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  08\06\2015        created 
 *
 */
 public class SaaSCreateQuestionLogCtrlTest
{
    static testMethod void validateQuestionLog()
    {
        Release__c rel = SaaSTestUtility.createRelease();
        Request__c req = SaaSTestUtility.createRequest();
        Question_Log__c questionLogObj  = new Question_Log__c();
        questionLogObj.Request__c = req.id;
        questionLogObj.Submitter__c = Userinfo.getUserId();
        questionLogObj.Question__c = 'Test description ';
        questionLogObj.Sub_Capability__c='Access';
        questionLogObj.Industry__c='Financial Services';
        questionLogObj.Scope__c='Plan and Analyze';
      //questionLogObj.Submitter__c='ana lam';
       // questionLogObj.Request__c='Create Lead conversion Process';
        insert questionLogObj;
            
        
     
        
        SaaSCreateQuestionLogCtrl controller = new SaaSCreateQuestionLogCtrl(new ApexPages.StandardController(questionLogObj ));
        controller.questionType=SaaSTextConstant.VALUE_DELIVERY_QUESTION_RECORD_TYPE;
        controller.saveQuestionLog();
        controller.quesLogObj.Scope__c = null;
        controller.saveQuestionLog();
        controller.quesLogObj.Scope__c = 'test';
        controller.saveQuestionLog();
        controller.quesLogObj.Sub_Capability__c = null;
        controller.saveQuestionLog();
        controller.quesLogObj.Sub_Capability__c = 'sub';
        controller.saveQuestionLog();
        controller.quesLogObj.Industry__c = null;
        controller.saveQuestionLog();
        controller.quesLogObj.Industry__c = 'test';
        controller.saveQuestionLog();
        controller.QuesLogObj.Question__c = null;
        controller.saveQuestionLog();
        controller.QuesLogObj.Question__c = 'ques';
        controller.saveQuestionLog();
        controller.questionType=SaaSTextConstant.SAAS_QUESTION_RECORD_TYPE;
        controller.QuesLogObj.Request__c = null;        
        controller.saveQuestionLog();
        controller.QuesLogObj.Submitter__c = null;
        controller.saveQuestionLog();
        
        controller.questionType= SaaSTextConstant.VALUE_DELIVERY_QUESTION_RECORD_TYPE ;
         controller.QuesLogObj.Domain__c = 'Domain';       
        controller.saveQuestionLog();
     
        //controller.validateQuestion();
       
       // controller.validateQuestion();
        controller.getRecordType();
       // controller.showans();
        //controller.saveAnswer();
        controller.convertToRequest();
        controller.disbaleRecordType();
        controller.deleteRecord(); 
        controller.getRelatedReqLst();
       
     }
     
        
    static testMethod void validateQuestionLogclone()
    {
        Release__c rel = SaaSTestUtility.createRelease().clone();
        Request__c req = SaaSTestUtility.createRequest();        
        Question_Log__c questionLogObj  = SaaSTestUtility.createSaaSQuestion();
        PageReference pageRef = Page.SaaSCreateQuestionLog;
        pageRef.getParameters().put(SaaSTextConstant.IS_CLONE_URL_PARAM, '1');
        pageRef.getParameters().put(SaaSTextConstant.REQUEST_ID_URL_PARAM,req.id);
        Test.setCurrentPage(pageRef);      
        SaaSCreateQuestionLogCtrl controller = new SaaSCreateQuestionLogCtrl(new ApexPages.StandardController(questionLogObj ));
        controller.saveQuestionLog();
        controller.getRecordType();
                
        controller.validateQuestion();
        controller.convertToRequest();
        controller.disbaleRecordType();
        controller.createQuestion();
       // controller.saveAnswer();    
       
        controller = new SaaSCreateQuestionLogCtrl(new ApexPages.StandardController(new Question_Log__c()));
       
       
         
      }
        
          
         
    }