force-app/main/default/objects/Value_Delivery_Session__c/Value_Delivery_Session__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session</label>
    <nameField>
        <label>Value Delivery Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/Value_Delivery_Session_Outcomes__c.object-meta.xml
<CustomObject>
    <label>Value Delivery Session Outcomes</label>
    <nameField>
        <label>Session Outcomes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Delivery Session Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiate And Confirm</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Value_Delivery_Session_Outcomes__c/fields/Value_Delivery_Session__c.field-meta.xml
<CustomField>
    <fullName>Value_Delivery_Session__c</fullName>
    <label>Value Delivery Session</label>
    <referenceTo>Value_Delivery_Session__c</referenceTo>
    <relationshipName>Session_Outcomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SaaSPageTemplateCtrl.cls
public class SaaSPageTemplateCtrl 
{
    public String getUserPhotoUrl() 
    {
        list<user> userList = [select SmallPhotoUrl from user where id=:userinfo.getuserid()];
        return userList.get(0).SmallPhotoUrl ;
    }
    
      
    public List<Value_Delivery_Session_Outcomes__c> getDesginSessionOutcomes()
    {
        return [Select id, name, Phase__c from Value_Delivery_Session_Outcomes__c where Phase__c = 'Design' and Value_Delivery_Session__c = :SaaSUtility.getLoggedInValueSession()  ];        
    }
    
       public List<Value_Delivery_Session_Outcomes__c> getBuildSessionOutcomes()
    {
        return [Select id, name, Phase__c from Value_Delivery_Session_Outcomes__c where Phase__c = 'Build' and Value_Delivery_Session__c = :SaaSUtility.getLoggedInValueSession()  ];        
    }
    
      public List<Value_Delivery_Session_Outcomes__c> getInitiateSessionOutcomes()
    {
        return [Select id, name, Phase__c from Value_Delivery_Session_Outcomes__c where Phase__c = 'Initiate And Confirm' and Value_Delivery_Session__c = :SaaSUtility.getLoggedInValueSession()  ];        
    }
   
}