force-app/main/default/objects/Test_Execution__c/Test_Execution__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - An object that represents the execution of a test script in a specific case.</description>
    <label>Test Script Execution</label>
    <nameField>
        <displayFormat>TE-{0}</displayFormat>
        <label>Test Execution ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Execution__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Comments on the test execution</description>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Execution__c/fields/Execution_Cycle_Name__c.field-meta.xml
<CustomField>
    <fullName>Execution_Cycle_Name__c</fullName>
    <label>Execution Cycle Name</label>
    <referenceTo>Test_Execution_Cycle__c</referenceTo>
    <relationshipName>Test_Executions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Test_Execution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Execution__c/fields/Test_Executor__c.field-meta.xml
<CustomField>
    <fullName>Test_Executor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Executor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Test_Script_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Execution_Steps__c/Test_Execution_Steps__c.object-meta.xml
<CustomObject>
    <label>Test Execution Steps</label>
    <nameField>
        <label>Execution Steps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Execution Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Execution_Steps__c/fields/Actual_Result__c.field-meta.xml
<CustomField>
    <fullName>Actual_Result__c</fullName>
    <label>Actual Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Execution_Steps__c/fields/Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Execution_Steps__c/fields/Input_Data__c.field-meta.xml
<CustomField>
    <fullName>Input_Data__c</fullName>
    <label>Input Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Execution_Steps__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Execution_Steps__c/fields/Step_Order__c.field-meta.xml
<CustomField>
    <fullName>Step_Order__c</fullName>
    <label>Step Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Test_Execution_Steps__c/fields/Test_Execution_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Execution_Name__c</fullName>
    <label>Test Execution Name</label>
    <referenceTo>Test_Execution__c</referenceTo>
    <relationshipLabel>Test Execution Steps</relationshipLabel>
    <relationshipName>Test_Execution_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VFC_Test_Execution_InlineEdit.cls
public with sharing class VFC_Test_Execution_InlineEdit {
    
    Public String eId {get;set;}   
    public Task tsk{get;set;} 
    Public List<Test_Execution_Steps__c> testExstps {get;set;}
    Public List<Test_Execution__c> testExs {get;set;}
    private ApexPages.StandardController stdController;
 
    
    public VFC_Test_Execution_InlineEdit(ApexPages.StandardController controller) {
        this.stdController= Controller;
        eId = apexpages.currentPage().getParameters().get('Id');        
        testExstps = new List<Test_Execution_Steps__c>();
        testExs = new List<Test_Execution__c>();
        testExstps = [Select id,Name,Actual_Result__c,Status__c,Step_Order__c,Expected_Result__c,Input_Data__c,User_Login_Details__c,Test_Execution_Name__c,Test_Execution_Name__r.Comments__c,Test_Execution_Name__r.Status__c from Test_Execution_Steps__c 
                       where Test_Execution_Name__c  =:eId ORDER BY Step_Order__c ASC ];        
        tsk = new task();
        //tsk.OwnerId = UserInfo.getuserid();
        testExs = [Select id,name,Status__c,Test_Executor__c,Execution_Cycle_Name__c,Comments__c from Test_Execution__c
                 ];
        
    }
    

    public PageReference saveAndCongrat() {
       upsert testExstps;
       if(stdController.save()!=null){ // This takes care of the details for you.
       PageReference pageRef = new PageReference('/'+eid);
       pageRef.setRedirect(true);
       return pageRef; 
      }
      return null; 
      }

      public PageReference saveSteps(){         
        upsert testExstps;
        PageReference pageRef = new PageReference('/'+eid);
        pageRef.setRedirect(true);
        return pageRef;                  
    }
    
        public PageReference cancelB(){
      
       return new PageReference('/' + eId);

           
    }
    }